/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { BookDefinition } from '../../..';
import author from './author';
import genre from './genre';
import title from './title';

const book: BookDefinition = {
  author,
  genre,
  title,
};

export default book;
