/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CompanyDefinitions } from '../../..';
import adjective from './adjective';
import bs_adjective from './bs_adjective';
import bs_noun from './bs_noun';
import bs_verb from './bs_verb';
import descriptor from './descriptor';
import name_ from './name';
import noun from './noun';
import suffix from './suffix';

const company: CompanyDefinitions = {
  adjective,
  bs_adjective,
  bs_noun,
  bs_verb,
  descriptor,
  name: name_,
  noun,
  suffix,
};

export default company;
