/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { DrinkDefinitions } from '../../..';
import brand from './brand';
import category from './category';
import description from './description';
import _name from './name';

const drink: DrinkDefinitions = {
  name: _name,
  description,
  brand,
  category,
};

export default drink;
