/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'יום חמישי',
    'יום ראשון',
    'יום רביעי',
    'יום שבת',
    'יום שישי',
    'יום שלישי',
    'יום שני',
  ],
  abbr: ['יום א׳', 'יום ב׳', 'יום ג׳', 'יום ד׳', 'יום ה׳', 'יום ו׳', 'שבת'],
};
