/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import animal from './animal';
import app from './app';
import beer from './beer';
import book from './book';
import business from './business';
import cell_phone from './cell_phone';
import clothing from './clothing';
import color from './color';
import commerce from './commerce';
import company from './company';
import computer from './computer';
import database from './database';
import date from './date';
import finance from './finance';
import flights from './flights';
import flower from './flower';
import food from './food';
import glasses from './glasses';
import hacker from './hacker';
import internet from './internet';
import jewels from './jewels';
import liquor from './liquor';
import location from './location';
import lorem from './lorem';
import movie from './movie';
import music from './music';
import parfum from './parfum';
import person from './person';
import phone from './phone';
import plant from './plant';
import recipe from './recipe';
import science from './science';
import shoes from './shoes';
import stays from './stays';
import system from './system';
import team from './team';
import tire from './tire';
import vehicle from './vehicle';
import watch from './watch';
import wheel from './wheel';
import wine from './wine';
import word from './word';

const en: LocaleDefinition = {
  title: 'English',
  separator: ' & ',
  animal,
  app,
  beer,
  book,
  business,
  cell_phone,
  clothing,
  color,
  commerce,
  company,
  computer,
  database,
  date,
  finance,
  flights,
  flower,
  food,
  glasses,
  hacker,
  internet,
  jewels,
  liquor,
  location,
  lorem,
  movie,
  music,
  parfum,
  person,
  phone,
  plant,
  recipe,
  science,
  shoes,
  stays,
  system,
  team,
  tire,
  vehicle,
  watch,
  wheel,
  wine,
  word,
};

export default en;
