/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import address from './address';
import animal from './animal';
import app from './app';
import business from './business';
import cell_phone from './cell_phone';
import color from './color';
import commerce from './commerce';
import company from './company';
import database from './database';
import date from './date';
import finance from './finance';
import hacker from './hacker';
import internet from './internet';
import lorem from './lorem';
import music from './music';
import name_ from './name';
import phone_number from './phone_number';
import science from './science';
import system from './system';
import team from './team';
import vehicle from './vehicle';
import word from './word';

const en: LocaleDefinition = {
  title: 'English',
  separator: ' & ',
  address,
  animal,
  app,
  business,
  cell_phone,
  color,
  commerce,
  company,
  database,
  date,
  finance,
  hacker,
  internet,
  lorem,
  music,
  name: name_,
  phone_number,
  science,
  system,
  team,
  vehicle,
  word,
};

export default en;
