/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CompanyDefinition } from '../../..';
import adjective from './adjective';
import legal_entity_type from './legal_entity_type';
import name_pattern from './name_pattern';
import noun from './noun';

const company: CompanyDefinition = {
  adjective,
  legal_entity_type,
  name_pattern,
  noun,
};

export default company;
