/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CompanyDefinition } from '../../..';
import adjective from './adjective';
import name_pattern from './name_pattern';
import noun from './noun';
import suffix from './suffix';

const company: CompanyDefinition = {
  adjective,
  name_pattern,
  noun,
  suffix,
};

export default company;
