/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'abril',
    'agosto',
    'diciembre',
    'enero',
    'febrero',
    'julio',
    'junio',
    'marzo',
    'mayo',
    'noviembre',
    'octubre',
    'septiembre',
  ],
  abbr: [
    'abr',
    'ago',
    'dic',
    'ene',
    'feb',
    'jul',
    'jun',
    'mar',
    'may',
    'nov',
    'oct',
    'sep',
  ],
};
