/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'April',
    'August',
    'Dezember',
    'Februar',
    'Januar',
    'Juli',
    'Juni',
    'Mai',
    'März',
    'November',
    'Oktober',
    'September',
  ],
  abbr: [
    'Apr',
    'Aug',
    'Dez',
    'Feb',
    'Jan',
    'Jul',
    'Jun',
    'Mai',
    'Mär',
    'Nov',
    'Okt',
    'Sep',
  ],
};
