/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'Dienstag',
    'Donnerstag',
    'Freitag',
    'Mittwoch',
    'Montag',
    'Samstag',
    'Sonntag',
  ],
  abbr: ['Di', 'Do', 'Fr', 'Mi', 'Mo', 'Sa', 'So'],
};
