/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { FabricDefinitions } from '../../..';
import category from './category';
import composition from './composition';
import description from './description';
import name_ from './name';
import style from './style';

const fabric: FabricDefinitions = {
  category,
  composition,
  description,
  name: name_,
  style,
};

export default fabric;
