/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CompanyDefinitions } from '../../..';
import adjective from './adjective';
import descriptor from './descriptor';
import name_patterns from './name_patterns';
import noun from './noun';
import suffix from './suffix';

const company: CompanyDefinitions = {
  adjective,
  descriptor,
  name_patterns,
  noun,
  suffix,
};

export default company;
