/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CompanyDefinition } from '../../..';
import legal_form from './legal_form';
import name_pattern from './name_pattern';
import suffix from './suffix';

const company: CompanyDefinition = {
  legal_form,
  name_pattern,
  suffix,
};

export default company;
