export default [
  'Set of 250 pieces to build your cute hearts: match colors and numbers to create your own mosaic composition! Follow the pattern and match the colors correctly to create cute hearts with the Plus-Plus puzzle by number!',
  'Build a food court for Eevee and Lucario characters. This set combines with other Adventure Builder sets to create an even larger Pokémon world full of authentic detail. Discover Pikachu Beach Fun, Bulbasaur Forest or other even larger sets, each sold separately. MEGA Pokémon building toys are designed for kids over 7 years',
  'Build a refreshment stand for Eevee and Lucario characters. This set combines with other Adventure Builder sets to create an even larger Pokémon world full of authentic detail. Discover Pikachu Beach Fun, Bulbasaur Forest or other even larger sets, each sold separately. MEGA Pokémon building toys are designed for children over the age of 7',
  'One motorcycle: five creations. A fun and exciting model kit to make with this Meccano set. Kids can have fun assembling and reassembling motorcycles and sports cars. While using this S.T.E.A.M. construction kit, they will learn the principles of science, technology, engineering, art and math.',
  'This cool LEGO Technic Formula E® Porsche 99X Electric (42137) race car model with pull-back system is the perfect gift for all Formula E® and Porsche fans aged 9 and up. With this model of the famous Porsche, children can immerse themselves in an immersive building experience, recreating all the details of the real car and reliving all the emotions of the real race, thanks to the 2 pull-back motors and the LEGO Technic reality app. augmented (AR).',
  'Give young fans aged 9 and up the perfect gift: the Iron Man action figure. 24 cm tall, the LEGO Marvel Iron Man Figure (76206) is ready to give kids hours and hours of exciting Marvel-themed adventures Super Heroes. Inspired by the Avengers: Age of Ultron movie, this realistic reproduction is fully articulated and ready to embark on daring missions against villains.',
  'Take kids who love sea animals on a fantasy journey to the bottom of the ocean with the LEGO DUPLO Ocean Animals (10972) set. A playset that offers infinite possibilities for the development of preschool children, thanks to a three-dimensional play mat that depicts a seabed and 4 sweet toy animals.',
  "Young witches, wizards and muggles aged 8 and up can experience fantastic adventures with this multi-level LEGO Harry Potter Hogwarts: Dumbledore's Office (76402) set, featuring different areas and authentic details from the famous film saga. Young fans of Harry Potter games will find magic and adventure in every room of this toy castle.",
  'Discover fun creative toys for kids in the LEGO Creator Creatures of the Forest Fantasy 3in1 (31125) building set. This toy animal set for children aged 7 and up allows you to create many fantastic stories in the woods. One of the 3 models included is a wise toy owl with a posable head, tail, wings and feathers, reading a storybook to a hedgehog.',
  'Stable to accommodate up to 3 ponies and large fenced outdoor area for the first strolls. The upper floor houses provisions and equipment for the care of the horses.',
  'The original Batman in 30 centimeters scale. With 11 points of articulation it is possible to move and position it at will in heroic poses. With realistic colors and decorations, he also has a cloth cape. Children can enjoy reliving the adventures of Gotham City with the most iconic hero ever.',
  'Dinosaurs have returned to earth! Live great adventures with this playset - Lights and sounds - Moving parts - Available in 2 models',
];
