/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { SmokingRollingPaperDefinitions } from '../../..';
import brand from './brand';
import size from './size';

const smokingRollingPaper: SmokingRollingPaperDefinitions = {
  brand,
  size,
};

export default smokingRollingPaper;
