/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { FoodDefinition } from '../../..';
import adjective from './adjective';
import description_pattern from './description_pattern';
import dish from './dish';
import dish_pattern from './dish_pattern';
import ethnic_category from './ethnic_category';
import fruit from './fruit';
import ingredient from './ingredient';
import meat from './meat';
import spice from './spice';
import vegetable from './vegetable';

const food: FoodDefinition = {
  adjective,
  description_pattern,
  dish,
  dish_pattern,
  ethnic_category,
  fruit,
  ingredient,
  meat,
  spice,
  vegetable,
};

export default food;
