/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import metadata from './metadata';
import person from './person';

/**
 * The locale data for the `yo_NG` locale.
 *
 * - Language: Yoruba (Nigeria)
 * - Endonym: Yoruba (Naijiria)
 */
const yo_NG: LocaleDefinition = {
  metadata,
  person,
};

export default yo_NG;
