/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { HackerDefinition } from '../../..';
import abbreviation from './abbreviation';
import adjective from './adjective';
import ingverb from './ingverb';
import noun from './noun';
import phrase from './phrase';
import verb from './verb';

const hacker: HackerDefinition = {
  abbreviation,
  adjective,
  ingverb,
  noun,
  phrase,
  verb,
};

export default hacker;
