/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinition } from '../../..';
import city_name from './city_name';
import city_pattern from './city_pattern';
import continent from './continent';
import country from './country';
import county from './county';
import state from './state';

const location: LocationDefinition = {
  city_name,
  city_pattern,
  continent,
  country,
  county,
  state,
};

export default location;
