/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import animal from './animal';
import book from './book';
import color from './color';
import date from './date';
import location from './location';
import metadata from './metadata';
import person from './person';
import vehicle from './vehicle';

/**
 * The locale data for the `cy` locale.
 *
 * - Language: Welsh
 * - Endonym: Cymraeg
 */
const cy: LocaleDefinition = {
  animal,
  book,
  color,
  date,
  location,
  metadata,
  person,
  vehicle,
};

export default cy;
