/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinitions } from '../../..';
import building_number from './building_number';
import city from './city';
import default_country from './default_country';
import postcode from './postcode';
import state from './state';
import state_abbr from './state_abbr';
import street_cantonese_part from './street_cantonese_part';
import street_english_part from './street_english_part';
import street_pattern from './street_pattern';
import street_prefix from './street_prefix';
import street_suffix from './street_suffix';

const location: LocationDefinitions = {
  building_number,
  city,
  default_country,
  postcode,
  state,
  state_abbr,
  street_cantonese_part,
  street_english_part,
  street_pattern,
  street_prefix,
  street_suffix,
};

export default location;
