export default [
  'Set mit 250 Teilen zum Bauen Ihrer süßen Herzen: Kombinieren Sie Farben und Zahlen, um Ihre eigene Mosaikkomposition zu erstellen! Folge dem Muster und kombiniere die Farben richtig, um niedliche Herzen mit dem Plus-Plus-Puzzle nach Zahlen zu erstellen!',
  'Baue einen Food Court für Eevee- und Lucario-Charaktere. Dieses Set lässt sich mit anderen Adventure Builder-Sets kombinieren, um eine noch größere Pokémon-Welt voller authentischer Details zu erschaffen. Entdecken Sie Pikachu Beach Fun, Bulbasaur Forest oder andere noch größere Sets, die jeweils separat erhältlich sind. MEGA-Pokémon-Bauspielzeuge sind für Kinder ab 7 Jahren konzipiert',
  'Baue einen Erfrischungsstand für Eevee- und Lucario-Charaktere. Dieses Set lässt sich mit anderen Adventure Builder-Sets kombinieren, um eine noch größere Pokémon-Welt voller authentischer Details zu erschaffen. Entdecken Sie Pikachu Beach Fun, Bulbasaur Forest oder andere noch größere Sets, die jeweils separat erhältlich sind. MEGA-Pokémon-Bauspielzeuge sind für Kinder ab 7 Jahren konzipiert.',
  'Ein Motorrad: fünf Kreationen. Ein lustiger und spannender Modellbausatz zum Bauen mit diesem Meccano-Set. Kinder können sich beim Auf- und Abbau von Motorrädern und Sportwagen vergnügen. Bei der Verwendung dieses S.T.E.A.M. Baukasten lernen sie die Grundlagen von Wissenschaft, Technologie, Ingenieurwesen, Kunst und Mathematik.',
  'Dieses coole LEGO Technic Formel E® Porsche 99X Electric (42137) Rennwagenmodell mit Rückholsystem ist das perfekte Geschenk für alle Formel E® und Porsche Fans ab 9 Jahren. Mit diesem Modell des berühmten Porsche können Kinder dank der 2 Rückziehmotoren und der LEGO Technic Reality-App in ein fesselndes Bauerlebnis eintauchen, alle Details des echten Autos nachbilden und alle Emotionen des echten Rennens nacherleben . erweitert (AR).',
  'Schenken Sie jungen Fans ab 9 Jahren das perfekte Geschenk: die Iron Man Actionfigur. Die 24 cm große LEGO Marvel Iron Man-Figur (76206) ist bereit, Kindern stundenlange, aufregende Superhelden-Abenteuer im Marvel-Stil zu bieten. Inspiriert vom Film „Avengers: Age of Ultron“, ist diese realistische Reproduktion voll artikuliert und bereit, sich auf waghalsige Missionen gegen Schurken zu begeben.',
  'Nehmen Sie mit dem LEGO DUPLO Set Meerestiere (10972) Kinder, die Meerestiere lieben, mit auf eine Fantasiereise auf den Grund des Ozeans. Ein Spielset, das dank einer dreidimensionalen Spielmatte, die einen Meeresboden und 4 süße Spielzeugtiere darstellt, unendliche Möglichkeiten für die Entwicklung von Vorschulkindern bietet.',
  'Junge Hexen, Zauberer und Muggel ab 8 Jahren können mit diesem mehrstöckigen Set LEGO Harry Potter Hogwarts: Dumbledores Büro (76402) fantastische Abenteuer erleben, das verschiedene Bereiche und authentische Details aus der berühmten Filmsaga enthält. Junge Fans von Harry-Potter-Spielen finden Magie und Abenteuer in jedem Raum dieses Spielzeugschlosses.',
  'Entdecken Sie lustige kreative Spielzeuge für Kinder im LEGO Creator Creatures of the Forest Fantasy 3-in-1-Bauset (31125). Mit diesem Spieltier-Set für Kinder ab 7 Jahren lassen sich viele fantastische Geschichten im Wald erfinden. Eines der 3 enthaltenen Modelle ist eine weise Spielzeugeule mit beweglichem Kopf, Schwanz, Flügeln und Federn, die einem Igel ein Märchenbuch vorliest.',
  'Stall für bis zu 3 Ponys und großer eingezäunter Außenbereich für die ersten Spaziergänge. Im Obergeschoss befinden sich Vorräte und Geräte für die Pflege der Pferde.',
  'Der Original-Batman im 30-Zentimeter-Maßstab. Mit 11 Artikulationspunkten ist es möglich, es in heroischen Posen nach Belieben zu bewegen und zu positionieren. Mit realistischen Farben und Dekorationen hat er auch einen Stoffumhang. Kinder können die Abenteuer von Gotham City mit dem berühmtesten Helden aller Zeiten noch einmal erleben.',
  'Dinosaurier sind auf die Erde zurückgekehrt! Erleben Sie großartige Abenteuer mit diesem Spielset - Lichter und Geräusche - Bewegliche Teile - Erhältlich in 2 Modellen',
];
