/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { ToyDefinitions } from '../../..';
import age from './age';
import brand from './brand';
import category from './category';
import description from './description';
import name_ from './name';

const toy: ToyDefinitions = {
  age,
  brand,
  category,
  description,
  name: name_,
};

export default toy;
