/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CompanyDefinitions } from '../../..';
import name_ from './name';
import suffix from './suffix';

const company: CompanyDefinitions = {
  name: name_,
  suffix,
};

export default company;
