/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PersonDefinition } from '../../..';
import bio_part from './bio_part';
import bio_pattern from './bio_pattern';
import first_name from './first_name';
import gender from './gender';
import last_name from './last_name';
import last_name_pattern from './last_name_pattern';
import name_ from './name';
import prefix from './prefix';
import sex from './sex';
import western_zodiac_sign from './western_zodiac_sign';

const person: PersonDefinition = {
  bio_part,
  bio_pattern,
  first_name,
  gender,
  last_name,
  last_name_pattern,
  name: name_,
  prefix,
  sex,
  western_zodiac_sign,
};

export default person;
