/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PersonDefinition } from '../../..';
import female_first_name from './female_first_name';
import female_prefix from './female_prefix';
import first_name from './first_name';
import last_name from './last_name';
import last_name_pattern from './last_name_pattern';
import male_first_name from './male_first_name';
import male_prefix from './male_prefix';
import name_ from './name';
import prefix from './prefix';
import sex from './sex';
import suffix from './suffix';
import title from './title';
import western_zodiac_sign from './western_zodiac_sign';

const person: PersonDefinition = {
  female_first_name,
  female_prefix,
  first_name,
  last_name,
  last_name_pattern,
  male_first_name,
  male_prefix,
  name: name_,
  prefix,
  sex,
  suffix,
  title,
  western_zodiac_sign,
};

export default person;
