/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AddressDefinitions } from '../../..';
import building_number from './building_number';
import city from './city';
import city_name from './city_name';
import country from './country';
import default_country from './default_country';
import postcode from './postcode';
import secondary_address from './secondary_address';
import state from './state';
import street from './street';
import street_address from './street_address';
import street_name from './street_name';
import street_suffix from './street_suffix';

const address: AddressDefinitions = {
  building_number,
  city,
  city_name,
  country,
  default_country,
  postcode,
  secondary_address,
  state,
  street,
  street_address,
  street_name,
  street_suffix,
};

export default address;
