/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { NameDefinitions } from '../../..';
import female_first_name from './female_first_name';
import female_last_name from './female_last_name';
import first_name from './first_name';
import last_name from './last_name';
import male_first_name from './male_first_name';
import male_last_name from './male_last_name';
import name_ from './name';
import prefix from './prefix';
import suffix from './suffix';
import title from './title';

const name: Partial<NameDefinitions> = {
  female_first_name,
  female_last_name,
  first_name,
  last_name,
  male_first_name,
  male_last_name,
  name: name_,
  prefix,
  suffix,
  title,
};

export default name;
