export default [
  'Lancé en 1988 en tant que premier brandy de solera, il est fabriqué à partir de raisins de brandy de qualité et produit selon une méthode de vieillissement hautement cultivée qui offre un goût fin et une texture lisse.',
  "Gordon's Gin est le gin le plus vendu au monde. Il a reçu quatre mandats royaux ainsi qu'une multitude de prix internationaux du gin. Depuis sa création, ils exportent du gin dans le monde entier et lui ont valu le titre de gin préféré du monde",
  'Peignez la ville de plusieurs couleurs avec ce shooter clair à base de vodka avec de la gelée comestible aux couleurs vives flottant autour pour votre prochain plaisir. Amusant à boire et à partager avec des amis.',
  "Avec des 'comètes' comestibles aux couleurs de l'arc-en-ciel qui flottent, cette vodka à base d'acide vous donnera l'énergie nécessaire pour la secouer sur la piste de danse.",
  "Ce shooter à base de vodka et de bubble-gum acidulé emmènera vos papilles gustatives dans l'espace.",
  "Inspiré par les jungles subtropicales d'Afrique australe, Sour Monkey est un jeu de tir sauvage à faible teneur en alcool. L'expérience de consommation est exaltante : elle taquinera votre langue avec une douce explosion fruitée, puis tout à coup une saveur aigre-douce vous plissera les lèvres et choquera vos sens.",
  "Ce rhum exquis perpétue la tradition séculaire d'exportation de rhum en fûts. Un mélange cohérent de rhums noirs jamaïcains et sud-africains exceptionnels, vieillis en fût de chêne pour fournir un mélange riche et de caractère avec une saveur douce et agréable.",
  'Cette liqueur aigre-douce au goût de baies est excellente dans un shooter ou dans un verre de soda au citron vert. Lancez la fête avec cette liqueur aromatisée exquise.',
  "Chatouillez votre folie intérieure avec une liqueur de cocktail onctueuse et décadente infusée de biscuits et de saveurs de chocolat crémeux. Une boisson classique après le dîner, lui donnant le goût, l'apparence et la sensation d'une boisson à tout moment, tout le temps - pourquoi attendre après le dîner ?",
  "Un merveilleux mélange de traditions séculaires et d'inventions uniques en son genre a donné naissance à une gamme de cognacs, qui sont aujourd'hui connus dans le monde entier. Le Courvoisier V.S est un cognac gracieux et bien équilibré avec des arômes proéminents de fruits frais et de bois.",
  'Une décadente liqueur de café et de crème à la vanille dans une bouteille distinctive en forme de corne de rhinocéros. Idéal servi sur glace dans un petit verre.',
  "Ce gin primé est suffisamment polyvalent pour vos mélangeurs préférés mais suffisamment complexe pour intriguer le connaisseur de gin. Il se marie bien avec les fruits de mer comme les crevettes et le saumon, et est tout aussi agréable avec un curry d'agneau ou des fromages affinés.",
];
