/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'csütörtök',
    'hétfő',
    'kedd',
    'péntek',
    'szerda',
    'szombat',
    'vasárnap',
  ],
  abbr: ['Cs', 'H', 'K', 'P', 'Sze', 'Szo', 'V'],
};
