/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { HackerDefinitions } from '../../..';
import adjective from './adjective';
import noun from './noun';
import phrase from './phrase';
import verb from './verb';

const hacker: HackerDefinitions = {
  adjective,
  noun,
  phrase,
  verb,
};

export default hacker;
