/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { SofaDefinitions } from '../../..';
import category from './category';
import material from './material';
import name_ from './name';
import sitting from './sitting';
import style from './style';

const sofa: SofaDefinitions = {
  category,
  material,
  name: name_,
  sitting,
  style,
};

export default sofa;
