/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { HackerDefinition } from '../../..';
import adjective from './adjective';
import ingverb from './ingverb';
import noun from './noun';
import phrase from './phrase';
import verb from './verb';
import verbed from './verbed';

const hacker: HackerDefinition = {
  adjective,
  ingverb,
  noun,
  phrase,
  verb,
  verbed,
};

export default hacker;
