export default [
  "Das 'Monflowers‘ ist ein Blanche-Bier mit einem sehr erfrischenden und frischen Timbre, inspiriert von der belgischen Tradition und aus einer Mischung von Gewürzen und Monferrato-Blüten, piemontesischem Malz und Weizen gewonnen. Die Nase erzählt zarte Noten von Weizen, Getreide und Weizen, unterstützt von einem Hauch von Honig, der von italienischem Malz mitgebracht wird. Der Schluck ist leicht, dünn, mit einem erfrischenden und sehr weichen Getränk.",
  'Eporedian Pale Ale ist ein Bier aus Canavese mit typischer und angenehmer Bitter- und Zitrusnote, mit einer dynamischen und sehr faszinierenden Entwicklung am Gaumen. Die Nase ist geprägt von intensiven Kräuteraromen mit Empfindungen von Grapefruit und frischem Hopfen. Es entwickelt einen bitteren und schön progressiven Schluck, ohne aufdringlich zu sein, aber extrem durstlöschend und trinkbar',
  "'Che Belle Gose' ist ein köstliches Gose-Bier mit salzigem Geschmack, das vom Birrifcio Civale in Zusammenarbeit mit der Brauerei Croce di Malto und Montegioco hergestellt wird. Es ist von den deutschen Vorbildern aus Leipzig inspiriert, die die Zugabe von weißem und rosa Salz vorsehen in den Produktionsphasen. Es ist buchstäblich ein Salzbier mit einem erfrischenden, frischen und marinen Profil, angereichert mit Aromen von Koriander, Zitrusfrüchten, Weizen und weißen Blumen",
  "Das 'Audace'-Bier aus der Via dei Birrai 32 ist ein belgisches Starkbier mit starkem Charakter und Zitrusnoten, das durch die Zugabe von kochender Orangenschale entsteht. Die Nase gibt warme Aromen von Löwenzahn und Kamille, Pfirsich in Sirup und Mandel und im Mund ist es voll und angenehm zitrisch, ohne bittere Akzente, sehr weich.",
  'Das Ippa di Baladin ist die italienische Interpretation des berühmten indischen Pale Ale nach Teo Musso-Art, ein Pionier in der Welt der Craft-Biere. Hergestellt aus auf italienischem Boden angebautem Hopfen, glänzt er im Glas mit seinem bernsteinfarbenen Mantel, der sich durch einen angenehmen weißen Schaum auszeichnet. Die Nase ist geprägt von intensiven krautigen, bitteren Zitrusnoten und leichten Empfindungen von Mango. Am Schluck ist es süffig, leicht und sauber, mit langen Hopfennoten. Das Ippa di Baladin ist die italienische Interpretation des berühmten indischen Pale Ale nach Teo Musso-Art, einem Pionier in der Welt der Craft-Biere. Hergestellt aus auf italienischem Boden angebautem Hopfen, glänzt er im Glas mit seinem bernsteinfarbenen Mantel, der sich durch einen angenehmen weißen Schaum auszeichnet. Die Nase ist geprägt von intensiven krautigen, bitteren Zitrusnoten und leichten Empfindungen von Mango. Am Schluck ist es trinkbar, leicht und sauber, mit langen Anklängen von Hopfen',
  "'Lago Nero“ ist ein vom irischen Vorbild inspiriertes Stout-Bier, das sich durch starke Rauchnoten auszeichnet. Es zeigt ein geröstetes und würziges Geruchsprofil mit Noten von geräuchertem Speck, bitterem Kakao, Kaffeebohnen und einem feinen Hopfen. Am Schluck zeigt es die klassische Note von geröstetem Malz mit einem fließenden und angenehm bitteren Körper.",
  "'Full Moon' von der Brauerei Triporteur ist ein dunkles Bier, inspiriert vom typischen Quadrupel aus Belgien, veredelt durch einen Rest in gerösteter belgischer Eiche. Er öffnet sich in der Nase zu intensiven und warmen Aromen von kandiertem Apfel, Karamell und Lakritze mit gerösteten und holzigen Untertönen. Der Schluck ist reich und großzügig, gut ausbalanciert zwischen Zuckergehalt und fruchtiger Nuance, rund und wirklich anhaltend.",
  "'Admiral' von 32 - Brauerei Via dei Birrai ist ein bernsteinfarbenes obergäriges Bier mit dunkler Farbe und rubinroten Nuancen mit einem kompakten und anhaltenden beigen Schaum. Die Nase verströmt typische Aromen von Malz und Karamell mit Rückkehr von Hefe und Röstung. Im Mund ist es voll, mit einer schönen Frische und einem angenehmen kräuterigen und bitteren Abgang, der durch den verwendeten Admiralshopfen gegeben wird.",
  "Das 'Strike'-Bier von BAV ist ein italienisches IPA, das mit Nachgärung in der Flasche und mit einem hohen IBU-Wert hergestellt wird. Es zeichnet sich durch duftende und zitronige Düfte mit Nuancen von exotischen Früchten, Kräutern und Hefen aus. Der Geschmack ist frisch, gut strukturiert und leicht fruchtig, trotz der intensiven und langen Bitterhopfenaromen leicht zu trinken.",
  'IPA by Brigà ist eine piemontesische Interpretation des beliebtesten (und missbrauchten) Braustils, den es gibt: das India Pale Ale. Es ist ein obergäriges Bier, hergestellt aus reinem Pian della Mussa-Wasser und Rohstoffen aus biologischer Landwirtschaft. Amber mit tropischer, kräuteriger und zitrusartiger Prägung, es schließt mit einer stiltypischen Bitterspitze ab.',
  "'Ghisa' der Lambrate-Brauerei ist ein dunkles Bier im Smoked-Stout-Stil, das durch seine natürliche Balance zwischen gattungstypischen Raucharomen und fließender Trinkbarkeit besticht. In der Nase öffnet es sich zu Aromen von Kaffee, Cappuccino, Maron Glacé und Kastanien mit einem dichten und weichen Schluck, lebendig und zart, reich an Rauch-, Kaffee- und Toffee-Untertönen, die perfekt an olfaktorische Aromen erinnern.",
  "'Vincent Vega' ist der Protagonist des Kultfilms Pulp Fiction, dem Retorto dieses bernsteinfarbene Bier gewidmet hat, das von den Triples der Abtei inspiriert ist. Mit einer besonders cremigen und anhaltenden Schaumkrone offenbart er sich in einem gelbbraunen, karamellfarbenen Mantel mit Zitrusdüften durch Rotorange und Pink Grapefruit. Es gibt umhüllende und volle Empfindungen, ohne süßlich zu sein, mit einem besonders appetitlichen trockenen Abgang.",
];
