/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import company from './company';
import internet from './internet';
import location from './location';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';

/**
 * The locale data for the `en_NG` locale.
 *
 * - Language: English (Nigeria)
 * - Endonym: English (Nigeria)
 */
const en_NG: LocaleDefinition = {
  company,
  internet,
  location,
  metadata,
  person,
  phone_number,
};

export default en_NG;
