/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { DatabaseDefinition } from '../../..';
import column from './column';

const database: DatabaseDefinition = {
  column,
};

export default database;
