/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'dimanĉo',
    'lundo',
    'mardo',
    'merkredo',
    'sabato',
    'vendredo',
    'ĵaŭdo',
  ],
  abbr: ['di', 'lu', 'ma', 'me', 'sa', 've', 'ĵa'],
};
