/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import address from './address';
import cell_phone from './cell_phone';
import color from './color';
import commerce from './commerce';
import date from './date';
import lorem from './lorem';
import music from './music';
import person from './person';
import phone_number from './phone_number';

const he: LocaleDefinition = {
  title: 'Hebrew',
  separator: 'ו ',
  address,
  cell_phone,
  color,
  commerce,
  date,
  lorem,
  music,
  person,
  phone_number,
};

export default he;
