/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'czwartek',
    'niedziela',
    'piątek',
    'poniedziałek',
    'sobota',
    'wtorek',
    'środa',
  ],
  abbr: ['czw.', 'niedz.', 'pon.', 'pt.', 'sob.', 'wt.', 'śr.'],
};
