/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CompanyDefinitions } from '../../..';
import legal_form from './legal_form';
import name_patterns from './name_patterns';
import suffix from './suffix';

const company: CompanyDefinitions = {
  legal_form,
  name_patterns,
  suffix,
};

export default company;
