/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CompanyDefinitions } from '../../..';
import legal_form from './legal_form';
import name_ from './name';
import suffix from './suffix';

const company = {
  legal_form,
  name: name_,
  suffix,
} as Partial<CompanyDefinitions>;

export default company;
