/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import company from './company';
import internet from './internet';
import location from './location';
import person from './person';
import phone from './phone';

const zu_ZA: LocaleDefinition = {
  title: 'Zulu (South Africa)',
  company,
  internet,
  location,
  person,
  phone,
};

export default zu_ZA;
