/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../../definitions';
import company from './company';
import internet from './internet';
import location from './location';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';

/**
 * The locale data for the `zu_ZA` locale.
 *
 * - Language: Zulu (South Africa)
 * - Endonym: isiZulu (Iningizimu Afrika)
 */
const zu_ZA: LocaleDefinition = {
  company,
  internet,
  location,
  metadata,
  person,
  phone_number,
};

export default zu_ZA;
