/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { FinanceDefinition } from '../../..';
import account_type from './account_type';
import credit_card from './credit_card';
import currency from './currency';
import transaction_description_pattern from './transaction_description_pattern';
import transaction_type from './transaction_type';

const finance: FinanceDefinition = {
  account_type,
  credit_card,
  currency,
  transaction_description_pattern,
  transaction_type,
};

export default finance;
