/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import animal from './animal';
import color from './color';
import commerce from './commerce';
import company from './company';
import date from './date';
import finance from './finance';
import internet from './internet';
import location from './location';
import lorem from './lorem';
import metadata from './metadata';
import music from './music';
import person from './person';
import phone_number from './phone_number';
import vehicle from './vehicle';
import word from './word';

/**
 * The locale data for the `fr` locale.
 *
 * - Language: French
 * - Endonym: Français
 */
const fr: LocaleDefinition = {
  animal,
  color,
  commerce,
  company,
  date,
  finance,
  internet,
  location,
  lorem,
  metadata,
  music,
  person,
  phone_number,
  vehicle,
  word,
};

export default fr;
