/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import animal from './animal';
import book from './book';
import color from './color';
import commerce from './commerce';
import company from './company';
import date from './date';
import finance from './finance';
import food from './food';
import internet from './internet';
import location from './location';
import lorem from './lorem';
import music from './music';
import person from './person';
import phone_number from './phone_number';
import recipe from './recipe';
import stays from './stays';
import vehicle from './vehicle';
import word from './word';

const fr: LocaleDefinition = {
  title: 'French',
  animal,
  book,
  color,
  commerce,
  company,
  date,
  finance,
  food,
  internet,
  location,
  lorem,
  music,
  person,
  phone_number,
  recipe,
  stays,
  vehicle,
  word,
};

export default fr;
