/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import address from './address';
import animal from './animal';
import color from './color';
import commerce from './commerce';
import company from './company';
import date from './date';
import finance from './finance';
import internet from './internet';
import lorem from './lorem';
import music from './music';
import person from './person';
import phone_number from './phone_number';
import vehicle from './vehicle';
import word from './word';

const fr: LocaleDefinition = {
  title: 'French',
  address,
  animal,
  color,
  commerce,
  company,
  date,
  finance,
  internet,
  lorem,
  music,
  person,
  phone_number,
  vehicle,
  word,
};

export default fr;
