/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import beer from './beer';
import book from './book';
import cigar from './cigar';
import cigarette from './cigarette';
import clothing from './clothing';
import company from './company';
import computer from './computer';
import condom from './condom';
import flights from './flights';
import flower from './flower';
import food from './food';
import glasses from './glasses';
import internet from './internet';
import jewels from './jewels';
import lighter from './lighter';
import liquor from './liquor';
import location from './location';
import medication from './medication';
import movie from './movie';
import parfum from './parfum';
import person from './person';
import phone from './phone';
import plant from './plant';
import recipe from './recipe';
import shoes from './shoes';
import smokingFilter from './smokingFilter';
import smokingRollingPaper from './smokingRollingPaper';
import stays from './stays';
import tattoo from './tattoo';
import tobacco from './tobacco';
import tire from './tire';
import toy from './toy';
import videogame from './videogame';
import watch from './watch';
import wheel from './wheel';
import wine from './wine';

const it: LocaleDefinition = {
  title: 'Italian',
  beer,
  book,
  cigar,
  cigarette,
  clothing,
  company,
  computer,
  condom,
  flights,
  flower,
  food,
  glasses,
  internet,
  jewels,
  lighter,
  liquor,
  location,
  medication,
  movie,
  parfum,
  person,
  phone,
  plant,
  recipe,
  shoes,
  smokingFilter,
  smokingRollingPaper,
  stays,
  tattoo,
  tobacco,
  tire,
  toy,
  videogame,
  watch,
  wheel,
  wine,
};

export default it;
