/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import book from './book';
import company from './company';
import food from './food';
import internet from './internet';
import location from './location';
import person from './person';
import phone_number from './phone_number';
import recipe from './recipe';

const it: LocaleDefinition = {
  title: 'Italian',
  book,
  company,
  food,
  internet,
  location,
  person,
  phone_number,
  recipe,
};

export default it;
