/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { KitchenDefinitions } from '../../..';
import brand from './brand';
import category from './category';
import material from './material';
import name_ from './name';
import style from './style';

const kitchen: KitchenDefinitions = {
  brand,
  category,
  material,
  name: name_,
  style,
};

export default kitchen;
