/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { MusicDefinitions } from '../../..';
import genre from './genre';
import song_name from './song_name';

const music: MusicDefinitions = {
  genre,
  song_name,
};

export default music;
