comment:
  layout: 'diff, flags, files'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 100%
