/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PersonDefinition } from '../../..';
import bio_parts from './bio_parts';
import female_first_name from './female_first_name';
import female_last_name from './female_last_name';
import female_last_name_pattern from './female_last_name_pattern';
import first_name from './first_name';
import job_title from './job_title';
import last_name from './last_name';
import male_first_name from './male_first_name';
import male_last_name from './male_last_name';
import male_last_name_pattern from './male_last_name_pattern';
import sex from './sex';

const person: PersonDefinition = {
  bio_parts,
  female_first_name,
  female_last_name,
  female_last_name_pattern,
  first_name,
  job_title,
  last_name,
  male_first_name,
  male_last_name,
  male_last_name_pattern,
  sex,
};

export default person;
