/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PersonDefinition } from '../../..';
import bio_parts from './bio_parts';
import first_name from './first_name';
import job_title from './job_title';
import last_name from './last_name';
import last_name_pattern from './last_name_pattern';
import sex from './sex';

const person: PersonDefinition = {
  bio_parts,
  first_name,
  job_title,
  last_name,
  last_name_pattern,
  sex,
};

export default person;
