/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AnimalDefinition } from '../../..';
import bird from './bird';
import fish from './fish';
import pet_name from './pet_name';
import type_ from './type';

const animal: AnimalDefinition = {
  bird,
  fish,
  pet_name,
  type: type_,
};

export default animal;
