/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { DateDefinition } from '../../..';
import time_zone from './time_zone';

const date: DateDefinition = {
  time_zone,
};

export default date;
