/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinitions } from '../../..';
import city from './city';
import city_name from './city_name';
import country_code from './country_code';
import default_country from './default_country';
import postcode from './postcode';
import state from './state';
import state_abbr from './state_abbr';
import street from './street';
import street_name from './street_name';

const location: LocationDefinitions = {
  city,
  city_name,
  country_code,
  default_country,
  postcode,
  state,
  state_abbr,
  street,
  street_name,
};

export default location;
