/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PersonDefinitions } from '../../..';
import female_first_name from './female_first_name';
import first_name from './first_name';
import last_name from './last_name';
import male_first_name from './male_first_name';
import name_ from './name';
import prefix from './prefix';
import suffix from './suffix';

const person: PersonDefinitions = {
  female_first_name,
  first_name,
  last_name,
  male_first_name,
  name: name_,
  prefix,
  suffix,
};

export default person;
