/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinitions } from '../../..';
import city from './city';
import county from './county';
import default_country from './default_country';
import postcode_by_state from './postcode_by_state';
import street from './street';

const location: LocationDefinitions = {
  city,
  county,
  default_country,
  postcode_by_state,
  street,
};

export default location;
