/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinitions } from '../../..';
import city_pattern from './city_pattern';
import county from './county';
import default_country from './default_country';
import postcode_by_state from './postcode_by_state';
import street_pattern from './street_pattern';

const location: LocationDefinitions = {
  city_pattern,
  county,
  default_country,
  postcode_by_state,
  street_pattern,
};

export default location;
