export default [
  'Das Deckblatt ist zehn Jahre alt, das Deckblatt acht, die Kaution über sechs Jahre. Die harmonischen und reichen Aromen von Davidoff Special 53 - Capa Dominicana passen perfekt zu einem dominikanischen Rum mit süßen und würzigen Noten. Die Tabaksorten überraschen mit markanten Noten von Holz, Kaffee und Kakao. Rum und Zigarre ergänzen sich, die Süße des Rums unterstreicht die Zigarre positiv und die Zigarre verleiht dem Rum Cremigkeit.',
  'Auf Wunsch vieler unserer Kunden, die ihre Davidoff No.1 oder Cohiba Lanceros vermissen, hat unser Geschäftsführer und Zigarrenexperte Mirko Pettene für unsere Royales Limited Edition 2021 ein Lancero-Format kreiert. Diese Lancero wird ausschließlich ab 8 Jahren gerollt Tabak in Royales Premium-Zigarrenqualität und kommt in einer limitierten Auflage von nur 300 wunderschönen schwarzen 10er-Kisten. Eine elegante Zigarre für Kenner und Genießer.',
  'Die Worte „Refined Power“ scheinen durch diese Zigarre wie die goldenen Röhren, die sie umhüllen. Ein wahres Kraftpaket mit außergewöhnlichem Geschmack.',
  'Die Geschichte der Marke Horacio beginnt in Costa Rica, wo sie 2008 mit viel Hingabe von drei Zigarrenliebhabern entwickelt wurde. Heute werden die Premium-Zigarren in Nicaragua produziert, das für seine äußerst delikaten Blends bekannt ist. Die klimatischen Bedingungen dort sind ideal für eine hochwertige Tabakproduktion.',
  'Hamburg, Juli 2019. Als Dankeschön für die außergewöhnliche und langjährige Zusammenarbeit mit Deutschlands besten Davidoff-Händlern lanciert Davidoff eine streng limitierte Davidoff ***** Exclusive Edition. Die edle Zigarren-Edition ist auf 500 Kisten limitiert und nur erhältlich bei David Fünf-Sterne-Botschaftern und Flagship-Stores in Deutschland.',
  'Wir kennen Rocky seit vielen Jahren und lieben seine Zigarren einfach. In Rekordzeit hat sich Rocky zu einem der größten Zigarrenmischer seiner Zeit entwickelt. Wir und unzählige Aficionados auf der ganzen Welt glauben, dass er längst ein wahrer Meister seines Fachs geworden ist. Ein weiterer Beweis dafür, wenn es noch mehr brauchte, ist sein neues Sortiment, das wir Ihnen heute vorstellen möchten. The Disciple wird in vier Formaten auf dem deutschen Markt erhältlich sein: Robusto, Toro, Bala (Figurado) und Sixty.',
  'Mit der Melanio Diadema Serie V bringt Oliva eine echte Limitada auf den Markt: Sie ist eine etwas andere Mischung im Vergleich zum Standardsortiment der Melanio Serie V und außerdem eine der ersten runden Formen innerhalb der ansonsten "boxpressed" Serie.',
  'Im September 2020 wurde der „EPC Pledge“ in zwei Vitolas veröffentlicht, einem Robusto namens „Prequel“ und dem „Sojourn“, einem Toro. In diesem Jahr entwickelte sich das Sortiment zum heißesten Must-have der Zigarrenwelt. Der Cigar Aficionado stimmte zu und zeichnete sie nur wenige Monate später mit einer unübertroffenen Bewertung von 98 Punkten als „Cigar of the Year“ aus. ',
  'Die VILLIGER LA MERIDIANA sind kräftige Puros aus Nicaragua, bieten aber dank der Verwendung eines milderen Deckblatts einen erstaunlich ausgewogenen Genuss. Die typisch schokoladigen Kaffeenoten sind erdig und tief, dabei weich abgerundet und vollmundig. Eine schöne, komplexe Aromenvielfalt, die kraftvoll, aber nie aufdringlich ist und Liebhaber dieser Puros mit einer großen Bandbreite an Formaten angenehm überrascht.',
];
