/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CommerceDefinitions } from '../../..';
import color from './color';
import department from './department';
import product_description from './product_description';
import product_name from './product_name';

const commerce = {
  color,
  department,
  product_description,
  product_name,
} as CommerceDefinitions;

export default commerce;
