/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinition } from '../../..';
import building_number from './building_number';
import city_infix from './city_infix';
import city_pattern from './city_pattern';
import city_prefix from './city_prefix';
import city_suffix from './city_suffix';
import county from './county';
import default_country from './default_country';
import postcode from './postcode';
import state from './state';
import street_pattern from './street_pattern';
import street_suffix from './street_suffix';

const location: LocationDefinition = {
  building_number,
  city_infix,
  city_pattern,
  city_prefix,
  city_suffix,
  county,
  default_country,
  postcode,
  state,
  street_pattern,
  street_suffix,
};

export default location;
