/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { InternetDefinition } from '../../..';
import domain_suffix from './domain_suffix';
import free_email from './free_email';

const internet: InternetDefinition = {
  domain_suffix,
  free_email,
};

export default internet;
