/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CompanyDefinitions } from '../../..';
import category from './category';
import name_pattern from './name_pattern';
import type_ from './type';

const company: CompanyDefinitions = {
  category,
  name_pattern,
  type: type_,
};

export default company;
