/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CompanyDefinition } from '../../..';
import category from './category';
import legal_entity_type from './legal_entity_type';
import name_pattern from './name_pattern';

const company: CompanyDefinition = {
  category,
  legal_entity_type,
  name_pattern,
};

export default company;
