/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import cell_phone from './cell_phone';
import internet from './internet';
import location from './location';
import lorem from './lorem';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';

/**
 * The locale data for the `fr_CH` locale.
 *
 * - Language: French (Switzerland)
 * - Endonym: Français (Suisse)
 */
const fr_CH: LocaleDefinition = {
  cell_phone,
  internet,
  location,
  lorem,
  metadata,
  person,
  phone_number,
};

export default fr_CH;
