/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import address from './address';
import internet from './internet';
import phone_number from './phone_number';

const fr_CH: LocaleDefinition = {
  title: 'French (Switzerland)',
  address,
  internet,
  phone_number,
};

export default fr_CH;
