/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { FishDefinitions } from '../../..';
import category from './category';
import description from './description';
import name_ from './name';

const fish: FishDefinitions = {
  category,
  description,
  name: name_,
};

export default fish;
