/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { FinanceDefinition } from '../../../..';
import bech32 from './bech32';
import legacy from './legacy';
import segwit from './segwit';
import taproot from './taproot';

const bitcoin_address_specs: FinanceDefinition['bitcoin_address_specs'] = {
  bech32,
  legacy,
  segwit,
  taproot,
};

export default bitcoin_address_specs;
