/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AddressDefinitions } from '../../..';
import building_number from './building_number';
import city from './city';
import city_prefix from './city_prefix';
import default_country from './default_country';
import postcode from './postcode';
import region from './region';
import state from './state';
import state_abbr from './state_abbr';
import street_name from './street_name';
import street_root from './street_root';
import street_suffix from './street_suffix';

const address = {
  building_number,
  city,
  city_prefix,
  default_country,
  postcode,
  region,
  state,
  state_abbr,
  street_name,
  street_root,
  street_suffix,
} as Partial<AddressDefinitions>;

export default address;
