/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { FinanceDefinition } from '../../../..';
import unionpay from './unionpay';

const credit_card: FinanceDefinition['credit_card'] = {
  unionpay,
};

export default credit_card;
