/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PhoneNumberDefinition } from '../../..';
import human from './human';
import national from './national';
import raw from './raw';

const phone_number: PhoneNumberDefinition = {
  human,
  national,
  raw,
};

export default phone_number;
