/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'april',
    'august',
    'desember',
    'februar',
    'januar',
    'juli',
    'juni',
    'mai',
    'mars',
    'november',
    'oktober',
    'september',
  ],
  abbr: [
    'apr',
    'aug',
    'des',
    'feb',
    'jan',
    'jul',
    'jun',
    'mai',
    'mar',
    'nov',
    'okt',
    'sep',
  ],
};
