/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PersonDefinitions } from '../../..';
import female_first_name from './female_first_name';
import last_name from './last_name';
import male_first_name from './male_first_name';

const person: PersonDefinitions = {
  female_first_name,
  last_name,
  male_first_name,
};

export default person;
