/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PersonDefinitions } from '../../..';
import female_first_name from './female_first_name';
import female_prefix from './female_prefix';
import last_name from './last_name';
import male_first_name from './male_first_name';
import male_prefix from './male_prefix';
import name_ from './name';
import prefix from './prefix';
import sex from './sex';

const person: PersonDefinitions = {
  female_first_name,
  female_prefix,
  last_name,
  male_first_name,
  male_prefix,
  name: name_,
  prefix,
  sex,
};

export default person;
