/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LoremDefinition } from '../../..';
import word from './words';

const lorem: LoremDefinition = {
  word,
};

export default lorem;
