/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CompanyDefinitions } from '../../..';
import suffix from './suffix';

const company: Partial<CompanyDefinitions> = {
  suffix,
};

export default company;
