/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AddressDefinitions } from '../../..';
import building_number from './building_number';
import city from './city';
import city_name from './city_name';
import city_prefix from './city_prefix';
import city_suffix from './city_suffix';
import country from './country';
import default_country from './default_country';
import direction from './direction';
import postcode from './postcode';
import street from './street';
import street_address from './street_address';
import street_prefix from './street_prefix';

const address: AddressDefinitions = {
  building_number,
  city,
  city_name,
  city_prefix,
  city_suffix,
  country,
  default_country,
  direction,
  postcode,
  street,
  street_address,
  street_prefix,
};

export default address;
