/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../../definitions';
import location from './location';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';

/**
 * The locale data for the `fi` locale.
 *
 * - Language: Finnish
 * - Endonym: suomi
 */
const fi: LocaleDefinition = {
  location,
  metadata,
  person,
  phone_number,
};

export default fi;
