/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import person from './person';

const fi: LocaleDefinition = {
  title: 'Finnish',
  location,
  person,
};

export default fi;
