/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: ['جمعه', 'دوشنبه', 'سه‌شنبه', 'شنبه', 'پنجشنبه', 'چهارشنبه', 'یکشنبه'],
  abbr: ['جمعه', 'دوشنبه', 'سه‌شنبه', 'شنبه', 'پنجشنبه', 'چهارشنبه', 'یکشنبه'],
};
