/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import metadata from './metadata';
import person from './person';

const yo: LocaleDefinition = {
  metadata,
  person,
};

export default yo;
