/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { BookDefinitions } from '../../..';
import author from './author';
import description from './description';
import publisher from './publisher';
import title from './title';

const book: BookDefinitions = {
  author,
  description,
  publisher,
  title,
};

export default book;
