/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { HackerDefinitions } from '../../..';
import abbreviation from './abbreviation';

const hacker: HackerDefinitions = {
  abbreviation,
};

export default hacker;
