/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { HackerDefinition } from '../../../definitions';
import abbreviation from './abbreviation';

const hacker: HackerDefinition = {
  abbreviation,
};

export default hacker;
