/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { ColorDefinition } from '../../../definitions';
import human from './human';

const color: ColorDefinition = {
  human,
};

export default color;
