/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinition } from '../../..';
import building_number from './building_number';
import city_name from './city_name';
import city_pattern from './city_pattern';
import country from './country';
import direction from './direction';
import postcode from './postcode';
import secondary_address from './secondary_address';
import street_address from './street_address';
import street_name from './street_name';
import street_pattern from './street_pattern';

const location: LocationDefinition = {
  building_number,
  city_name,
  city_pattern,
  country,
  direction,
  postcode,
  secondary_address,
  street_address,
  street_name,
  street_pattern,
};

export default location;
