/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { NameDefinitions } from '../../..';
import first_name from './first_name';
import last_name from './last_name';

const name = {
  first_name,
  last_name,
} as Partial<NameDefinitions>;

export default name;
