/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import animal from './animal';
import color from './color';
import company from './company';
import date from './date';
import hacker from './hacker';
import internet from './internet';
import location from './location';
import metadata from './metadata';
import music from './music';
import person from './person';
import phone_number from './phone_number';
import word from './word';

const zh_CN: LocaleDefinition = {
  animal,
  color,
  company,
  date,
  hacker,
  internet,
  location,
  metadata,
  music,
  person,
  phone_number,
  word,
};

export default zh_CN;
