/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import address from './address';
import name_ from './name';
import phone_number from './phone_number';

const zh_CN: LocaleDefinition = {
  title: 'Chinese',
  address,
  person: name_,
  phone_number,
};

export default zh_CN;
