/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import lorem from './lorem';
import metadata from './metadata';
import person from './person';

/**
 * The locale data for the `ku_ckb` locale.
 *
 * - Language: Kurdish (Sorani)
 * - Endonym: کوردی (سۆرانی)
 */
const ku_ckb: LocaleDefinition = {
  lorem,
  metadata,
  person,
};

export default ku_ckb;
