/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { DateDefinitions } from '../../..';
import month from './month';
import weekday from './weekday';

const date: DateDefinitions = {
  month,
  weekday,
};

export default date;
