/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import name_ from './name';
import suffix from './suffix';

const team = {
  name: name_,
  suffix,
};

export default team;
