/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'dinsdag',
    'donderdag',
    'maandag',
    'vrijdag',
    'woensdag',
    'zaterdag',
    'zondag',
  ],
  abbr: ['di', 'do', 'ma', 'vr', 'wo', 'za', 'zo'],
};
