/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinitions } from '../../..';
import building_number from './building_number';
import city_prefix from './city_prefix';
import city_suffix from './city_suffix';
import country from './country';
import default_country from './default_country';
import postcode from './postcode';
import state from './state';
import street_name from './street_name';

const location: LocationDefinitions = {
  building_number,
  city_prefix,
  city_suffix,
  country,
  default_country,
  postcode,
  state,
  street_name,
};

export default location;
