/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinitions } from '../../..';
import building_number from './building_number';
import city from './city';
import default_country from './default_country';
import postcode from './postcode';
import state from './state';
import state_abbr from './state_abbr';
import street from './street';
import street_suffix from './street_suffix';

const location: LocationDefinitions = {
  building_number,
  city,
  default_country,
  postcode,
  state,
  state_abbr,
  street,
  street_suffix,
};

export default location;
