/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PersonDefinitions } from '../../..';
import female_prefix from './female_prefix';
import first_name from './first_name';
import last_name from './last_name';
import male_prefix from './male_prefix';
import name_ from './name';
import nobility_title_prefix from './nobility_title_prefix';
import prefix from './prefix';

const person: PersonDefinitions = {
  female_prefix,
  first_name,
  last_name,
  male_prefix,
  name: name_,
  nobility_title_prefix,
  prefix,
};

export default person;
