/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PersonDefinition } from '../../..';
import bio_part from './bio_part';
import bio_pattern from './bio_pattern';
import bio_supporter from './bio_supporter';
import first_name from './first_name';
import gender from './gender';
import job_area from './job_area';
import job_descriptor from './job_descriptor';
import job_title_pattern from './job_title_pattern';
import job_type from './job_type';
import last_name from './last_name';
import last_name_pattern from './last_name_pattern';
import middle_name from './middle_name';
import name_ from './name';
import prefix from './prefix';
import sex from './sex';
import suffix from './suffix';
import western_zodiac_sign from './western_zodiac_sign';

const person: PersonDefinition = {
  bio_part,
  bio_pattern,
  bio_supporter,
  first_name,
  gender,
  job_area,
  job_descriptor,
  job_title_pattern,
  job_type,
  last_name,
  last_name_pattern,
  middle_name,
  name: name_,
  prefix,
  sex,
  suffix,
  western_zodiac_sign,
};

export default person;
