/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { InternetDefinitions } from '../../..';
import free_email from './free_email';

const internet: InternetDefinitions = {
  free_email,
};

export default internet;
