/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'abril',
    'agosto',
    'dezembro',
    'fevereiro',
    'janeiro',
    'julho',
    'junho',
    'maio',
    'março',
    'novembro',
    'outubro',
    'setembro',
  ],
  abbr: [
    'abr.',
    'ago.',
    'dez.',
    'fev.',
    'jan.',
    'jul.',
    'jun.',
    'mai.',
    'mar.',
    'nov.',
    'out.',
    'set.',
  ],
};
