/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'domingo',
    'quarta-feira',
    'quinta-feira',
    'segunda-feira',
    'sexta-feira',
    'sábado',
    'terça-feira',
  ],
  abbr: ['dom.', 'qua.', 'qui.', 'seg.', 'sex.', 'sáb.', 'ter.'],
};
