/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { MeatDefinitions } from '../../..';
import category from './category';
import cut from './cut';
import description from './description';
import name_ from './name';

const meat: MeatDefinitions = {
  category,
  cut,
  description,
  name: name_,
};

export default meat;
