/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'apríl',
    'august',
    'december',
    'február',
    'január',
    'júl',
    'jún',
    'marec',
    'máj',
    'november',
    'október',
    'september',
  ],
  abbr: [
    'apr',
    'aug',
    'dec',
    'feb',
    'jan',
    'júl',
    'jún',
    'mar',
    'máj',
    'nov',
    'okt',
    'sep',
  ],
};
