/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'nedeľa',
    'piatok',
    'pondelok',
    'sobota',
    'streda',
    'utorok',
    'štvrtok',
  ],
  abbr: ['ne', 'pi', 'po', 'so', 'st', 'ut', 'št'],
};
