/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AnimalDefinition } from '../../..';
import bird from './bird';
import cat from './cat';
import dog from './dog';

const animal: AnimalDefinition = {
  bird,
  cat,
  dog,
};

export default animal;
