/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AnimalDefinition } from '../../..';
import dog from './dog';

const animal: AnimalDefinition = {
  dog,
};

export default animal;
