export default [
  'Ensemble de 250 pièces pour construire vos jolis cœurs : associez les couleurs et les chiffres pour créer votre propre composition en mosaïque ! Suivez le motif et faites correspondre les couleurs correctement pour créer de jolis cœurs avec le puzzle Plus-Plus par numéro !',
  "Construisez une aire de restauration pour les personnages d'Eevee et de Lucario. Cet ensemble se combine avec d'autres ensembles Adventure Builder pour créer un monde Pokémon encore plus grand et plein de détails authentiques. Découvrez Pikachu Beach Fun, Bulbasaur Forest ou d'autres ensembles encore plus grands, chacun vendu séparément. Les jouets de construction MEGA Pokémon sont conçus pour les enfants de plus de 7 ans",
  "Construisez un stand de rafraîchissements pour les personnages d'Eevee et de Lucario. Cet ensemble se combine avec d'autres ensembles Adventure Builder pour créer un monde Pokémon encore plus grand et plein de détails authentiques. Découvrez Pikachu Beach Fun, Bulbasaur Forest ou d'autres ensembles encore plus grands, chacun vendu séparément. Les jouets de construction MEGA Pokémon sont conçus pour les enfants de plus de 7",
  "Une moto : cinq créations. Un kit de modèle amusant et passionnant à réaliser avec cet ensemble Meccano. Les enfants peuvent s'amuser à monter et remonter des motos et des voitures de sport. Lors de l'utilisation de ce S.T.E.A.M. kit de construction, ils apprendront les principes de la science, de la technologie, de l'ingénierie, de l'art et des mathématiques.",
  "Ce super modèle de voiture de course LEGO Technic Formula E® Porsche 99X électrique (42137) avec système de recul est le cadeau parfait pour tous les fans de Formule E® et de Porsche âgés de 9 ans et plus. Avec ce modèle de la célèbre Porsche, les enfants peuvent s'immerger dans une expérience de construction immersive, recréant tous les détails de la vraie voiture et revivant toutes les émotions de la vraie course, grâce aux 2 moteurs à rétrofriction et à l'application de réalité LEGO Technic . augmenté (AR).",
  "Offrez aux jeunes fans de 9 ans et plus le cadeau parfait : la figurine articulée Iron Man. D'une hauteur de 24 cm, la figurine LEGO Marvel Iron Man (76206) est prête à offrir aux enfants des heures et des heures d'aventures passionnantes sur le thème de Marvel Super Heroes. Inspirée du film Avengers : L'Ère d'Ultron, cette reproduction réaliste est entièrement articulée et prête à se lancer dans des missions audacieuses contre les méchants.",
  "Emmenez les enfants qui aiment les animaux marins dans un voyage fantastique au fond de l'océan avec l'ensemble LEGO DUPLO Les animaux de l'océan (10972). Un ensemble de jeu qui offre des possibilités infinies pour le développement des enfants d'âge préscolaire, grâce à un tapis de jeu en trois dimensions qui représente un fond marin et 4 animaux en peluche.",
  "Les jeunes sorcières, sorciers et moldus âgés de 8 ans et plus peuvent vivre des aventures fantastiques avec cet ensemble à plusieurs niveaux LEGO Harry Potter Poudlard : Le bureau de Dumbledore (76402), comprenant différentes zones et des détails authentiques de la célèbre saga cinématographique. Les jeunes fans des jeux Harry Potter trouverez de la magie et de l'aventure dans chaque pièce de ce château de jouets.",
  "Découvrez des jouets créatifs amusants pour les enfants dans l'ensemble de construction LEGO Creator Les créatures de la forêt Fantasy 3en1 (31125). Cet ensemble d'animaux jouets pour les enfants de 7 ans et plus vous permet de créer de nombreuses histoires fantastiques dans les bois. L'un des 3 modèles inclus est un hibou jouet sage avec une tête, une queue, des ailes et des plumes mobiles, lisant un livre d'histoires à un hérisson.",
  "Écurie pouvant accueillir jusqu'à 3 poneys et grand espace extérieur clôturé pour les premières balades. L'étage supérieur abrite des provisions et du matériel pour le soin des chevaux.",
  "Le Batman original à l'échelle de 30 centimètres. Avec 11 points d'articulation, il est possible de le déplacer et de le positionner à volonté dans des poses héroïques. Avec des couleurs et des décorations réalistes, il possède également une cape en tissu. Les enfants peuvent revivre les aventures de Gotham City avec le héros le plus emblématique de tous les temps.",
  'Les dinosaures sont revenus sur terre ! Vivez de grandes aventures avec cet ensemble de jeu - Lumières et sons - Pièces mobiles - Disponible en 2 modèles',
];
