/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import address from './address';
import company from './company';
import internet from './internet';
import lorem from './lorem';
import name_ from './name';
import phone_number from './phone_number';

const sk: LocaleDefinition = {
  title: 'Slovakian',
  address,
  company,
  internet,
  lorem,
  person: name_,
  phone_number,
};

export default sk;
