/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import animal from './animal';
import commerce from './commerce';
import company from './company';
import date from './date';
import finance from './finance';
import internet from './internet';
import location from './location';
import person from './person';
import phone_number from './phone_number';
import word from './word';

const hu: LocaleDefinition = {
  title: 'Hungarian',
  animal,
  commerce,
  company,
  date,
  finance,
  internet,
  location,
  person,
  phone_number,
  word,
};

export default hu;
