/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import animal from './animal';
import commerce from './commerce';
import date from './date';
import finance from './finance';
import internet from './internet';
import name_ from './name';
import phone_number from './phone_number';
import word from './word';

const hu: LocaleDefinition = {
  title: 'Hungarian',
  animal,
  commerce,
  date,
  finance,
  internet,
  name: name_,
  phone_number,
  word,
};

export default hu;
