/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'april',
    'augusti',
    'december',
    'februari',
    'januari',
    'juli',
    'juni',
    'maj',
    'mars',
    'november',
    'oktober',
    'september',
  ],
  abbr: [
    'apr.',
    'aug.',
    'dec.',
    'feb.',
    'jan.',
    'juli',
    'juni',
    'maj',
    'mars',
    'nov.',
    'okt.',
    'sep.',
  ],
};
