/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import cast from './cast';
import description from './description';
import director from './director';
import duration from './duration';
import genre from './genre';
import title from './title';
import writers from './writers';

const movie = {
  cast,
  description,
  director,
  duration,
  genre,
  title,
  writers,
};

export default movie;
