/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import cell_phone from './cell_phone';
import company from './company';
import internet from './internet';
import location from './location';
import person from './person';
import phone from './phone';
import word from './word';

const de_AT: LocaleDefinition = {
  title: 'German (Austria)',
  cell_phone,
  company,
  internet,
  location,
  person,
  phone,
  word,
};

export default de_AT;
