/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import credit_card_types from './credit_card_types';

const business = {
  credit_card_types,
};

export default business;
