/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { InternetDefinition } from '../../..';
import emoji from './emoji';
import http_status_code from './http_status_code';

const internet: InternetDefinition = {
  emoji,
  http_status_code,
};

export default internet;
