/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CompanyDefinition } from '../../..';
import suffix from './suffix';

const company: CompanyDefinition = {
  suffix,
};

export default company;
