/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CompanyDefinition } from '../../..';
import legal_entity_type from './legal_entity_type';

const company: CompanyDefinition = {
  legal_entity_type,
};

export default company;
