/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CompanyDefinition } from '../../..';
import adjective from './adjective';
import descriptor from './descriptor';
import name_pattern from './name_pattern';
import noun from './noun';
import suffix from './suffix';

const company: CompanyDefinition = {
  adjective,
  descriptor,
  name_pattern,
  noun,
  suffix,
};

export default company;
