/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CompanyDefinitions } from '../../..';
import adjective from './adjective';
import descriptor from './descriptor';
import name_ from './name';
import noun from './noun';
import suffix from './suffix';

const company: CompanyDefinitions = {
  adjective,
  descriptor,
  name: name_,
  noun,
  suffix,
};

export default company;
