/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { InternetDefinition } from '../../..';
import avatar_uri from './avatar_uri';
import domain_suffix from './domain_suffix';
import example_email from './example_email';
import free_email from './free_email';

const internet: InternetDefinition = {
  avatar_uri,
  domain_suffix,
  example_email,
  free_email,
};

export default internet;
