/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { VehicleDefinition } from '../../..';
import bicycle_type from './bicycle_type';
import fuel from './fuel';
import manufacturer from './manufacturer';
import model from './model';
import type_ from './type';

const vehicle: VehicleDefinition = {
  bicycle_type,
  fuel,
  manufacturer,
  model,
  type: type_,
};

export default vehicle;
