/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PersonDefinitions } from '../../..';
import first_name from './first_name';
import last_name from './last_name';

const person: PersonDefinitions = {
  first_name,
  last_name,
};

export default person;
