/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import af_ZA from './af_ZA';
import ar from './ar';
import az from './az';
import base from './base';
import bn_BD from './bn_BD';
import cs_CZ from './cs_CZ';
import cy from './cy';
import da from './da';
import de from './de';
import de_AT from './de_AT';
import de_CH from './de_CH';
import dv from './dv';
import el from './el';
import en from './en';
import en_AU from './en_AU';
import en_AU_ocker from './en_AU_ocker';
import en_BORK from './en_BORK';
import en_CA from './en_CA';
import en_GB from './en_GB';
import en_GH from './en_GH';
import en_HK from './en_HK';
import en_IE from './en_IE';
import en_IN from './en_IN';
import en_NG from './en_NG';
import en_US from './en_US';
import en_ZA from './en_ZA';
import eo from './eo';
import es from './es';
import es_MX from './es_MX';
import fa from './fa';
import fi from './fi';
import fr from './fr';
import fr_BE from './fr_BE';
import fr_CA from './fr_CA';
import fr_CH from './fr_CH';
import fr_LU from './fr_LU';
import fr_SN from './fr_SN';
import he from './he';
import hr from './hr';
import hu from './hu';
import hy from './hy';
import id_ID from './id_ID';
import it from './it';
import ja from './ja';
import ka_GE from './ka_GE';
import ko from './ko';
import lv from './lv';
import mk from './mk';
import nb_NO from './nb_NO';
import ne from './ne';
import nl from './nl';
import nl_BE from './nl_BE';
import pl from './pl';
import pt_BR from './pt_BR';
import pt_PT from './pt_PT';
import ro from './ro';
import ro_MD from './ro_MD';
import ru from './ru';
import sk from './sk';
import sr_RS_latin from './sr_RS_latin';
import sv from './sv';
import ta_IN from './ta_IN';
import th from './th';
import tr from './tr';
import uk from './uk';
import ur from './ur';
import uz_UZ_latin from './uz_UZ_latin';
import vi from './vi';
import yo_NG from './yo_NG';
import zh_CN from './zh_CN';
import zh_TW from './zh_TW';
import zu_ZA from './zu_ZA';

export { default as af_ZA } from './af_ZA';
export { default as ar } from './ar';
export { default as az } from './az';
export { default as base } from './base';
export { default as bn_BD } from './bn_BD';
export { default as cs_CZ } from './cs_CZ';
export { default as cy } from './cy';
export { default as da } from './da';
export { default as de } from './de';
export { default as de_AT } from './de_AT';
export { default as de_CH } from './de_CH';
export { default as dv } from './dv';
export { default as el } from './el';
export { default as en } from './en';
export { default as en_AU } from './en_AU';
export { default as en_AU_ocker } from './en_AU_ocker';
export { default as en_BORK } from './en_BORK';
export { default as en_CA } from './en_CA';
export { default as en_GB } from './en_GB';
export { default as en_GH } from './en_GH';
export { default as en_HK } from './en_HK';
export { default as en_IE } from './en_IE';
export { default as en_IN } from './en_IN';
export { default as en_NG } from './en_NG';
export { default as en_US } from './en_US';
export { default as en_ZA } from './en_ZA';
export { default as eo } from './eo';
export { default as es } from './es';
export { default as es_MX } from './es_MX';
export { default as fa } from './fa';
export { default as fi } from './fi';
export { default as fr } from './fr';
export { default as fr_BE } from './fr_BE';
export { default as fr_CA } from './fr_CA';
export { default as fr_CH } from './fr_CH';
export { default as fr_LU } from './fr_LU';
export { default as fr_SN } from './fr_SN';
export { default as he } from './he';
export { default as hr } from './hr';
export { default as hu } from './hu';
export { default as hy } from './hy';
export { default as id_ID } from './id_ID';
export { default as it } from './it';
export { default as ja } from './ja';
export { default as ka_GE } from './ka_GE';
export { default as ko } from './ko';
export { default as lv } from './lv';
export { default as mk } from './mk';
export { default as nb_NO } from './nb_NO';
export { default as ne } from './ne';
export { default as nl } from './nl';
export { default as nl_BE } from './nl_BE';
export { default as pl } from './pl';
export { default as pt_BR } from './pt_BR';
export { default as pt_PT } from './pt_PT';
export { default as ro } from './ro';
export { default as ro_MD } from './ro_MD';
export { default as ru } from './ru';
export { default as sk } from './sk';
export { default as sr_RS_latin } from './sr_RS_latin';
export { default as sv } from './sv';
export { default as ta_IN } from './ta_IN';
export { default as th } from './th';
export { default as tr } from './tr';
export { default as uk } from './uk';
export { default as ur } from './ur';
export { default as uz_UZ_latin } from './uz_UZ_latin';
export { default as vi } from './vi';
export { default as yo_NG } from './yo_NG';
export { default as zh_CN } from './zh_CN';
export { default as zh_TW } from './zh_TW';
export { default as zu_ZA } from './zu_ZA';

export const allLocales = {
  af_ZA,
  ar,
  az,
  base,
  bn_BD,
  cs_CZ,
  cy,
  da,
  de,
  de_AT,
  de_CH,
  dv,
  el,
  en,
  en_AU,
  en_AU_ocker,
  en_BORK,
  en_CA,
  en_GB,
  en_GH,
  en_HK,
  en_IE,
  en_IN,
  en_NG,
  en_US,
  en_ZA,
  eo,
  es,
  es_MX,
  fa,
  fi,
  fr,
  fr_BE,
  fr_CA,
  fr_CH,
  fr_LU,
  fr_SN,
  he,
  hr,
  hu,
  hy,
  id_ID,
  it,
  ja,
  ka_GE,
  ko,
  lv,
  mk,
  nb_NO,
  ne,
  nl,
  nl_BE,
  pl,
  pt_BR,
  pt_PT,
  ro,
  ro_MD,
  ru,
  sk,
  sr_RS_latin,
  sv,
  ta_IN,
  th,
  tr,
  uk,
  ur,
  uz_UZ_latin,
  vi,
  yo_NG,
  zh_CN,
  zh_TW,
  zu_ZA,
} as const;
