/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinition } from '../../..';
import building_number from './building_number';
import city_pattern from './city_pattern';
import city_prefix from './city_prefix';
import city_suffix from './city_suffix';
import common_street_suffix from './common_street_suffix';
import country from './country';
import county from './county';
import postcode from './postcode';
import secondary_address from './secondary_address';
import state from './state';
import street_address from './street_address';
import street_name from './street_name';
import street_pattern from './street_pattern';
import street_prefix from './street_prefix';
import street_suffix from './street_suffix';

const location: LocationDefinition = {
  building_number,
  city_pattern,
  city_prefix,
  city_suffix,
  common_street_suffix,
  country,
  county,
  postcode,
  secondary_address,
  state,
  street_address,
  street_name,
  street_pattern,
  street_prefix,
  street_suffix,
};

export default location;
