/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'आइतबार',
    'बिहिबार',
    'बुधबार',
    'मङ्गलबार',
    'शनिबार',
    'शुक्रबार',
    'सोमबार',
  ],
  abbr: ['आइत', 'बिहि', 'बुध', 'मङ्गल', 'शनि', 'शुक्र', 'सोम'],
};
