/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AddressDefinitions } from '../../..';
import building_number from './building_number';
import city from './city';
import city_name from './city_name';
import country from './country';
import county from './county';
import default_country from './default_country';
import direction from './direction';
import direction_abbr from './direction_abbr';
import postcode from './postcode';
import secondary_address from './secondary_address';
import state from './state';
import state_abbr from './state_abbr';
import street from './street';
import street_address from './street_address';
import street_name from './street_name';
import street_prefix from './street_prefix';
import time_zone from './time_zone';

const address: AddressDefinitions = {
  building_number,
  city,
  city_name,
  country,
  county,
  default_country,
  direction,
  direction_abbr,
  postcode,
  secondary_address,
  state,
  state_abbr,
  street,
  street_address,
  street_name,
  street_prefix,
  time_zone,
};

export default address;
