/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'abril',
    'agosto',
    'diciembre',
    'enero',
    'febrero',
    'julio',
    'junio',
    'marzo',
    'mayo',
    'noviembre',
    'octubre',
    'septiembre',
  ],
  abbr: [
    'abr',
    'ago',
    'dic',
    'ene',
    'feb',
    'jul',
    'jun',
    'mar',
    'may',
    'nov',
    'oct',
    'sept',
  ],
  abbr_context: [
    'abr.',
    'ag.',
    'dic.',
    'en.',
    'febr.',
    'jul.',
    'jun.',
    'my.',
    'mzo.',
    'nov.',
    'oct.',
    'sept.',
  ],
};
