/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'domingo',
    'jueves',
    'lunes',
    'martes',
    'miércoles',
    'sábado',
    'viernes',
  ],
  abbr: ['dom', 'jue', 'lun', 'mar', 'mié', 'sáb', 'vie'],
  abbr_context: ['dom.', 'juev.', 'lun.', 'mart.', 'miérc.', 'sáb.', 'vier.'],
};
