/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'Aprel',
    'Avgust',
    'Dekabr',
    'Fevral',
    'Iyul',
    'Iyun',
    'Mart',
    'May',
    'Noyabr',
    'Oktabr',
    'Sentabr',
    'Yanvar',
  ],
  abbr: [
    'Apr',
    'Avg',
    'Dek',
    'Fev',
    'Iyl',
    'Iyn',
    'Mar',
    'May',
    'Noy',
    'Okt',
    'Sen',
    'Yan',
  ],
};
