/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { SportsDefinitions } from '../../..';
import team_patterns from './team_patterns';

const sports: SportsDefinitions = {
  team_patterns,
};

export default sports;
