/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { MedicationDefinitions } from '../../..';
import category from './category';
import description from './description';
import format from './format';
import howToUse from './howToUse';
import manufacturer from './manufacturer';
import name_ from './name';

const medication: MedicationDefinitions = {
  category,
  description,
  format,
  howToUse,
  manufacturer,
  name: name_,
};

export default medication;
