/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import company from './company';
import internet from './internet';
import location from './location';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';

/**
 * The locale data for the `en_IN` locale.
 *
 * - Language: English (India)
 * - Endonym: English (India)
 */
const en_IN: LocaleDefinition = {
  company,
  internet,
  location,
  metadata,
  person,
  phone_number,
};

export default en_IN;
