/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import address from './address';
import company from './company';
import internet from './internet';
import person from './person';
import phone_number from './phone_number';

const en_IN: LocaleDefinition = {
  title: 'English (India)',
  address,
  company,
  internet,
  person,
  phone_number,
};

export default en_IN;
