/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { VehicleDefinition } from '../../..';
import fuel from './fuel';

const vehicle: VehicleDefinition = {
  fuel,
};

export default vehicle;
