export default [
  "Sciogliete il lievito di birra in poca acqua tiepida, circa 10 ml. Unite il sale alla farina e mescolate. Versate l'acqua in un recipiente capiente, aggiungete poco per volta il lievito sciolto, l'olio e la farina, mentre con l'altra mano si comincia ad impastare. Etc...",
  "Per prima cosa mettete in una ciotola la farina, il sale e il lievito avendo cura di mettere il sale e il lievito ai lati opposti. Aggiungere l'acqua e l'olio d'oliva e mescolare fino a formare un impasto ruvido. Formare una palla con l'impasto, quindi lavorarlo su una superficie leggermente infarinata per circa 10 minuti fino a ottenere un impasto liscio ed elastico. Eccetera...",
  "Aggiungere il lievito all'acqua tiepida con ½ cucchiaino di zucchero per 5 minuti. Unire la farina e il sale in una ciotola capiente. Fare un buco al centro e aggiungere il composto di acqua/lievito mescolando l'impasto con un cucchiaio fino ad ottenere avete ottenuto un impasto. Se è troppo appiccicoso potete aggiungere poco alla volta un po' più di farina. Etc...",
  "Per l'impasto, unire l'olio, il lievito e 2 cucchiai di acqua tiepida in una ciotola per sciogliere il lievito. Unisci la farina e 1 cucchiaio di sale in una ciotola e fai un buco al centro. Aggiungere 680 ml di acqua e il composto di lievito per bene e mescolare con le mani per formare un impasto appiccicoso (3-4 minuti). Coprire con pellicola per idratare (15 minuti), quindi impastare su una spianatoia leggermente infarinata fino ad ottenere un composto liscio (2 minuti). Rimettete nella ciotola, coprite con pellicola e mettete in frigo a fermentare (24 ore). Eccetera..",
  "Affettate le cipolle a rondelle sottili. Tritare finemente la carota, il sedano e lo spicchio d'aglio. In una casseruola capiente (8 qt.), scaldare lo strutto, le cipolle e la pancetta tritata finemente. Cuocere per 5 minuti, mescolando, fino a quando non saranno morbide; quindi aggiungere la carota, l'aglio e il sedano e cuocere a fuoco lento per 3-4 minuti. Eccetera...",
  "Una volta puliti i calamari (puoi chiedere al pescivendolo di farlo per te), tagliarli a rondelle e saltarli con aglio e un po' d'olio. Aggiungere il vino bianco e il concentrato di pomodoro e, una volta evaporato l'alcool, unire i pomodori e cuocere per 10 minuti a fuoco dolce.",
  "Scaldare 3 cucchiai di olio extravergine di oliva in una padella capiente a fuoco medio. Aggiungere la cipolla, il sedano e l'aglio se utilizzati. Cuocere, per circa 2 minuti, aggiungendo 1-2 cucchiai di acqua se necessario.",
  "Scaldare una pentola capiente con olio d'oliva, aggiungere i funghi e la cipolla e cuocere, mescolando spesso per 7-8 minuti, aggiungendo se necessario un filo di brodo. Trasferire le verdure in un contenitore e riportare la pentola a fuoco medio-basso. Aggiungere il riso e farlo tostare per 1 minuto, mescolando spesso. Aggiungere il vino e farlo evaporare.",
  "Semplicemente mescolare insieme acqua, succo di limone e zucchero in una ciotola capiente, finché lo zucchero non si sarà sciolto. Trasferite il composto in un recipiente di metallo capiente (andrebbe benissimo uno stampo da plumcake), coprite e mettete in freezer per mezz'ora. Mescolare energicamente con un cucchiaio di legno il composto per rompere eventuali cristalli di ghiaccio, quindi trasferirlo di nuovo in congelatore. Ripeti ogni 30 minuti mescolando 2-3 volte, o finché la tua granita non avrà raggiunto una consistenza vellutata e ghiacciata.",
  'Rompi i biscotti a pezzi con le mani, oppure mettili in un sacchetto per congelatore e rompili delicatamente con un mattarello. Non schiacciarli. Sbattere il burro ammorbidito con lo zucchero fino a renderlo pallido e spumoso, circa 3 minuti.',
  "Portare a bollore una pentola capiente di acqua leggermente salata, quindi cuocere la pasta al dente, circa 8 minuti per le linguine. Scolare la pasta e trasferirla nella padella con gli altri ingredienti. Scaldare una padella a fuoco medio, aggiungere l'olio d'oliva, poi i pezzi di salmone, l'aglio e gli spinaci e saltare per 2 minuti.",
];
