/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinitions } from '../../..';
import building_number from './building_number';
import city from './city';
import city_name from './city_name';
import country from './country';
import default_country from './default_country';
import postcode from './postcode';
import street from './street';
import street_address from './street_address';
import street_name from './street_name';

const location: LocationDefinitions = {
  building_number,
  city,
  city_name,
  country,
  default_country,
  postcode,
  street,
  street_address,
  street_name,
};

export default location;
