/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../../definitions';
import color from './color';
import commerce from './commerce';
import company from './company';
import date from './date';
import food from './food';
import internet from './internet';
import location from './location';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';

/**
 * The locale data for the `az` locale.
 *
 * - Language: Azerbaijani
 * - Endonym: azərbaycan dili
 */
const az: LocaleDefinition = {
  color,
  commerce,
  company,
  date,
  food,
  internet,
  location,
  metadata,
  person,
  phone_number,
};

export default az;
