/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import address from './address';
import color from './color';
import commerce from './commerce';
import company from './company';
import date from './date';
import internet from './internet';
import name_ from './name';
import phone_number from './phone_number';

const az: LocaleDefinition = {
  title: 'Azerbaijani',
  separator: ' və ',
  address,
  color,
  commerce,
  company,
  date,
  internet,
  name: name_,
  phone_number,
};

export default az;
