/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PhoneNumberDefinition } from '../../..';
import format from './format';

const phone_number: PhoneNumberDefinition = {
  format,
};

export default phone_number;
