/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { FinanceDefinitions } from '../../..';
import currency from './currency';

const finance: FinanceDefinitions = {
  currency,
};

export default finance;
