trigger:
  branches:
    include:
      - main
pr:
  autoCancel: true
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

jobs:
  - job: Lint
    displayName: Lint

    strategy:
      matrix:
        node_12_x:
          node_version: 12.x
    steps:
      - template: ./templates/setup-node.yml
      - bash: |
          npm run lint

  - job: Test
    displayName: Test
    strategy:
      matrix:
        node_12_x:
          node_version: 12.x
    steps:
      - template: ./templates/setup-node.yml
      - bash: |
          npm run test
