/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { MusicDefinition } from '../../..';
import genre from './genre';

const music: MusicDefinition = {
  genre,
};

export default music;
