/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { ScienceDefinitions } from '../../..';
import chemicalElement from './chemicalElement';
import longUnit from './longUnit';
import shortUnit from './shortUnit';

const science: ScienceDefinitions = {
  chemicalElement,
  longUnit,
  shortUnit,
};

export default science;
