/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { ScienceDefinitions } from '../../..';
import chemicalElement from './chemicalElement';
import unit from './unit';

const science: ScienceDefinitions = {
  chemicalElement,
  unit,
};

export default science;
