/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import cell_phone from './cell_phone';
import company from './company';
import internet from './internet';
import location from './location';
import person from './person';
import phone from './phone';

const ge: LocaleDefinition = {
  title: 'Georgian',
  separator: ' და ',
  cell_phone,
  company,
  internet,
  location,
  person,
  phone,
};

export default ge;
