/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PersonDefinition } from '../../..';
import first_name from './first_name';
import job_area from './job_area';
import job_descriptor from './job_descriptor';
import job_type from './job_type';
import last_name from './last_name';
import last_name_pattern from './last_name_pattern';
import name_ from './name';
import prefix from './prefix';

const person: PersonDefinition = {
  first_name,
  job_area,
  job_descriptor,
  job_type,
  last_name,
  last_name_pattern,
  name: name_,
  prefix,
};

export default person;
