/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import address from './address';
import animal from './animal';
import app from './app';
import business from './business';
import cell_phone from './cell_phone';
import color from './color';
import commerce from './commerce';
import date from './date';
import finance from './finance';
import lorem from './lorem';
import music from './music';
import name_ from './name';
import team from './team';
import vehicle from './vehicle';

const ur: LocaleDefinition = {
  title: 'Urdu',
  separator: ' اور ',
  address,
  animal,
  app,
  business,
  cell_phone,
  color,
  commerce,
  date,
  finance,
  lorem,
  music,
  person: name_,
  team,
  vehicle,
};

export default ur;
