/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import animal from './animal';
import app from './app';
import business from './business';
import cell_phone from './cell_phone';
import color from './color';
import commerce from './commerce';
import date from './date';
import finance from './finance';
import location from './location';
import lorem from './lorem';
import music from './music';
import person from './person';
import team from './team';
import vehicle from './vehicle';

const ur: LocaleDefinition = {
  title: 'Urdu',
  animal,
  app,
  business,
  cell_phone,
  color,
  commerce,
  date,
  finance,
  location,
  lorem,
  music,
  person,
  team,
  vehicle,
};

export default ur;
