/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PrinterDefinitions } from '../../..';
import brand from './brand';
import colorOutput from './colorOutput';
import connectivity from './connectivity';
import features from './features';
import functions from './functions';
import name_ from './name';
import paperSize from './paperSize';
import type_ from './type';
import use from './use';

const printer: PrinterDefinitions = {
  brand,
  colorOutput,
  connectivity,
  features,
  functions,
  name: name_,
  paperSize,
  type: type_,
  use,
};

export default printer;
