/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { WordDefinition } from '../../..';
import adjective from './adjective';
import conjunction from './conjunction';
import interjection from './interjection';

const word: WordDefinition = {
  adjective,
  conjunction,
  interjection,
};

export default word;
