/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { WordDefinitions } from '../../..';
import adjective from './adjective';
import conjunction from './conjunction';
import interjection from './interjection';

const word: WordDefinitions = {
  adjective,
  conjunction,
  interjection,
};

export default word;
