/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PhoneNumberDefinition } from '../../../..';
import human from './human';
import international from './international';
import national from './national';

const format: PhoneNumberDefinition['format'] = {
  human,
  international,
  national,
};

export default format;
