/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { VideogameDefinitions } from '../../..';
import ageRating from './ageRating';
import brand from './brand';
import condition from './condition';
import description from './description';
import developer from './developer';
import genre from './genre';
import name_ from './name';
import platform from './platform';
import publisher from './publisher';

const videogame: VideogameDefinitions = {
  ageRating,
  brand,
  condition,
  description,
  developer,
  genre,
  name: name_,
  platform,
  publisher,
};

export default videogame;
