/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AnimalDefinitions } from '../../..';
import bear from './bear';
import cow from './cow';
import crocodilia from './crocodilia';
import insect from './insect';
import lion from './lion';
import type_ from './type';

const animal: AnimalDefinitions = {
  bear,
  cow,
  crocodilia,
  insect,
  lion,
  type: type_,
};

export default animal;
