/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import cell_phone from './cell_phone';
import color from './color';
import commerce from './commerce';
import date from './date';
import location from './location';
import person from './person';
import phone from './phone';
import team from './team';
import vehicle from './vehicle';

const ar: LocaleDefinition = {
  title: 'Arabic',
  separator: ' & ',
  cell_phone,
  color,
  commerce,
  date,
  location,
  person,
  phone,
  team,
  vehicle,
};

export default ar;
