/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import cell_phone from './cell_phone';
import color from './color';
import commerce from './commerce';
import date from './date';
import location from './location';
import person from './person';
import phone_number from './phone_number';
import sports from './sports';
import vehicle from './vehicle';

const ar: LocaleDefinition = {
  title: 'Arabic',
  cell_phone,
  color,
  commerce,
  date,
  location,
  person,
  phone_number,
  sports,
  vehicle,
};

export default ar;
