export default [
  'Die Pizza Margherita ist die typische Pizza für zu Hause mit ihrer Sauce aus Tomaten, Mozzarella, Öl und Basilikum.',
  'Eine ECHTE Vier-Käse-Pizza besteht aus vier unglaublichen und köstlichen Käsesorten auf einem leichten und knusprigen Pizzaboden, der mit Tomatensauce bestrichen ist. Es ist einfach unglaublich!',
  'Quattro Stagioni Pizza oder Vier-Jahreszeiten-Pizza ist eine der besten italienischen Pizzen, die es gibt, mit Artischocken, Pilzen, Oliven und Schinken. Diese authentische italienische Pizza ist unglaublich lecker und macht Spaß.',
  "Pizza Capricciosa ist eine klassische italienische Pizza. Die 'Capricciosa', wie sie alle nennen, steht auf der Speisekarte jeder Pizzeria, normalerweise unter der Liste der traditionellen Pizzen. Ihre Hauptzutaten sind Tomatenpüree, Mozzarella, Cremini-Pilze, Artischockenherzen, schwarze Oliven , und Prosciutto Cotto",
  'Diavola ist eine Variation italienischer Pizza, die traditionell mit Tomatensauce, Mozzarella-Käse, würziger Salami und scharfen Chilischoten belegt wird. Schwarze Oliven sind optional und können für zusätzlichen Geschmack hinzugefügt werden.',
  'Legendäres neapolitanisches Ragù ist ein Sonntagsritual. Leckere Fleischstücke und Tomaten köcheln langsam stundenlang. Das Ergebnis ist eine dichte und intensive Sauce, die sich liebevoll an gewirbelte Fusilli-Nudeln schmiegt.',
  'Diese klassische italienische Calamarata-Pasta ist mit Meeresfrüchtegeschmack gefüllt und aus 7 einfachen Zutaten hergestellt! In 20 Minuten fertig und SO lecker, wenn Sie Pasta und Meeresfrüchte lieben, wird dies sicher zu einem Favoriten.',
  'Dieser traditionelle sizilianische Fischeintopf oder Puttanesca mit Kabeljau aus Tomaten, Oliven und Kapern ist ein klassisches italienisches Gericht, das sich leicht in 20 Minuten zubereiten lässt.',
  'Cremig, reichhaltig und unglaublich einfach zuzubereiten, dieses italienische Wildpilz-Risotto ist so ein köstlich beruhigendes Herbstessen! Wildpilz-Risotto ist zu dieser Jahreszeit ein festes Familien-Lieblingsessen. Es ist cremig, reichhaltig und in weniger als leicht zuzubereiten 30 Minuten und genau das Richtige, um sich an kühleren Tagen aufzuwärmen.',
  'Probieren Sie das authentische sizilianische Granita-Rezept zu Hause, eines der besten italienischen Tiefkühldesserts - Nur 3 Zutaten erforderlich!',
  'Traditionelle italienische Schokoladensalami – Dieses lustige und einfache Weihnachtsdessert ohne Backen wird mit nur 5 einfachen Zutaten zubereitet. Schokoladensalami weckt so viele Erinnerungen an meine Weihnachtsferien in Sizilien Ich konnte es kaum erwarten.',
  'Diese einfache und cremige Lachspasta mit Spinat ist voller Geschmack und eine fantastische Option für eine schnelle, köstliche Mahlzeit in nur 10 Minuten! In einer frischen Sahnesauce mit Knoblauch und Zitrone übergossen, ist Lachspasta ein so einfaches, aber raffiniertes Gericht, dass jeden am Esstisch begeistern wird.',
];
