export default [
  'Die Bierhefe in etwas warmem Wasser auflösen, ca. 10 ml. Das Salz zum Mehl geben und mischen. Das Wasser in einen großen Behälter gießen, die aufgelöste Hefe, das Öl und das Mehl nach und nach dazugeben, dabei mit andererseits beginnst du zu kneten. Etc...',
  'Geben Sie zuerst Mehl, Salz und Hefe in eine Schüssel und stellen Sie sicher, dass Salz und Hefe auf gegenüberliegenden Seiten liegen. Wasser und Olivenöl zugeben und zu einem groben Teig verkneten. Den Teig zu einer Kugel formen und auf einer leicht bemehlten Fläche etwa 10 Minuten kneten, bis der Teig glatt und elastisch ist. Etc...',
  'Die Hefe mit ½ Teelöffel Zucker 5 Minuten lang in das lauwarme Wasser geben. Mehl und Salz in einer großen Rührschüssel vermischen. In die Mitte eine Mulde machen und die Wasser-Hefe-Mischung hinzufügen, während der Teig mit einem Löffel verrührt wird haben einen Teig erhalten. Wenn er zu klebrig ist, können Sie nach und nach etwas mehr Mehl hinzufügen. usw...',
  'Für den Teig Öl, Hefe und 2 EL lauwarmes Wasser in einer Schüssel vermengen, um die Hefe aufzulösen. Mehl und 1 EL Salz in einer Schüssel mischen und in die Mitte eine Mulde drücken. 680 ml Wasser-Hefe-Mischung in die Vertiefung geben und mit den Händen zu einem klebrigen Teig verkneten (3-4 Minuten). Zum Hydratisieren mit Plastikfolie abdecken (15 Minuten), dann auf einer leicht bemehlten Arbeitsfläche glatt kneten (2 Minuten). Zurück in die Schüssel geben, mit Plastikfolie abdecken und im Kühlschrank fermentieren (24 Stunden). Etc..',
  'Zwiebeln in dünne Scheiben schneiden. Karotte, Sellerie und Knoblauchzehe fein hacken. In einem großen Topf (8 qt.) das Schmalz, die Zwiebeln und den fein gehackten Pancetta erhitzen. Kochen Sie für 5 Minuten unter Rühren, bis sie weich sind; Dann die Karotte, den Knoblauch und den Sellerie hinzufügen und 3-4 Minuten köcheln lassen. Etc...',
  'Sobald Sie Ihre Calamari gereinigt haben (Sie können den Fischhändler bitten, dies für Sie zu tun), schneiden Sie sie in Ringe und braten Sie sie mit Knoblauch und etwas Öl an. Fügen Sie Weißwein und Tomatenmark hinzu, und sobald der Alkohol verdunstet ist, heben Sie die Tomaten unter und kochen Sie sie 10 Minuten lang bei schwacher Hitze.',
  'Esslöffel natives Olivenöl extra in einer großen Bratpfanne bei mittlerer Hitze erhitzen. Fügen Sie die Zwiebel, den Sellerie und den Knoblauch hinzu, falls verwendet. Kochen Sie etwa 2 Minuten lang und fügen Sie bei Bedarf 1-2 Esslöffel Wasser hinzu.',
  'Einen großen Topf mit Olivenöl erhitzen, Champignons und Zwiebel dazugeben und unter häufigem Rühren 7-8 Minuten dünsten, ggf. einen Spritzer Brühe zugeben. Übertragen Sie das Gemüse in einen Behälter und stellen Sie den Topf wieder auf niedrige bis mittlere Hitze. Fügen Sie den Reis hinzu und rösten Sie ihn 1 Minute lang an, wobei Sie häufig umrühren. Fügen Sie den Wein hinzu und lassen Sie ihn verdunsten.',
  'Einfach Wasser, Zitronensaft und Zucker in einer großen Schüssel verrühren, bis sich der Zucker aufgelöst hat. Füllen Sie die Mischung in einen großen Metallbehälter (eine Kastenform würde perfekt funktionieren), decken Sie sie ab und stellen Sie sie für eine halbe Stunde in den Gefrierschrank. Verwenden Sie einen Holzlöffel, um die Mischung kräftig umzurühren, um alle Eiskristalle zu brechen, und stellen Sie sie dann wieder in den Gefrierschrank. Wiederholen Sie alle 30 Minuten das Rühren 2-3 Mal oder bis Ihr Granita eine samtig-eisige Textur erreicht hat.',
  'Brechen Sie die Kekse mit den Händen in Stücke oder geben Sie sie in einen Gefrierbeutel und brechen Sie sie vorsichtig mit einem Nudelholz. Zerdrücken Sie sie nicht. Die weiche Butter mit dem Zucker etwa 3 Minuten schaumig schlagen.',
  'Einen großen Topf mit leicht gesalzenem Wasser zum Kochen bringen, dann die Nudeln al dente kochen, etwa 8 Minuten für die Linguine. Nudeln abgießen und mit den anderen Zutaten in die Pfanne geben. Erhitzen Sie eine Pfanne bei mittlerer Hitze, fügen Sie das Olivenöl hinzu, gefolgt von den Lachsstücken, dem Knoblauch und dem Spinat und braten Sie alles 2 Minuten lang an.',
];
