/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AddressDefinitions } from '../../..';
import city from './city';
import city_name from './city_name';
import city_suffix from './city_suffix';
import postcode from './postcode';
import state from './state';
import state_abbr from './state_abbr';
import street_name from './street_name';
import street_root from './street_root';
import street_suffix from './street_suffix';

const address = {
  city,
  city_name,
  city_suffix,
  postcode,
  state,
  state_abbr,
  street_name,
  street_root,
  street_suffix,
} as Partial<AddressDefinitions>;

export default address;
