/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import address from './address';
import cell_phone from './cell_phone';
import lorem from './lorem';
import person from './person';
import phone_number from './phone_number';

const ja: LocaleDefinition = {
  title: 'Japanese',
  address,
  cell_phone,
  lorem,
  person,
  phone_number,
};

export default ja;
