/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import cell_phone from './cell_phone';
import company from './company';
import date from './date';
import location from './location';
import lorem from './lorem';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';

const ja: LocaleDefinition = {
  cell_phone,
  company,
  date,
  location,
  lorem,
  metadata,
  person,
  phone_number,
};

export default ja;
