/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import animal from './animal';
import book from './book';
import color from './color';
import company from './company';
import internet from './internet';
import location from './location';
import lorem from './lorem';
import metadata from './metadata';
import music from './music';
import person from './person';
import phone_number from './phone_number';
import science from './science';
import team from './team';

/**
 * The locale data for the `pl` locale.
 *
 * - Language: Polish
 * - Endonym: Polski
 */
const pl: LocaleDefinition = {
  animal,
  book,
  color,
  company,
  internet,
  location,
  lorem,
  metadata,
  music,
  person,
  phone_number,
  science,
  team,
};

export default pl;
