/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import address from './address';
import animal from './animal';
import cell_phone from './cell_phone';
import color from './color';
import company from './company';
import internet from './internet';
import lorem from './lorem';
import music from './music';
import name_ from './name';
import phone_number from './phone_number';
import science from './science';
import team from './team';

const pl: LocaleDefinition = {
  title: 'Polish',
  address,
  animal,
  cell_phone,
  color,
  company,
  internet,
  lorem,
  music,
  person: name_,
  phone_number,
  science,
  team,
};

export default pl;
