/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import animal from './animal';
import cell_phone from './cell_phone';
import color from './color';
import company from './company';
import internet from './internet';
import location from './location';
import lorem from './lorem';
import music from './music';
import person from './person';
import phone_number from './phone_number';
import science from './science';
import sports from './sports';

const pl: LocaleDefinition = {
  title: 'Polish',
  animal,
  cell_phone,
  color,
  company,
  internet,
  location,
  lorem,
  music,
  person,
  phone_number,
  science,
  sports,
};

export default pl;
