/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { ColorDefinitions } from '../../..';
import colorGamut from './color_gamut';
import human from './human';

const color: Partial<ColorDefinitions> = {
  human,
  colorGamut,
};

export default color;
