/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { ColorDefinitions } from '../../..';
import cssFunctions from './css_functions';
import cssSpaces from './css_spaces';
import human from './human';
import space from './space';

const color = {
  cssFunctions,
  cssSpaces,
  human,
  space,
} as Partial<ColorDefinitions>;

export default color;
