/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import brewery from './brewery';
import description from './description';
import name_ from './name';
import region from './region';
import size from './size';
import type_ from './type';
import zone from './zone';

const beer = {
  brewery,
  description,
  name: name_,
  region,
  size,
  type: type_,
  zone,
};

export default beer;
