/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinitions } from '../../..';
import building_number from './building_number';
import city from './city';
import city_name from './city_name';
import default_country from './default_country';
import postcode from './postcode';
import state from './state';
import street_address from './street_address';
import street_pattern from './street_pattern';
import street_prefix from './street_prefix';

const location: LocationDefinitions = {
  building_number,
  city,
  city_name,
  default_country,
  postcode,
  state,
  street_address,
  street_pattern,
  street_prefix,
};

export default location;
