/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'კვირა',
    'ოთხშაბათი',
    'ორშაბათი',
    'პარასკევი',
    'სამშაბათი',
    'შაბათი',
    'ხუთშაბათი',
  ],
  abbr: ['კვი', 'ოთხ', 'ორშ', 'პარ', 'სამ', 'შაბ', 'ხუთ'],
};
