/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { FinanceDefinition } from '../../../..';
import mastercard from './mastercard';
import visa from './visa';

const credit_card: FinanceDefinition['credit_card'] = {
  mastercard,
  visa,
};

export default credit_card;
