/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinitions } from '../../..';
import city from './city';
import city_prefix from './city_prefix';
import city_suffix from './city_suffix';
import country from './country';
import default_country from './default_country';
import postcode from './postcode';
import secondary_address from './secondary_address';
import state from './state';
import state_abbr from './state_abbr';
import street from './street';
import street_suffix from './street_suffix';

const location: LocationDefinitions = {
  city,
  city_prefix,
  city_suffix,
  country,
  default_country,
  postcode,
  secondary_address,
  state,
  state_abbr,
  street,
  street_suffix,
};

export default location;
