/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AddressDefinitions } from '../../..';
import city from './city';
import city_name from './city_name';
import country_code from './country_code';
import default_country from './default_country';
import postcode from './postcode';
import state from './state';
import state_abbr from './state_abbr';
import street_prefix from './street_prefix';
import street_suffix from './street_suffix';

const address: AddressDefinitions = {
  city,
  city_name,
  country_code,
  default_country,
  postcode,
  state,
  state_abbr,
  street_prefix,
  street_suffix,
};

export default address;
