/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AddressDefinitions } from '../../..';
import city from './city';
import city_name from './city_name';
import country_code from './country_code';
import default_country from './default_country';
import postcode from './postcode';
import state from './state';

const address = {
  city,
  city_name,
  country_code,
  default_country,
  postcode,
  state,
} as Partial<AddressDefinitions>;

export default address;
