/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import address from './address';
import cell_phone from './cell_phone';
import company from './company';
import date from './date';
import internet from './internet';
import person from './person';
import phone_number from './phone_number';

const mk: LocaleDefinition = {
  title: 'Macedonian',
  separator: ' и ',
  address,
  cell_phone,
  company,
  date,
  internet,
  person,
  phone_number,
};

export default mk;
