/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import company from './company';
import date from './date';
import internet from './internet';
import location from './location';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';

/**
 * The locale data for the `mk` locale.
 *
 * - Language: Macedonian
 * - Endonym: македонски јазик
 */
const mk: LocaleDefinition = {
  company,
  date,
  internet,
  location,
  metadata,
  person,
  phone_number,
};

export default mk;
