/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PlantDefinition } from '../../..';
import flower from './flower';
import tree from './tree';

const plant: PlantDefinition = {
  flower,
  tree,
};

export default plant;
