/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { StaysDefinitions } from '../../..';
import brands from './brands';
import description from './description';
import facilities from './facilities';
import propertyName from './propertyName';
import propertyType from './propertyType';
import reviewScore from './reviewScore';
import starRating from './starRating';

const stays: StaysDefinitions = {
  brands,
  description,
  facilities,
  propertyName,
  propertyType,
  reviewScore,
  starRating,
};

export default stays;
