/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AddressDefinitions } from '../../..';
import city from './city';
import city_prefix from './city_prefix';
import city_suffix from './city_suffix';
import country from './country';
import postcode from './postcode';
import state from './state';
import state_abbr from './state_abbr';
import street from './street';

const address: AddressDefinitions = {
  city,
  city_prefix,
  city_suffix,
  country,
  postcode,
  state,
  state_abbr,
  street,
};

export default address;
