/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import company from './company';
import internet from './internet';
import location from './location';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';

/**
 * The locale data for the `de_CH` locale.
 *
 * - Language: German (Switzerland)
 * - Endonym: Deutsch (Schweiz)
 */
const de_CH: LocaleDefinition = {
  company,
  internet,
  location,
  metadata,
  person,
  phone_number,
};

export default de_CH;
