/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: ['Jumat', 'Kamis', 'Minggu', 'Rabu', 'Sabtu', 'Selasa', 'Senin'],
  abbr: ['Jum', 'Kam', 'Min', 'Rab', 'Sab', 'Sel', 'Sen'],
};
