/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import color from './color';
import date from './date';
import metadata from './metadata';

/**
 * The locale data for the `mn` locale.
 *
 * - Language: Mongolian
 * - Endonym: Монгол
 */
const mn: LocaleDefinition = {
  color,
  date,
  metadata,
};

export default mn;
