/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import ar from '../locales/ar';
import en from '../locales/en';

export const faker = new Faker({
  locale: [ar, en],
});
