/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import az from '../locales/az';
import base from '../locales/base';
import en from '../locales/en';

export const faker = new Faker({
  locale: [az, en, base],
});
