/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import bn_BD from '../locales/bn_BD';
import en from '../locales/en';

/**
 * The faker instance for the `bn_BD` locale.
 *
 * - Language: Bengali (Bangladesh)
 * - Endonym: বাংলা (বাংলাদেশ)
 *
 * This instance uses the following locales internally (in descending precedence):
 *
 * - `bn_BD`
 * - `en`
 * - `base`
 */
export const faker = new Faker({
  locale: [bn_BD, en, base],
});
