/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import cy from '../locales/cy';
import en from '../locales/en';

/**
 * The faker instance for the `cy` locale.
 *
 * - Language: Welsh
 * - Endonym: Cymraeg
 *
 * This instance uses the following locales internally (in descending precedence):
 *
 * - `cy`
 * - `en`
 * - `base`
 */
export const faker = new Faker({
  locale: [cy, en, base],
});
