/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import cz from '../locales/cz';
import en from '../locales/en';

export const faker = new Faker({
  locale: 'cz',
  localeFallback: 'en',
  locales: {
    cz,
    en,
  },
});
