/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import de from '../locales/de';
import en from '../locales/en';
import global from '../locales/global';

export const faker = new Faker({
  locale: [de, en, global],
});
