/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import de from '../locales/de';
import en from '../locales/en';

const faker = new Faker({
  localeOrder: ['de', 'en'],
  locales: {
    de,
    en,
  },
});

export = faker;
