/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import de_AT from '../locales/de_AT.json';
import en from '../locales/en.json';

export const faker = new Faker({
  locale: 'de_AT',
  localeFallback: 'en',
  locales: {
    de_AT,
    en,
  },
});
