/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import dv from '../locales/dv';
import en from '../locales/en';

/**
 * The faker instance for the `dv` locale.
 *
 * - Language: Maldivian
 * - Endonym: ދިވެހި
 *
 * This instance uses the following locales internally (in descending precedence):
 *
 * - `dv`
 * - `en`
 * - `base`
 */
export const faker = new Faker({
  locale: [dv, en, base],
});
