/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import dv from '../locales/dv';
import en from '../locales/en';
import global from '../locales/global';

export const faker = new Faker({
  locale: [dv, en, global],
});
