/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import dv from '../locales/dv';
import en from '../locales/en';

export const faker = new Faker({
  locale: 'dv',
  localeFallback: 'en',
  locales: {
    dv,
    en,
  },
});
