/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import el from '../locales/el';
import global from '../locales/global';

export const faker = new Faker({
  locale: [el, global],
});
