/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import el from '../locales/el';
import en from '../locales/en';

export const faker = new Faker({
  locale: [el, en, base],
});
