/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';

const faker = new Faker({
  localeOrder: ['en'],
  locales: {
    en,
  },
});

export = faker;
