/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en.json';
import en_AU_ocker from '../locales/en_AU_ocker.json';

export const faker = new Faker({
  locale: 'en_AU_ocker',
  localeFallback: 'en',
  locales: {
    en_AU_ocker,
    en,
  },
});
