/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import en_BORK from '../locales/en_BORK';

export const faker = new Faker({
  locale: [en_BORK, en],
});
