/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import en_CA from '../locales/en_CA';

const faker = new Faker({
  localeOrder: ['en_CA', 'en'],
  locales: {
    en_CA,
    en,
  },
});

export = faker;
