/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import en_CA from '../locales/en_CA';

export const faker = new Faker({
  locale: [en_CA, en],
});
