/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import en_GH from '../locales/en_GH';

export const faker = new Faker({
  locale: [en_GH, en, base],
});
