/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import en_GB from '../locales/en_GB';

export const faker = new Faker({
  locale: [en_GB, en, base],
});
