/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en.json';
import en_IND from '../locales/en_IND.json';

export const faker = new Faker({
  locale: 'en_IND',
  localeFallback: 'en',
  locales: {
    en_IND,
    en,
  },
});
