/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import en_IND from '../locales/en_IND';

const faker = new Faker({
  localeOrder: ['en_IND', 'en'],
  locales: {
    en_IND,
    en,
  },
});

export = faker;
