/*
 * This file is automatically generated.
 * Run 'pnpm esno scripts/generateLocales.ts' to update.
 */

import { Faker } from '..';
import en_NG from '../locales/en_NG';
import en from '../locales/en';

const faker = new Faker({
  locale: 'en_NG',
  localeFallback: 'en',
  locales: {
    en_NG,
    en,
  },
});

export default faker;
