/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import en_NG from '../locales/en_NG';
import global from '../locales/global';

export const faker = new Faker({
  locale: [en_NG, en, global],
});
