/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import en_US from '../locales/en_US';

const faker = new Faker({
  localeOrder: ['en_US', 'en'],
  locales: {
    en_US,
    en,
  },
});

export = faker;
