/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import en_ZA from '../locales/en_ZA';

export const faker = new Faker({
  locale: [en_ZA, en],
});
