/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import es from '../locales/es';

export const faker = new Faker({
  locale: [es, en, base],
});
