/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import es from '../locales/es';

const faker = new Faker({
  localeOrder: ['es', 'en'],
  locales: {
    es,
    en,
  },
});

export = faker;
