/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import es from '../locales/es';
import es_CL from '../locales/es_CL';

/**
 * The faker instance for the `es_CL` locale.
 *
 * - Language: Spanish (Chile)
 * - Endonym: Español (Chile)
 *
 * This instance uses the following locales internally (in descending precedence):
 *
 * - `es_CL`
 * - `es`
 * - `en`
 * - `base`
 */
export const faker = new Faker({
  locale: [es_CL, es, en, base],
});
