/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import es from '../locales/es';
import es_MX from '../locales/es_MX';

const faker = new Faker({
  localeOrder: ['es_MX', 'es', 'en'],
  locales: {
    es_MX,
    es,
    en,
  },
});

export = faker;
