/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import fa from '../locales/fa';
import global from '../locales/global';

export const faker = new Faker({
  locale: [fa, global],
});
