/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en.json';
import fi from '../locales/fi.json';

export const faker = new Faker({
  locale: 'fi',
  localeFallback: 'en',
  locales: {
    fi,
    en,
  },
});
