/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import fi from '../locales/fi';

/**
 * The faker instance for the `fi` locale.
 *
 * - Language: Finnish
 * - Endonym: suomi
 *
 * This instance uses the following locales internally (in descending precedence):
 *
 * - `fi`
 * - `en`
 * - `base`
 */
export const faker = new Faker({
  locale: [fi, en, base],
});
