/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import fr from '../locales/fr';

export const faker = new Faker({
  locale: [fr, en, base],
});
