/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import fr from '../locales/fr';

const faker = new Faker({
  localeOrder: ['fr', 'en'],
  locales: {
    fr,
    en,
  },
});

export = faker;
