/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import fr from '../locales/fr';
import global from '../locales/global';

export const faker = new Faker({
  locale: [fr, global],
});
