/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import fr from '../locales/fr';
import fr_CA from '../locales/fr_CA';
import global from '../locales/global';

export const faker = new Faker({
  locale: [fr_CA, fr, en, global],
});
