/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import fr from '../locales/fr';
import fr_CH from '../locales/fr_CH';

const faker = new Faker({
  localeOrder: ['fr_CH', 'fr', 'en'],
  locales: {
    fr_CH,
    fr,
    en,
  },
});

export = faker;
