/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import fr from '../locales/fr';
import fr_CH from '../locales/fr_CH';

/**
 * The faker instance for the `fr_CH` locale.
 *
 * - Language: French (Switzerland)
 * - Endonym: Français (Suisse)
 *
 * This instance uses the following locales internally (in descending precedence):
 *
 * - `fr_CH`
 * - `fr`
 * - `en`
 * - `base`
 */
export const faker = new Faker({
  locale: [fr_CH, fr, en, base],
});
