/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '..';
import ge from '../locales/ge';
import en from '../locales/en';

const faker = new Faker({
  locale: 'ge',
  localeFallback: 'en',
  locales: {
    ge,
    en,
  },
});

export = faker;
