/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '..';
import he from '../locales/he';
import en from '../locales/en';

const faker = new Faker({
  locale: 'he',
  localeFallback: 'en',
  locales: {
    he,
    en,
  },
});

export = faker;
