/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import he from '../locales/he';

export const faker = new Faker({
  locale: 'he',
  localeFallback: 'en',
  locales: {
    he,
    en,
  },
});
