/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import global from '../locales/global';
import hr from '../locales/hr';

export const faker = new Faker({
  locale: [hr, en, global],
});
