/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en.json';
import hr from '../locales/hr.json';

export const faker = new Faker({
  locale: 'hr',
  localeFallback: 'en',
  locales: {
    hr,
    en,
  },
});
