/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import global from '../locales/global';
import hu from '../locales/hu';

export const faker = new Faker({
  locale: [hu, global],
});
