/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import hy from '../locales/hy';
import en from '../locales/en';

const faker = new Faker({
  locale: 'hy',
  localeFallback: 'en',
  locales: {
    hy,
    en,
  },
});

export = faker;
