/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import global from '../locales/global';
import hy from '../locales/hy';

export const faker = new Faker({
  locale: [hy, en, global],
});
