/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import global from '../locales/global';
import id_ID from '../locales/id_ID';

export const faker = new Faker({
  locale: [id_ID, en, global],
});
