/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { faker as fakerAF_ZA } from './af_ZA';
import { faker as fakerAR } from './ar';
import { faker as fakerAZ } from './az';
import { faker as fakerBASE } from './base';
import { faker as fakerCS_CZ } from './cs_CZ';
import { faker as fakerDE } from './de';
import { faker as fakerDE_AT } from './de_AT';
import { faker as fakerDE_CH } from './de_CH';
import { faker as fakerDV } from './dv';
import { faker as fakerEL } from './el';
import { faker as fakerEN } from './en';
import { faker as fakerEN_AU } from './en_AU';
import { faker as fakerEN_AU_ocker } from './en_AU_ocker';
import { faker as fakerEN_BORK } from './en_BORK';
import { faker as fakerEN_CA } from './en_CA';
import { faker as fakerEN_GB } from './en_GB';
import { faker as fakerEN_GH } from './en_GH';
import { faker as fakerEN_IE } from './en_IE';
import { faker as fakerEN_IN } from './en_IN';
import { faker as fakerEN_NG } from './en_NG';
import { faker as fakerEN_US } from './en_US';
import { faker as fakerEN_ZA } from './en_ZA';
import { faker as fakerES } from './es';
import { faker as fakerES_MX } from './es_MX';
import { faker as fakerFA } from './fa';
import { faker as fakerFI } from './fi';
import { faker as fakerFR } from './fr';
import { faker as fakerFR_BE } from './fr_BE';
import { faker as fakerFR_CA } from './fr_CA';
import { faker as fakerFR_CH } from './fr_CH';
import { faker as fakerFR_LU } from './fr_LU';
import { faker as fakerGE } from './ge';
import { faker as fakerHE } from './he';
import { faker as fakerHR } from './hr';
import { faker as fakerHU } from './hu';
import { faker as fakerHY } from './hy';
import { faker as fakerID_ID } from './id_ID';
import { faker as fakerIT } from './it';
import { faker as fakerJA } from './ja';
import { faker as fakerKO } from './ko';
import { faker as fakerLV } from './lv';
import { faker as fakerMK } from './mk';
import { faker as fakerNB_NO } from './nb_NO';
import { faker as fakerNE } from './ne';
import { faker as fakerNL } from './nl';
import { faker as fakerNL_BE } from './nl_BE';
import { faker as fakerPL } from './pl';
import { faker as fakerPT_BR } from './pt_BR';
import { faker as fakerPT_PT } from './pt_PT';
import { faker as fakerRO } from './ro';
import { faker as fakerRU } from './ru';
import { faker as fakerSK } from './sk';
import { faker as fakerSR_RS_latin } from './sr_RS_latin';
import { faker as fakerSV } from './sv';
import { faker as fakerTH } from './th';
import { faker as fakerTR } from './tr';
import { faker as fakerUK } from './uk';
import { faker as fakerUR } from './ur';
import { faker as fakerVI } from './vi';
import { faker as fakerZH_CN } from './zh_CN';
import { faker as fakerZH_TW } from './zh_TW';
import { faker as fakerZU_ZA } from './zu_ZA';

export {
  fakerAF_ZA,
  fakerAR,
  fakerAZ,
  fakerBASE,
  fakerCS_CZ,
  fakerDE,
  fakerDE_AT,
  fakerDE_CH,
  fakerDV,
  fakerEL,
  fakerEN,
  fakerEN_AU,
  fakerEN_AU_ocker,
  fakerEN_BORK,
  fakerEN_CA,
  fakerEN_GB,
  fakerEN_GH,
  fakerEN_IE,
  fakerEN_IN,
  fakerEN_NG,
  fakerEN_US,
  fakerEN_ZA,
  fakerES,
  fakerES_MX,
  fakerFA,
  fakerFI,
  fakerFR,
  fakerFR_BE,
  fakerFR_CA,
  fakerFR_CH,
  fakerFR_LU,
  fakerGE,
  fakerHE,
  fakerHR,
  fakerHU,
  fakerHY,
  fakerID_ID,
  fakerIT,
  fakerJA,
  fakerKO,
  fakerLV,
  fakerMK,
  fakerNB_NO,
  fakerNE,
  fakerNL,
  fakerNL_BE,
  fakerPL,
  fakerPT_BR,
  fakerPT_PT,
  fakerRO,
  fakerRU,
  fakerSK,
  fakerSR_RS_latin,
  fakerSV,
  fakerTH,
  fakerTR,
  fakerUK,
  fakerUR,
  fakerVI,
  fakerZH_CN,
  fakerZH_TW,
  fakerZU_ZA,
};

export const allFakers = {
  af_ZA: fakerAF_ZA,
  ar: fakerAR,
  az: fakerAZ,
  base: fakerBASE,
  cs_CZ: fakerCS_CZ,
  de: fakerDE,
  de_AT: fakerDE_AT,
  de_CH: fakerDE_CH,
  dv: fakerDV,
  el: fakerEL,
  en: fakerEN,
  en_AU: fakerEN_AU,
  en_AU_ocker: fakerEN_AU_ocker,
  en_BORK: fakerEN_BORK,
  en_CA: fakerEN_CA,
  en_GB: fakerEN_GB,
  en_GH: fakerEN_GH,
  en_IE: fakerEN_IE,
  en_IN: fakerEN_IN,
  en_NG: fakerEN_NG,
  en_US: fakerEN_US,
  en_ZA: fakerEN_ZA,
  es: fakerES,
  es_MX: fakerES_MX,
  fa: fakerFA,
  fi: fakerFI,
  fr: fakerFR,
  fr_BE: fakerFR_BE,
  fr_CA: fakerFR_CA,
  fr_CH: fakerFR_CH,
  fr_LU: fakerFR_LU,
  ge: fakerGE,
  he: fakerHE,
  hr: fakerHR,
  hu: fakerHU,
  hy: fakerHY,
  id_ID: fakerID_ID,
  it: fakerIT,
  ja: fakerJA,
  ko: fakerKO,
  lv: fakerLV,
  mk: fakerMK,
  nb_NO: fakerNB_NO,
  ne: fakerNE,
  nl: fakerNL,
  nl_BE: fakerNL_BE,
  pl: fakerPL,
  pt_BR: fakerPT_BR,
  pt_PT: fakerPT_PT,
  ro: fakerRO,
  ru: fakerRU,
  sk: fakerSK,
  sr_RS_latin: fakerSR_RS_latin,
  sv: fakerSV,
  th: fakerTH,
  tr: fakerTR,
  uk: fakerUK,
  ur: fakerUR,
  vi: fakerVI,
  zh_CN: fakerZH_CN,
  zh_TW: fakerZH_TW,
  zu_ZA: fakerZU_ZA,
} as const;
