/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import is_IS from '../locales/is_IS';

/**
 * The faker instance for the `is_IS` locale.
 *
 * - Language: Icelandic (Iceland)
 * - Endonym: Íslenska (Ísland)
 *
 * This instance uses the following locales internally (in descending precedence):
 *
 * - `is_IS`
 * - `en`
 * - `base`
 */
export const faker = new Faker({
  locale: [is_IS, en, base],
});
