/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import it from '../locales/it';

const faker = new Faker({
  localeOrder: ['it', 'en'],
  locales: {
    it,
    en,
  },
});

export = faker;
