/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import it from '../locales/it';
import en from '../locales/en';

const faker = new Faker({
  locale: 'it',
  localeFallback: 'en',
  locales: {
    it,
    en,
  },
});

export = faker;
