/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en.json';
import ja from '../locales/ja.json';

export const faker = new Faker({
  locale: 'ja',
  localeFallback: 'en',
  locales: {
    ja,
    en,
  },
});
