/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import ja from '../locales/ja';

const faker = new Faker({
  localeOrder: ['ja', 'en'],
  locales: {
    ja,
    en,
  },
});

export = faker;
