/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import ko from '../locales/ko';

export const faker = new Faker({
  locale: [ko, en],
});
