/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import ko from '../locales/ko';

const faker = new Faker({
  localeOrder: ['ko', 'en'],
  locales: {
    ko,
    en,
  },
});

export = faker;
