/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import ko from '../locales/ko';
import en from '../locales/en';

const faker = new Faker({
  locale: 'ko',
  localeFallback: 'en',
  locales: {
    ko,
    en,
  },
});

export = faker;
