/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import ku from '../locales/ku';

/**
 * The faker instance for the `ku` locale.
 *
 * - Language: Kurdish
 * - Endonym: کوردیی
 *
 * This instance uses the following locales internally (in descending precedence):
 *
 * - `ku`
 * - `en`
 * - `base`
 */
export const faker = new Faker({
  locale: [ku, en, base],
});
