/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import ku_ckb from '../locales/ku_ckb';

/**
 * The faker instance for the `ku_ckb` locale.
 *
 * - Language: Kurdish (Sorani)
 * - Endonym: کوردی (سۆرانی)
 *
 * This instance uses the following locales internally (in descending precedence):
 *
 * - `ku_ckb`
 * - `en`
 * - `base`
 */
export const faker = new Faker({
  locale: [ku_ckb, en, base],
});
