/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import lv from '../locales/lv';

const faker = new Faker({
  localeOrder: ['lv', 'en'],
  locales: {
    lv,
    en,
  },
});

export = faker;
