/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import global from '../locales/global';
import lv from '../locales/lv';

export const faker = new Faker({
  locale: [lv, global],
});
