/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en.json';
import mk from '../locales/mk.json';

export const faker = new Faker({
  locale: 'mk',
  localeFallback: 'en',
  locales: {
    mk,
    en,
  },
});
