/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import mk from '../locales/mk';

export const faker = new Faker({
  locale: [mk, en],
});
