/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import mn from '../locales/mn';

/**
 * The faker instance for the `mn` locale.
 *
 * - Language: Mongolian
 * - Endonym: Монгол
 *
 * This instance uses the following locales internally (in descending precedence):
 *
 * - `mn`
 * - `en`
 * - `base`
 */
export const faker = new Faker({
  locale: [mn, en, base],
});
