/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import nb_NO from '../locales/nb_NO';

export const faker = new Faker({
  locale: [nb_NO, en, base],
});
