/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import nb_NO from '../locales/nb_NO';
import en from '../locales/en';

const faker = new Faker({
  locale: 'nb_NO',
  localeFallback: 'en',
  locales: {
    nb_NO,
    en,
  },
});

export = faker;
