/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import nb_NO from '../locales/nb_NO';

const faker = new Faker({
  localeOrder: ['nb_NO', 'en'],
  locales: {
    nb_NO,
    en,
  },
});

export = faker;
