/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import ne from '../locales/ne';

const faker = new Faker({
  localeOrder: ['ne', 'en'],
  locales: {
    ne,
    en,
  },
});

export = faker;
