/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en.json';
import ne from '../locales/ne.json';

export const faker = new Faker({
  locale: 'ne',
  localeFallback: 'en',
  locales: {
    ne,
    en,
  },
});
