/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import nl from '../locales/nl';
import en from '../locales/en';

const faker = new Faker({
  locale: 'nl',
  localeFallback: 'en',
  locales: {
    nl,
    en,
  },
});

export = faker;
