/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import nl from '../locales/nl';

export const faker = new Faker({
  locale: [nl, en],
});
