/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import nl from '../locales/nl';
import nl_BE from '../locales/nl_BE';

/**
 * The faker instance for the `nl_BE` locale.
 *
 * - Language: Dutch (Belgium)
 * - Endonym: Nederlands (België)
 *
 * This instance uses the following locales internally (in descending precedence):
 *
 * - `nl_BE`
 * - `nl`
 * - `en`
 * - `base`
 */
export const faker = new Faker({
  locale: [nl_BE, nl, en, base],
});
