/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import nl from '../locales/nl';
import nl_BE from '../locales/nl_BE';

const faker = new Faker({
  localeOrder: ['nl_BE', 'nl', 'en'],
  locales: {
    nl_BE,
    nl,
    en,
  },
});

export = faker;
