/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en.json';
import pl from '../locales/pl.json';

export const faker = new Faker({
  locale: 'pl',
  localeFallback: 'en',
  locales: {
    pl,
    en,
  },
});
