/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import pt_PT from '../locales/pt_PT';

export const faker = new Faker({
  locale: [pt_PT, en],
});
