/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en.json';
import pt_PT from '../locales/pt_PT.json';

export const faker = new Faker({
  locale: 'pt_PT',
  localeFallback: 'en',
  locales: {
    pt_PT,
    en,
  },
});
