/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import ro_MD from '../locales/ro_MD';

export const faker = new Faker({
  locale: 'ro_MD',
  localeFallback: 'en',
  locales: {
    ro_MD,
    en,
  },
});
