/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import sk from '../locales/sk';
import en from '../locales/en';

const faker = new Faker({
  locale: 'sk',
  localeFallback: 'en',
  locales: {
    sk,
    en,
  },
});

export = faker;
