/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import sk from '../locales/sk';

/**
 * The faker instance for the `sk` locale.
 *
 * - Language: Slovak
 * - Endonym: slovenčina
 *
 * This instance uses the following locales internally (in descending precedence):
 *
 * - `sk`
 * - `en`
 * - `base`
 */
export const faker = new Faker({
  locale: [sk, en, base],
});
