/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import sr_RS_latin from '../locales/sr_RS_latin';

export const faker = new Faker({
  locale: [sr_RS_latin, en],
});
