/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import sr_RS from '../locales/sr_RS';

export const faker = new Faker({
  locale: [sr_RS, en],
});
