/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import sv from '../locales/sv';

/**
 * The faker instance for the `sv` locale.
 *
 * - Language: Swedish
 * - Endonym: Svenska
 *
 * This instance uses the following locales internally (in descending precedence):
 *
 * - `sv`
 * - `en`
 * - `base`
 */
export const faker = new Faker({
  locale: [sv, en, base],
});
