/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import ta from '../locales/ta';

/**
 * The faker instance for the `ta` locale.
 *
 * - Language: Tamil
 * - Endonym: தமிழ்
 *
 * This instance uses the following locales internally (in descending precedence):
 *
 * - `ta`
 * - `en`
 * - `base`
 */
export const faker = new Faker({
  locale: [ta, en, base],
});
