/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import global from '../locales/global';
import tr from '../locales/tr';

export const faker = new Faker({
  locale: [tr, global],
});
