/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import tr from '../locales/tr';

export const faker = new Faker({
  locale: [tr, en],
});
