/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import vi from '../locales/vi';

export const faker = new Faker({
  locale: [vi, en, base],
});
