/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import yo from '../locales/yo';

export const faker = new Faker({
  locale: [yo, en, base],
});
