/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import global from '../locales/global';
import zh_CN from '../locales/zh_CN';

export const faker = new Faker({
  locale: [zh_CN, global],
});
