/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import zh_CN from '../locales/zh_CN';
import en from '../locales/en';

const faker = new Faker({
  locale: 'zh_CN',
  localeFallback: 'en',
  locales: {
    zh_CN,
    en,
  },
});

export = faker;
