/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en';
import zh_TW from '../locales/zh_TW';

const faker = new Faker({
  localeOrder: ['zh_TW', 'en'],
  locales: {
    zh_TW,
    en,
  },
});

export = faker;
