/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import en from '../locales/en.json';
import zu_ZA from '../locales/zu_ZA.json';

export const faker = new Faker({
  locale: 'zu_ZA',
  localeFallback: 'en',
  locales: {
    zu_ZA,
    en,
  },
});
