/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import lorem from './lorem';
import metadata from './metadata';

/**
 * The locale data for the `ku` locale.
 *
 * - Language: Kurdish
 * - Endonym: کوردیی
 */
const ku: LocaleDefinition = {
  lorem,
  metadata,
};

export default ku;
