/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AddressDefinitions } from '../../..';
import building_number from './building_number';
import city from './city';
import city_name from './city_name';
import city_prefix from './city_prefix';
import city_suffix from './city_suffix';
import country from './country';
import country_code from './country_code';
import default_country from './default_country';
import direction from './direction';
import postcode from './postcode';
import secondary_address from './secondary_address';
import state from './state';
import street_address from './street_address';
import street_name from './street_name';
import street_prefix from './street_prefix';
import street_suffix from './street_suffix';

const address = {
  building_number,
  city,
  city_name,
  city_prefix,
  city_suffix,
  country,
  country_code,
  default_country,
  direction,
  postcode,
  secondary_address,
  state,
  street_address,
  street_name,
  street_prefix,
  street_suffix,
} as Partial<AddressDefinitions>;

export default address;
