/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'Friday',
    'Monday',
    'Saturday',
    'Sunday',
    'Thursday',
    'Tuesday',
    'Wednesday',
  ],
  abbr: ['Fri', 'Mon', 'Sat', 'Sun', 'Thu', 'Tue', 'Wed'],
};
