/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { ScienceDefinition } from '../../..';
import unit from './unit';

const science: ScienceDefinition = {
  unit,
};

export default science;
