/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import company from './company';
import date from './date';
import internet from './internet';
import location from './location';
import person from './person';
import phone_number from './phone_number';

const id_ID: LocaleDefinition = {
  title: 'Indonesian',
  company,
  date,
  internet,
  location,
  person,
  phone_number,
};

export default id_ID;
