/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { SportsDefinitions } from '../../..';
import team_suffix from './team_suffix';

const sports: SportsDefinitions = {
  team_suffix,
};

export default sports;
