/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LoremDefinitions } from '../../..';
import supplemental from './supplemental';
import words from './words';

const lorem: LoremDefinitions = {
  supplemental,
  words,
};

export default lorem;
