/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { FinanceDefinition } from '../../..';
import common_credit_card_issuer from './common_credit_card_issuer';

const finance: FinanceDefinition = {
  common_credit_card_issuer,
};

export default finance;
