/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { FinanceDefinition } from '../../..';
import bitcoin_address_specs from './bitcoin_address_specs';

const finance: FinanceDefinition = {
  bitcoin_address_specs,
};

export default finance;
