/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { FinanceDefinition } from '../../..';
import federal_reserve_routing_symbol from './federal_reserve_routing_symbol';

const finance: FinanceDefinition = {
  federal_reserve_routing_symbol,
};

export default finance;
