/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { SportsDefinitions } from '../../..';
import team_patterns from './team_patterns';
import team_prefix from './team_prefix';

const sports: SportsDefinitions = {
  team_patterns,
  team_prefix,
};

export default sports;
