/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { NameDefinitions } from '../../..';
import female_first_name from './female_first_name';
import female_middle_name from './female_middle_name';
import first_name from './first_name';
import gender from './gender';
import last_name from './last_name';
import male_first_name from './male_first_name';
import male_middle_name from './male_middle_name';
import middle_name from './middle_name';
import name_ from './name';
import prefix from './prefix';
import sex from './sex';
import suffix from './suffix';
import title from './title';

const name: NameDefinitions = {
  female_first_name,
  female_middle_name,
  first_name,
  gender,
  last_name,
  male_first_name,
  male_middle_name,
  middle_name,
  name: name_,
  prefix,
  sex,
  suffix,
  title,
};

export default name;
