/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { GlassesDefinitions } from '../../..';
import brand from './brand';
import gender from './gender';
import lensType from './lensType';
import material from './material';
import productType from './productType';
import shape from './shape';
import size from './size';

const glasses: GlassesDefinitions = {
  brand,
  gender,
  lensType,
  material,
  productType,
  shape,
  size,
};

export default glasses;
