export default [
  "Dissolve the brewer's yeast in a little warm water, about 10 ml. Add the salt to the flour and mix. Pour the water into a large container, add the dissolved yeast, the oil and the flour a little at a time, while with the other hand you begin to knead. Etc...",
  'First, put the flour, salt and yeast in a bowl making sure to put the salt and yeast at opposite sides. Add the water and olive oil and mix together to form a rough dough. Shape the dough into a ball then knead on a lightly floured surface for around 10 minutes until the dough is smooth and elastic. Etc...',
  "Add the yeast to the lukewarm water with ½ teaspoon sugar for 5 minutes. Combine the flour and salt in a large mixing bowl. Make a well in the centre and add the water/yeast mixture whilst mixing the dough together with a spoon until you have obtained a dough. If it's too sticky you can gradually add a little more flour. Etc...",
  'For dough, combine oil, yeast and 2 tbsp lukewarm water in a bowl to dissolve yeast. Combine flour and 1 tbsp salt in a bowl and make a well in the centre. Add 680ml water and yeast mixture to well and mix with your hands to form a sticky dough (3-4 minutes). Cover with plastic wrap to hydrate (15 minutes), then knead on a lightly floured bench until smooth (2 minutes). Return to bowl, cover with plastic wrap and refrigerate to ferment (24 hours). Etc..',
  'Slice the onions into thin rounds. Finely chop the carrot, celery and garlic clove. In a large saucepan (8 qt.), heat the lard, onions and finely chopped pancetta. Cook for 5 minutes, stirring, until soft; then add the carrot, garlic, and celery and simmer for 3-4 minutes. Etc...',
  'Once you’ve cleaned your calamari (you can ask the fishmonger to do it for you), cut them into rings and sauté them with garlic and a bit of oil. Add white wine & tomato paste, and once the alcohol is evaporated, fold in the tomatoes and cook for 10 minutes over a gentle heat.',
  'Heat 3 tablespoons of extra-virgin olive oil in a large sauté pan over medium heat. Add the onion, celery and garlic if using. Cook, for about 2 minutes, adding 1-2 tablespoons of water if necessary.',
  'Heat a large pot with olive oil, add the mushrooms and onion and cook, stirring often for 7-8 minutes, adding a splash of stock if needed. Transfer the veggies into a container and return the pot to low-medium heat. Add the rice and toast it for 1 minute, stirring often. Add the wine, and let it evaporate.',
  'Simply stir together water, lemon juice, and sugar in a large bowl, until the sugar has dissolved. Transfer the mixture into a large metal container ( a loaf tin would work perfectly), cover, and place it in the freezer for half an hour. Use a wooden spoon to stir vigorously the mixture to break any ice crystals, then transfer it back in the freezer. Repeat every 30 minutes stirring 2-3 times, or until your granita has reached a velvety icy texture.',
  'Break the cookies into chunks using your hands, or place them in a freezer bag and gently break them with a rolling pin. Do not crush them. Whisk the softened butter with the sugar until pale and fluffy, about 3 minutes.',
  'Bring a large pot of lightly salted water to a boil, then cook the pasta al dente, about 8 minutes for linguine. Drain the pasta and transfer into the skillet with the other ingredients. Heat a skillet over medium heat, add the olive oil, followed by the salmon chunks, garlic and spinach and sauté for 2 minutes.',
];
