export default [
  "La 'Monflowers' est une bière Blanche au timbre très rafraîchissant et frais, inspirée de la tradition belge et obtenue à partir d'un mélange d'épices et de fleurs de Monferrato, de malt piémontais et de blé. Le nez raconte des notes délicates de blé, de céréales et de froment, soutenu par des notes de miel apportées par le malt italien. La gorgée est légère, fine, avec une boisson rafraîchissante et très douce",
  'Eporedian Pale Ale est une bière du Canavese avec un ton amer et citronné typique et agréable, avec un développement dynamique et très intrigant en bouche. Le nez est marqué par des arômes herbacés intenses, avec des sensations de pamplemousse et de houblon frais. Il développe une gorgée amère et magnifiquement progressive, sans être envahissante, mais extrêmement désaltérante et buvable',
  "'Che Belle Gose' est une délicieuse bière Gose au goût salé élaborée par le Birrifcio Civale en collaboration avec la Brasserie Croce di Malto et Montegioco. Elle s'inspire des modèles allemands de Leipzig qui prévoient l'ajout de sel blanc et rose dans les phases de production. C'est littéralement une bière salée au profil rafraîchissant, frais et marin, enrichie d'arômes de coriandre, d'agrumes, de blé et de fleurs blanches",
  "La bière 'Audace' du 32 Via dei Birrai est une bière belge forte avec un caractère fort et des sensations d'agrumes données par l'ajout de zeste d'orange bouillant. Le nez dégage des arômes chaleureux de pissenlit et de camomille, de pêche au sirop et d'amande et en bouche il est plein et agréablement citrin, sans accents amers, très doux",
  "L'Ippa di Baladin est l'interprétation italienne de la célèbre Indian Pale Ale selon le style Teo Musso, pionnier dans le monde des bières artisanales. Fabriquée avec du houblon cultivé sur le sol italien, elle brille dans le verre avec son manteau ambré caractérisé par une agréable mousse blanche. Le nez se caractérise par d'intenses notes herbacées, amères, d'agrumes et de légères sensations de mangue. À la gorgée, elle est buvable, légère et propre, avec de longues notes de houblonL'Ippa di Baladin est l'interprétation italienne de la célèbre Indian Pale Ale selon le style Teo Musso, pionnier dans le monde des bières artisanales. Fabriquée avec du houblon cultivé sur le sol italien, elle brille dans le verre avec son manteau ambré caractérisé par une agréable mousse blanche. Le nez se caractérise par d'intenses notes herbacées, amères, d'agrumes et de légères sensations de mangue. À la gorgée, il est buvable, léger et propre, avec de longues notes de houblon",
  "'Lago Nero' est une bière Stout inspirée du modèle irlandais et caractérisée par de fortes notes fumées. Elle révèle un profil olfactif torréfié et épicé, avec des notes de speck fumé, de cacao amer, de grains de café et un houblonnage fin. À la gorgée, il montre la note classique du malt grillé avec un corps fluide et agréablement amer",
  "'Full Moon' de la brasserie Triporteur est une bière brune inspirée de la typique Quadrupel de Belgique, rehaussée d'un repos en chêne belge toasté. Il s'ouvre au nez sur des arômes intenses et chaleureux de pomme confite, de caramel et de réglisse avec des nuances grillées et boisées. La gorgée est riche et généreuse, bien équilibrée entre la teneur en sucre et la nuance fruitée, ronde et vraiment persistante",
  "'Admiral' by 32 - Brasserie Via dei Birrai est une bière de fermentation haute ambrée avec une couleur sombre et des nuances rubis avec une mousse beige compacte et persistante. Le nez dégage des arômes typiques de malt et de caramel avec des retours de levure et de torréfaction. En bouche il est plein, avec une belle fraîcheur et une agréable finale herbacée et amère donnée par le houblon Admiral utilisé",
  "La bière 'Strike' de BAV est une IPA italienne produite avec refermentation en bouteille et avec une valeur IBU élevée. Il se caractérise par des parfums parfumés et citronnés, avec des nuances de fruits exotiques, d'herbes et de levures. Le goût est frais, bien structuré et légèrement fruité, facile à boire malgré les arômes intenses et longs de houblon amer",
  "IPA by Brigà est une interprétation piémontaise du style de brassage le plus aimé (et le plus abusé) qui existe : l'India Pale Ale. C'est une bière de fermentation haute, fabriquée à partir d'eau pure Pian della Mussa et de matières premières issues de l'agriculture biologique. Ambre avec un timbre tropical, herbacé et citronné, il se termine par une pointe amère typique du style",
  "'Ghisa' de la brasserie Lambrate est une bière brune de style Smoked Stout qui impressionne par son équilibre naturel entre les parfums fumés, typiques de cette catégorie, et la buvabilité fluide. Au nez, il s'ouvre sur des arômes de café, de cappuccino, de maron glacé et de châtaignes avec une gorgée dense et douce, vive et délicate riche en nuances de fumé, de café et de caramel qui rappellent parfaitement les arômes olfactifs",
  "'Vincent Vega' est le protagoniste du film culte Pulp Fiction auquel Retorto a dédié cette bière ambrée inspirée des triples d'abbaye. Doté d'un chapeau de mousse particulièrement crémeux et persistant, il se dévoile dans une robe fauve de couleur caramel aux senteurs d'agrumes dues à l'orange rouge et au pamplemousse rose. Il donne des sensations enveloppantes et pleines, sans être écoeurant, avec une finale sèche particulièrement appétissante",
];
