/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import address from './address';
import cell_phone from './cell_phone';
import color from './color';
import commerce from './commerce';
import company from './company';
import date from './date';
import internet from './internet';
import name_ from './name';
import phone_number from './phone_number';

const es: LocaleDefinition = {
  title: 'Spanish',
  address,
  cell_phone,
  color,
  commerce,
  company,
  date,
  internet,
  name: name_,
  phone_number,
};

export default es;
