/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import book from './book';
import cell_phone from './cell_phone';
import color from './color';
import commerce from './commerce';
import company from './company';
import date from './date';
import flights from './flights';
import food from './food';
import internet from './internet';
import location from './location';
import person from './person';
import phone_number from './phone_number';
import recipe from './recipe';
import stays from './stays';

const es: LocaleDefinition = {
  title: 'Spanish',
  book,
  cell_phone,
  color,
  commerce,
  company,
  date,
  flights,
  food,
  internet,
  location,
  person,
  phone_number,
  recipe,
  stays,
};

export default es;
