export default [
  'Disuelva la levadura de cerveza en un poco de agua tibia, unos 10 ml. Añada la sal a la harina y mezcle. Vierta el agua en un recipiente grande, agregue la levadura disuelta, el aceite y la harina poco a poco, mientras con con la otra mano empiezas a amasar. Etc...',
  'Primero, pon la harina, la sal y la levadura en un bol asegurándote de poner la sal y la levadura en lados opuestos. Agregue el agua y el aceite de oliva y mezcle hasta formar una masa áspera. Forme la masa en una bola y luego amase sobre una superficie ligeramente enharinada durante unos 10 minutos hasta que la masa esté suave y elástica. Etc...',
  'Agregue la levadura al agua tibia con ½ cucharadita de azúcar durante 5 minutos. Combine la harina y la sal en un tazón grande para mezclar. Haga un pozo en el centro y agregue la mezcla de agua y levadura mientras mezcla la masa con una cuchara hasta que haber obtenido una masa. Si te queda muy pegajosa puedes ir añadiendo poco a poco más harina. Etc...',
  'Para la masa, combine el aceite, la levadura y 2 cucharadas de agua tibia en un recipiente para disolver la levadura. Combine la harina y 1 cucharada de sal en un bol y haga un hueco en el centro. Agregue 680 ml de mezcla de agua y levadura al pozo y mezcle con las manos para formar una masa pegajosa (3-4 minutos). Cubra con una envoltura de plástico para hidratar (15 minutos), luego amase en un banco ligeramente enharinado hasta que quede suave (2 minutos). Regrese al tazón, cubra con una envoltura de plástico y refrigere para fermentar (24 horas). Etc..',
  'Corta las cebollas en rodajas finas. Picar finamente la zanahoria, el apio y el diente de ajo. En una cacerola grande (8 qt.), caliente la manteca de cerdo, las cebollas y la panceta finamente picada. Cocine por 5 minutos, revolviendo, hasta que esté suave; luego agregue la zanahoria, el ajo y el apio y cocine a fuego lento durante 3-4 minutos. Etc...',
  'Una vez limpios los calamares (puedes pedirle al pescadero que lo haga por ti), córtalos en aros y saltéalos con ajo y un poco de aceite. Añadir el vino blanco y la pasta de tomate y, una vez evaporado el alcohol, incorporar los tomates y cocinar durante 10 minutos a fuego suave.',
  'Caliente 3 cucharadas de aceite de oliva virgen extra en una sartén grande a fuego medio. Agregue la cebolla, el apio y el ajo si los usa. Cocine, durante unos 2 minutos, agregando 1-2 cucharadas de agua si es necesario.',
  'Caliente una olla grande con aceite de oliva, agregue los champiñones y la cebolla y cocine, revolviendo con frecuencia durante 7-8 minutos, agregando un chorrito de caldo si es necesario. Transfiera las verduras a un recipiente y vuelva a poner la olla a fuego medio-bajo. Agrega el arroz y tuéstalo durante 1 minuto, revolviendo con frecuencia. Agrega el vino y deja que se evapore.',
  'Simplemente mezcle el agua, el jugo de limón y el azúcar en un tazón grande, hasta que el azúcar se haya disuelto. Transfiera la mezcla a un recipiente de metal grande (un molde para pan funcionaría perfectamente), cúbralo y colóquelo en el congelador durante media hora. Use una cuchara de madera para remover vigorosamente la mezcla para romper los cristales de hielo, luego vuelva a transferirla al congelador. Repita cada 30 minutos revolviendo 2-3 veces, o hasta que su granizado haya alcanzado una textura helada aterciopelada.',
  'Rompe las galletas en trozos con las manos o colócalas en una bolsa para congelar y rómpelas suavemente con un rodillo. No los aplastes. Bate la mantequilla blanda con el azúcar hasta que esté pálida y esponjosa, unos 3 minutos.',
  'Haga hervir una olla grande de agua ligeramente salada, luego cocine la pasta al dente, aproximadamente 8 minutos para los linguini. Escurra la pasta y transfiérala a la sartén con los demás ingredientes. Calienta una sartén a fuego medio, agrega el aceite de oliva, luego los trozos de salmón, el ajo y las espinacas y saltea durante 2 minutos.',
];
