/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { VehicleDefinition } from '../../..';
import fuel from './fuel';
import type_ from './type';

const vehicle: VehicleDefinition = {
  fuel,
  type: type_,
};

export default vehicle;
