/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AddressDefinitions } from '../../..';
import county from './county';
import default_country from './default_country';
import postcode from './postcode';
import uk_country from './uk_country';

const address = {
  county,
  default_country,
  postcode,
  uk_country,
} as Partial<AddressDefinitions>;

export default address;
