/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { WordDefinition } from '../../..';
import letter from './letter';

const word: WordDefinition = {
  letter,
};

export default word;
