/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import animal from './animal';
import book from './book';
import cell_phone from './cell_phone';
import color from './color';
import date from './date';
import internet from './internet';
import location from './location';
import metadata from './metadata';
import person from './person';
import science from './science';
import team from './team';

/**
 * The locale data for the `bn` locale.
 *
 * - Language: Bengali
 * - Endonym: বাংলা
 */
const bn: LocaleDefinition = {
  animal,
  book,
  cell_phone,
  color,
  date,
  internet,
  location,
  metadata,
  person,
  science,
  team,
};

export default bn;
