/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { BookDefinition } from '../../..';
import author from './author';
import format from './format';
import genre from './genre';
import publisher from './publisher';
import series from './series';
import title from './title';

const book: BookDefinition = {
  author,
  format,
  genre,
  publisher,
  series,
  title,
};

export default book;
