/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AddressDefinitions } from '../../..';
import city from './city';
import city_root from './city_root';
import country from './country';
import default_country from './default_country';
import postcode from './postcode';

const address = {
  city,
  city_root,
  country,
  default_country,
  postcode,
} as Partial<AddressDefinitions>;

export default address;
