/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AddressDefinitions } from '../../..';
import default_country from './default_country';
import postcode from './postcode';

const address: Partial<AddressDefinitions> = {
  default_country,
  postcode,
};

export default address;
