/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import cell_phone from './cell_phone';
import color from './color';
import commerce from './commerce';
import company from './company';
import date from './date';
import internet from './internet';
import location from './location';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';
import team from './team';

/**
 * The locale data for the `sv` locale.
 *
 * - Language: Swedish
 * - Endonym: Svenska
 */
const sv: LocaleDefinition = {
  cell_phone,
  color,
  commerce,
  company,
  date,
  internet,
  location,
  metadata,
  person,
  phone_number,
  team,
};

export default sv;
