/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import cell_phone from './cell_phone';
import color from './color';
import commerce from './commerce';
import company from './company';
import date from './date';
import internet from './internet';
import location from './location';
import person from './person';
import phone from './phone';
import team from './team';

const sv: LocaleDefinition = {
  title: 'Swedish',
  cell_phone,
  color,
  commerce,
  company,
  date,
  internet,
  location,
  person,
  phone,
  team,
};

export default sv;
