/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CondomDefinitions } from '../../..';
import brand from './brand';
import description from './description';
import flavour from './flavour';
import lubricant from './lubricant';
import material from './material';
import name_ from './name';
import size from './size';
import type_ from './type';

const condom: CondomDefinitions = {
  brand,
  description,
  flavour,
  lubricant,
  material,
  name: name_,
  size,
  type: type_,
};

export default condom;
