/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PersonDefinition } from '../../../definitions';
import sex from './sex';

const person: PersonDefinition = {
  sex,
};

export default person;
