/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PhoneNumberDefinition } from '../../../..';
import human from './human';
import national from './national';
import raw from './raw';

const format: PhoneNumberDefinition['format'] = {
  human,
  national,
  raw,
};

export default format;
