/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'Aralık',
    'Ağustos',
    'Ekim',
    'Eylül',
    'Haziran',
    'Kasım',
    'Mart',
    'Mayıs',
    'Nisan',
    'Ocak',
    'Temmuz',
    'Şubat',
  ],
  abbr: [
    'Ara',
    'Ağu',
    'Eki',
    'Eyl',
    'Haz',
    'Kas',
    'Mar',
    'May',
    'Nis',
    'Oca',
    'Tem',
    'Şub',
  ],
};
