/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'Cuma',
    'Cumartesi',
    'Pazar',
    'Pazartesi',
    'Perşembe',
    'Salı',
    'Çarşamba',
  ],
  abbr: ['Cmt', 'Cum', 'Paz', 'Per', 'Pzt', 'Sal', 'Çar'],
};
