/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import cell_phone from './cell_phone';
import date from './date';
import internet from './internet';
import location from './location';
import person from './person';
import phone_number from './phone_number';

const hr: LocaleDefinition = {
  title: 'Hrvatski',
  cell_phone,
  date,
  internet,
  location,
  person,
  phone_number,
};

export default hr;
