/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import internet from './internet';
import location from './location';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';

/**
 * The locale data for the `fr_CA` locale.
 *
 * - Language: French (Canada)
 * - Endonym: Français (Canada)
 */
const fr_CA: LocaleDefinition = {
  internet,
  location,
  metadata,
  person,
  phone_number,
};

export default fr_CA;
