/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import internet from './internet';
import location from './location';
import phone_number from './phone_number';

const fr_CA: LocaleDefinition = {
  title: 'French (Canada)',
  internet,
  location,
  phone_number,
};

export default fr_CA;
