/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import cell_phone from './cell_phone';
import color from './color';
import company from './company';
import date from './date';
import location from './location';
import lorem from './lorem';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';

/**
 * The locale data for the `dv` locale.
 *
 * - Language: Maldivian
 * - Endonym: ދިވެހި
 */
const dv: LocaleDefinition = {
  cell_phone,
  color,
  company,
  date,
  location,
  lorem,
  metadata,
  person,
  phone_number,
};

export default dv;
