/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import cell_phone from './cell_phone';
import color from './color';
import company from './company';
import date from './date';
import location from './location';
import lorem from './lorem';
import person from './person';
import phone from './phone';

const dv: LocaleDefinition = {
  title: 'Dhivehi',
  cell_phone,
  color,
  company,
  date,
  location,
  lorem,
  person,
  phone,
};

export default dv;
