export default [
  'SHA-256',
  'Skein-SHA2',
  'Scrypt',
  'X11',
  'SHA-256d',
  'NeoScrypt',
  'X13',
  'Quark',
  'Multi-algorithm',
  'CryptoNight',
  'Lyra2Z',
  'Ethash',
  'X16R',
  'Equihash 200_9',
  'Nist5',
  'Lyra2REv2',
  'Xevan',
  'Skein',
  'C11',
  'CryptoNightV7',
  'HMQ1725',
  'Equihash 144_5 (ZHash)',
  'Qubit',
  'BLAKE-256',
  'DaggerHashimoto',
  'CryptoNight-Custom',
  'CryptoNightLiteV1',
  'X16S',
  'SkunkHash',
  'BLAKE2s',
  'CryptoNightHeavy',
  'Tribus',
  'X15',
  'Scrypt-N',
  'Scrypt-ChaCha',
  'X14',
  'Keccak',
  'PHI1612',
  'Argon2',
  'Lyra2REv3',
  'Yescrypt',
  'CryptoNightFast',
  'PHI2',
  'YescryptR32',
  'Argon2d',
  'Equihash 192_7',
  'Lyra2z330',
  'YescryptR16',
  'Shabal256',
  'Allium',
  'YesPoWer',
  'X21S',
  'Fresh',
  'Pascal (Random Hash)',
  'BLAKE2b',
  'X11Binarium',
  'VerusHash 2.0',
  'MTP',
  'HEX',
  'Tensority',
  'SoftCrypton',
  'CryptoHello',
  'A5A v2',
  'X11Evo',
  'Argon2i',
  'BTHash',
  'Polytimos',
  'TimeTravel',
  'Prime Constellation',
  'Aergo',
  'pGap',
  'MD5',
  'SonoA',
  'Balloon Hashing',
  'SHA-256T',
  'ProgPoW',
  'X11Spread',
  'Scrypt²',
  'Exosis',
  'LBK3',
  'TimeTravel10',
  'Lyra2Zoin',
  'CryptoNightLite',
  'UBQhash',
  'LBRY',
  'BCD',
  'SHA-224',
  'Cunningham chains',
  'Dcrypt',
  'Equihash 210_9',
  'Grøstl-512',
  'Lyra2RE',
  'DEDAL',
  'Lyra2vc0ban',
  'Prime Six',
];
