/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import date from './date';
import metadata from './metadata';

/**
 * The locale data for the `bn_BD` locale.
 *
 * - Language: Bengali (Bangladesh)
 * - Endonym: বাংলা (বাংলাদেশ)
 */
const bn_BD: LocaleDefinition = {
  date,
  metadata,
};

export default bn_BD;
