/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import color from './color';
import commerce from './commerce';
import company from './company';
import date from './date';
import internet from './internet';
import location from './location';
import lorem from './lorem';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';

const pt_BR: LocaleDefinition = {
  color,
  commerce,
  company,
  date,
  internet,
  location,
  lorem,
  metadata,
  person,
  phone_number,
};

export default pt_BR;
