/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { ShoesDefinitions } from '../../..';
import brand from './brand';
import material from './material';
import productType from './productType';
import size from './size';
import style from './style';

const shoes: ShoesDefinitions = {
  brand,
  material,
  productType,
  size,
  style,
};

export default shoes;
