/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: ['duminică', 'joi', 'luni', 'marți', 'miercuri', 'sâmbătă', 'vineri'],
  abbr: ['Dum', 'Joi', 'Lun', 'Mar', 'Mie', 'Sâm', 'Vin'],
};
