/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { ZodiacDefinitions } from '../../..';
import sign from './sign';

const zodiac: ZodiacDefinitions = {
  sign,
};

export default zodiac;
