/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import credit_card_expiry_dates from './credit_card_expiry_dates';
import credit_card_numbers from './credit_card_numbers';
import credit_card_types from './credit_card_types';

const business = {
  credit_card_expiry_dates,
  credit_card_numbers,
  credit_card_types,
};

export default business;
