/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinitions } from '../../..';
import building_number from './building_number';
import city_pattern from './city_pattern';
import city_prefix from './city_prefix';
import country from './country';
import default_country from './default_country';
import postcode from './postcode';
import province from './province';
import secondary_address from './secondary_address';
import state from './state';
import state_abbr from './state_abbr';
import street_address from './street_address';
import street_pattern from './street_pattern';
import street_suffix from './street_suffix';

const location: LocationDefinitions = {
  building_number,
  city_pattern,
  city_prefix,
  country,
  default_country,
  postcode,
  province,
  secondary_address,
  state,
  state_abbr,
  street_address,
  street_pattern,
  street_suffix,
};

export default location;
