/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PhoneNumberDefinitions } from '../../..';
import formats from './formats';

const phone_number: PhoneNumberDefinitions = {
  formats,
};

export default phone_number;
