/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AnimalDefinitions } from '../../..';
import horse from './horse';

const animal: AnimalDefinitions = {
  horse,
};

export default animal;
