/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import date from './date';
import metadata from './metadata';

/**
 * The locale data for the `ta_IN` locale.
 *
 * - Language: Tamil (India)
 * - Endonym: தமிழ் (இந்தியா)
 */
const ta_IN: LocaleDefinition = {
  date,
  metadata,
};

export default ta_IN;
