/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinitions } from '../../..';
import city from './city';
import city_name from './city_name';
import default_country from './default_country';
import postcode from './postcode';
import state from './state';
import state_abbr from './state_abbr';
import street_pattern from './street_pattern';

const location: LocationDefinitions = {
  city,
  city_name,
  default_country,
  postcode,
  state,
  state_abbr,
  street_pattern,
};

export default location;
