/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import color from './color';
import database from './database';
import hacker from './hacker';
import internet from './internet';
import location from './location';
import system from './system';

const base: LocaleDefinition = {
  title: 'Base',
  color,
  database,
  hacker,
  internet,
  location,
  system,
};

export default base;
