/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PersonDefinition } from '../../..';
import last_name from './last_name';
import last_name_patterns from './last_name_patterns';
import name_ from './name';

const person: PersonDefinition = {
  last_name,
  last_name_patterns,
  name: name_,
};

export default person;
