/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PhoneNumberDefinitions } from '../../..';
import area_code from './area_code';
import exchange_code from './exchange_code';

const phone_number: PhoneNumberDefinitions = {
  area_code,
  exchange_code,
};

export default phone_number;
