/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'недеља',
    'петак',
    'понедељак',
    'среда',
    'субота',
    'уторак',
    'четвртак',
  ],
  abbr: ['нед', 'пет', 'пон', 'сре', 'суб', 'уто', 'чет'],
};
