/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import cell_phone from './cell_phone';
import color from './color';
import commerce from './commerce';
import company from './company';
import internet from './internet';
import location from './location';
import lorem from './lorem';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';
import team from './team';

/**
 * The locale data for the `es_MX` locale.
 *
 * - Language: Spanish (Mexico)
 * - Endonym: Español (México)
 */
const es_MX: LocaleDefinition = {
  cell_phone,
  color,
  commerce,
  company,
  internet,
  location,
  lorem,
  metadata,
  person,
  phone_number,
  team,
};

export default es_MX;
