/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import address from './address';
import cell_phone from './cell_phone';
import color from './color';
import commerce from './commerce';
import company from './company';
import internet from './internet';
import lorem from './lorem';
import name_ from './name';
import phone_number from './phone_number';
import team from './team';

const es_MX: LocaleDefinition = {
  title: 'Spanish (Mexico)',
  separator: ' & ',
  address,
  cell_phone,
  color,
  commerce,
  company,
  internet,
  lorem,
  name: name_,
  phone_number,
  team,
};

export default es_MX;
