/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AddressDefinitions } from '../../..';
import county from './county';
import default_country from './default_country';

const address: AddressDefinitions = {
  county,
  default_country,
};

export default address;
