/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PersonDefinitions } from '../../..';
<<<<<<< HEAD
import female_prefix from './female_prefix';
import first_name from './first_name';
import last_name from './last_name';
import male_prefix from './male_prefix';
=======
import female_first_name from './female_first_name';
import first_name from './first_name';
import last_name from './last_name';
import male_first_name from './male_first_name';
>>>>>>> next
import name_ from './name';
import prefix from './prefix';
import title from './title';

const person: PersonDefinitions = {
<<<<<<< HEAD
  female_prefix,
  first_name,
  last_name,
  male_prefix,
=======
  female_first_name,
  first_name,
  last_name,
  male_first_name,
>>>>>>> next
  name: name_,
  prefix,
  title,
};

export default person;
