/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import author from './author';
import name_ from './name';
import version from './version';

const app = {
  author,
  name: name_,
  version,
};

export default app;
