/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { RecipeDefinitions } from '../../..';
import category from './category';
import description from './description';
import difficulty from './difficulty';
import doses from './doses';
import ingredients from './ingredients';
import name_ from './name';
import preparation from './preparation';

const recipe: RecipeDefinitions = {
  category,
  description,
  difficulty,
  doses,
  ingredients,
  name: name_,
  preparation,
};

export default recipe;
