export default [
  "Dissolvez la levure de bière dans un peu d'eau tiède, environ 10 ml. Ajoutez le sel à la farine et mélangez. Versez l'eau dans un grand récipient, ajoutez la levure dissoute, l'huile et la farine petit à petit, tout en d'autre part tu commences à pétrir. Etc...",
  "Tout d'abord, mettez la farine, le sel et la levure dans un bol en veillant à mettre le sel et la levure sur les côtés opposés. Ajouter l'eau et l'huile d'olive et mélanger pour former une pâte rugueuse. Façonner la pâte en boule puis pétrir sur une surface légèrement farinée pendant environ 10 minutes jusqu'à ce que la pâte soit lisse et élastique. Etc...",
  "Ajouter la levure à l'eau tiède avec ½ cuillère à café de sucre pendant 5 minutes. Mélanger la farine et le sel dans un grand bol à mélanger. Faire un puits au centre et ajouter le mélange eau/levure tout en mélangeant la pâte avec une cuillère jusqu'à ce que vous avoir obtenu une pâte. Si elle est trop collante vous pouvez rajouter petit à petit un peu de farine. Etc...",
  "Pour la pâte, mélanger l'huile, la levure et 2 cuillères à soupe d'eau tiède dans un bol pour dissoudre la levure. Mélanger la farine et 1 cuillère à soupe de sel dans un bol et faire un puits au centre. Ajouter 680 ml d'eau et le mélange de levure dans le puits et mélanger avec les mains pour former une pâte collante (3-4 minutes). Couvrir d'une pellicule plastique pour hydrater (15 minutes), puis pétrir sur un banc légèrement fariné jusqu'à consistance lisse (2 minutes). Remettre dans un bol, couvrir d'une pellicule plastique et réfrigérer pour fermenter (24 heures). Etc...",
  "Émincer les oignons en fines rondelles. Hacher finement la carotte, le céleri et la gousse d'ail. Dans une grande casserole (8 pintes), chauffer le saindoux, les oignons et la pancetta finement hachée. Cuire pendant 5 minutes, en remuant, jusqu'à tendreté; puis ajouter la carotte, l'ail et le céleri et laisser mijoter pendant 3-4 minutes. Etc...",
  "Une fois que vous avez nettoyé vos calamars (vous pouvez demander au poissonnier de le faire pour vous), coupez-les en rondelles et faites-les revenir avec de l'ail et un peu d'huile. Ajouter le vin blanc et le concentré de tomate, et une fois l'alcool évaporé, incorporer les tomates et cuire 10 minutes à feu doux.",
  "Faites chauffer 3 cuillères à soupe d'huile d'olive extra vierge dans une grande sauteuse à feu moyen. Ajouter l'oignon, le céleri et l'ail si désiré. Cuire, environ 2 minutes, en ajoutant 1-2 cuillères à soupe d'eau si nécessaire.",
  "Faites chauffer une grande casserole avec de l'huile d'olive, ajoutez les champignons et l'oignon et faites cuire en remuant souvent pendant 7 à 8 minutes, en ajoutant un peu de bouillon si nécessaire. Transférer les légumes dans un récipient et remettre la casserole à feu doux-moyen. Ajouter le riz et le faire griller 1 minute en remuant souvent. Ajouter le vin et laisser évaporer.",
  "Mélangez simplement l'eau, le jus de citron et le sucre dans un grand bol, jusqu'à ce que le sucre soit dissous. Transférer le mélange dans un grand récipient en métal (un moule à pain fonctionnerait parfaitement), couvrir et placer au congélateur pendant une demi-heure. Utilisez une cuillère en bois pour remuer vigoureusement le mélange afin de casser les éventuels cristaux de glace, puis remettez-le au congélateur. Répétez toutes les 30 minutes en remuant 2-3 fois, ou jusqu'à ce que votre granité ait atteint une texture glacée veloutée.",
  "Cassez les biscuits en morceaux avec vos mains ou placez-les dans un sac de congélation et cassez-les délicatement avec un rouleau à pâtisserie. Ne les écrasez pas. Fouetter le beurre ramolli avec le sucre jusqu'à ce qu'il soit pâle et mousseux, environ 3 minutes.",
  "Portez à ébullition une grande casserole d'eau légèrement salée, puis faites cuire les pâtes al dente, environ 8 minutes pour les linguines. Égouttez les pâtes et transférez-les dans la poêle avec les autres ingrédients. Faire chauffer une poêle à feu moyen, ajouter l'huile d'olive, puis les morceaux de saumon, l'ail et les épinards et faire sauter pendant 2 minutes.",
];
