/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { BookDefinition } from '../../../definitions';
import format from './format';

const book: BookDefinition = {
  format,
};

export default book;
