/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { TobaccoDefinitions } from '../../..';
import brand from './brand';
import type_ from './type';

const tobacco: TobaccoDefinitions = {
  brand,
  type: type_,
};

export default tobacco;
