export default [
  "La 'Monflowers' è una birra Blanche dal timbro molto rinfrescante e fresco, ispirata alla tradizione belga e ottenuta da un mix di spezie e fiori del Monferrato, malto piemontese e grano. Al naso racconta delicate note di grano, cereali e grano, sorretto da sentori di miele portati dal malto italiano. Il sorso è leggero, sottile, con una bevuta rinfrescante e molto vellutata",
  'Eporedian Pale Ale è una birra del Canavese dal tipico e gradevole tono amaro e agrumato, con uno sviluppo al palato dinamico e molto intrigante. Al naso è caratterizzato da intensi aromi erbacei, con sensazioni di pompelmo e luppolo fresco. Sviluppa un sorso amaro e meravigliosamente progressivo, senza essere invadente, ma estremamente dissetante e beverino',
  "'Che Belle Gose' è una deliziosa birra Gose dal gusto salato realizzata dal Birrifcio Civale in collaborazione con il Birrificio Croce di Malto e Montegioco. Si ispira ai modelli tedeschi di Lipsia che prevedono l'aggiunta di sale bianco e rosa nelle fasi di produzione è letteralmente una birra salata dal profilo rinfrescante, fresco e marino, arricchita da aromi di coriandolo, agrumi, grano e fiori bianchi",
  "La birra 'Audace' di Via dei Birrai 32 è una Belgian strong Ale dal carattere deciso e dalle sensazioni agrumate date dall'aggiunta di scorza d'arancia bollente. Al naso regala caldi aromi di tarassaco e camomilla, pesca sciroppata e mandorla e in bocca è pieno e piacevolmente citrino, senza accenti amari, molto morbido",
  "L'Ippa di Baladin è l'interpretazione italiana della famosa Indian Pale Ale secondo lo stile di Teo Musso, pioniere nel mondo delle birre artigianali. Prodotto con luppoli coltivati ​​su suolo italiano, brilla nel bicchiere con il suo manto ambrato caratterizzato da una piacevole schiuma bianca. Al naso è caratterizzato da intense note erbacee, amare, agrumate e leggere sensazioni di mango. Al sorso è beverino, leggero e pulito, con lunghi sentori di luppoloL'Ippa di Baladin è l'interpretazione italiana della famosa Indian Pale Ale secondo lo stile di Teo Musso, pioniere nel mondo delle birre artigianali. Prodotto con luppoli coltivati ​​su suolo italiano, brilla nel bicchiere con il suo manto ambrato caratterizzato da una piacevole schiuma bianca. Al naso è caratterizzato da intense note erbacee, amare, agrumate e leggere sensazioni di mango. Al sorso è beverino, leggero e pulito, con lunghi sentori di luppoli",
  'Lago Nero è una birra Stout ispirata al modello irlandese e caratterizzata da forti note affumicate. Rivela un profilo olfattivo tostato e speziato, con note di speck affumicato, cacao amaro, chicchi di caffè e una fine luppolatura. Al sorso mostra la classica nota di malto tostato con un corpo scorrevole e piacevolmente amaro',
  'Full Moon del birrificio Triporteur è una birra scura ispirata al tipico Quadrupel del Belgio, esaltata da un riposo in rovere del Belgio tostato. Al naso si apre ad aromi intensi e caldi di mela candita, caramello e liquirizia con sfumature tostate e legnose. Il sorso è ricco e generoso, ben equilibrato tra tenore zuccherino e sfumatura fruttata, rotondo e molto persistente',
  "'Admiral' di 32 - Birrificio Via dei Birrai è una birra ad alta fermentazione ambrata dal colore scuro e sfumature rubino con una schiuma beige compatta e persistente. Al naso sprigiona aromi tipici di malto e caramello con ritorni di lievito e tostatura. In bocca è pieno, con una bella freschezza e un piacevole finale erbaceo e amaro dato dal luppolo Admiral utilizzato",
  "La Birra 'Strike' di BAV è una IPA italiana prodotta con rifermentazione in bottiglia e con un alto valore IBU. È caratterizzato da profumi fragranti e agrumati, con sfumature di frutta esotica, erbe e lieviti. Al gusto è fresco, ben strutturato e leggermente fruttato, di facile beva nonostante gli intensi e lunghi aromi di luppoli amaro",
  "IPA di Brigà è un'interpretazione piemontese dello stile di birra più amato (e abusato) che esista: l'India Pale Ale. È una birra ad alta fermentazione, ottenuta da pura acqua Pian della Mussa e materie prime coltivate in agricoltura biologica. Ambrato dal timbro tropicale, erbaceo e agrumato, chiude con una punta amarognola tipica dello stile",
  "La 'Ghisa' del birrificio Lambrate è una birra scura in stile Smoked Stout che colpisce per il suo naturale equilibrio tra sentori affumicati, tipici di questa categoria, e scorrevole bevibilità. Al naso si apre su aromi di caffè, cappuccino, maron glacé e castagne con un sorso denso e morbido, vivace e delicato ricco di sfumature affumicate, caffè e toffe che ricordano perfettamente gli aromi olfattivi",
  "'Vincent Vega' è il protagonista del film cult Pulp Fiction a cui Retorto ha dedicato questa birra ambrata ispirata alle triple dell'abbazia. Dal cappello di spuma particolarmente cremoso e persistente, si rivela in un manto fulvo, color caramello con sentori agrumati dovuti all'arancia rossa e al pompelmo rosa. Dona sensazioni avvolgenti e piene, senza essere stucchevole, con un finale secco particolarmente appetitoso",
];
