/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CigaretteDefinitions } from '../../..';
import brand from './brand';
import type_ from './type';

const cigarette: CigaretteDefinitions = {
  brand,
  type: type_,
};

export default cigarette;
