/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import color from './color';
import commerce from './commerce';
import company from './company';
import date from './date';
import hacker from './hacker';
import internet from './internet';
import location from './location';
import lorem from './lorem';
import person from './person';
import phone from './phone';

const nl: LocaleDefinition = {
  title: 'Dutch',
  color,
  commerce,
  company,
  date,
  hacker,
  internet,
  location,
  lorem,
  person,
  phone,
};

export default nl;
