/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import address from './address';
import color from './color';
import commerce from './commerce';
import company from './company';
import date from './date';
import hacker from './hacker';
import internet from './internet';
import lorem from './lorem';
import name_ from './name';
import phone_number from './phone_number';

const nl: LocaleDefinition = {
  title: 'Dutch',
  address,
  color,
  commerce,
  company,
  date,
  hacker,
  internet,
  lorem,
  person: name_,
  phone_number,
};

export default nl;
