export default [
  'Conjunto de 250 piezas para construir tus lindos corazones: ¡combina colores y números para crear tu propia composición de mosaico! ¡Sigue el patrón y combina los colores correctamente para crear lindos corazones con el rompecabezas de números Plus-Plus!',
  'Construye un patio de comidas para los personajes de Eevee y Lucario. Este conjunto se combina con otros conjuntos de Adventure Builder para crear un mundo Pokémon aún más grande lleno de detalles auténticos. Descubre Pikachu Beach Fun, Bulbasaur Forest u otros juegos aún más grandes, cada uno se vende por separado. Los juguetes de construcción MEGA Pokémon están diseñados para niños mayores de 7 años',
  'Construye un puesto de refrescos para los personajes de Eevee y Lucario. Este conjunto se combina con otros conjuntos de Adventure Builder para crear un mundo Pokémon aún más grande lleno de detalles auténticos. Descubre Pikachu Beach Fun, Bulbasaur Forest u otros juegos aún más grandes, cada uno se vende por separado. Los juguetes de construcción MEGA Pokémon están diseñados para niños mayores de 7',
  'Una motocicleta: cinco creaciones. Un kit de modelo divertido y emocionante para hacer con este conjunto Meccano. Los niños pueden divertirse montando y volviendo a montar motocicletas y coches deportivos. Mientras usa este S.T.E.A.M. kit de construcción, aprenderán los principios de la ciencia, la tecnología, la ingeniería, el arte y las matemáticas.',
  'Este fantástico modelo de coche de carreras LEGO Technic Formula E® Porsche 99X Electric (42137) con sistema de tracción trasera es el regalo perfecto para todos los fans de Formula E® y Porsche a partir de 9 años. Con esta maqueta del famoso Porsche, los niños pueden sumergirse en una experiencia de construcción inmersiva, recreando todos los detalles del coche real y reviviendo todas las emociones de la carrera real, gracias a los 2 motores pull-back y la app de realidad LEGO Technic . aumentada (AR).',
  'Dale a los jóvenes fanáticos de 9 años en adelante el regalo perfecto: la figura de acción de Iron Man. Con 24 cm de altura, la figura LEGO Marvel Iron Man (76206) está lista para brindar a los niños horas y horas de emocionantes aventuras de superhéroes con el tema de Marvel. Inspirada en la película Los Vengadores: La era de Ultrón, esta reproducción realista está completamente articulada y lista para embarcarse en audaces misiones contra los villanos.',
  'Lleva a los niños amantes de los animales marinos a un viaje de fantasía al fondo del océano con el set LEGO DUPLO Ocean Animals (10972). Un juego que ofrece infinitas posibilidades para el desarrollo de los niños en edad preescolar, gracias a una alfombra de juego tridimensional que representa un fondo marino y 4 dulces animales de juguete.',
  'Los jóvenes brujos, magos y muggles a partir de 8 años pueden vivir fantásticas aventuras con este set LEGO Harry Potter Hogwarts: Oficina de Dumbledore (76402) de varios niveles, que presenta diferentes áreas y detalles auténticos de la famosa saga cinematográfica. Jóvenes fanáticos de los juegos de Harry Potter encontrarás magia y aventura en cada habitación de este castillo de juguete.',
  'Descubre divertidos juguetes creativos para niños en el set de construcción LEGO Creator Creatures of the Forest Fantasy 3in1 (31125). Este juego de animales de juguete para niños a partir de 7 años te permite crear muchas historias fantásticas en el bosque. Uno de los 3 modelos incluidos es un búho de juguete sabio con cabeza, cola, alas y plumas articuladas que le lee un libro de cuentos a un erizo.',
  'Establo para acomodar hasta 3 ponis y gran área al aire libre cercada para los primeros paseos. La planta superior alberga provisiones y equipos para el cuidado de los caballos.',
  'El Batman original en escala de 30 centímetros. Con 11 puntos de articulación es posible moverlo y posicionarlo a voluntad en poses heroicas. Con colores y decoraciones realistas, también tiene una capa de tela. Los niños pueden disfrutar reviviendo las aventuras de Gotham City con el héroe más icónico de la historia.',
  '¡Los dinosaurios han regresado a la tierra! Vive grandes aventuras con este juego - Luces y sonidos - Piezas móviles - Disponible en 2 modelos',
];
