export default [
  'The cover page is ten years old, the cover page eight, the deposit over six years. The harmonious and rich flavors of Davidoff Special 53 - Capa Dominicana go perfectly with a Dominican rum that has sweet and spicy notes. The tobacco varieties surprise with distinctive notes of wood, coffee and cocoa. Rum and cigar complement each other, the sweetness of the rum underlines the cigar positively and the cigar gives the rum creaminess.',
  'At the request of many of our customers who miss their Davidoff No.1 or Cohiba Lanceros our managing director and cigar expert Mirko Pettene has created a Lancero format for our Royales Limited Edition 2021. This Lancero is exclusively rolled from 8-year-old tobacco in Royales premium cigar quality and comes in a limited edition of only 300 beautiful black boxes of 10. An elegant cigar for connoisseurs and bon vivants.',
  'The words “refined power” shine through this cigar like the gold tubes that encase them. A true powerhouse backed with extraordinary flavor.',
  'The story of the Horacio brand begins in Costa Rica, where it was developed with great dedication by three cigar lovers in 2008. Today, the premium cigars are produced in Nicaragua, which is known for its extremely delicate blends. The climatic conditions there are ideal for high-quality tobacco production.',
  "Hamburg, July 2019. As a thank you for the exceptional and long-standing collaboration with Germany's best Davidoff vendors, Davidoff launch a strictly limited Davidoff ***** Exclusive Edition. The fine cigar edition is limited to 500 cases and only availablle at David five-star ambassadors and flagship stores in Germany.",
  'We have known Rocky for many years and simply love his cigars. In record time, Rocky has become one of the greatest cigar blenders of the age. We and countless aficionados around the world believe that he has long since become a genuine master at his craft. Further proof of this, if any more were needed, is his new range, which we would like to present to you today. The Disciple will be available in four formats on the German market: Robusto, Toro, Bala (Figurado) and Sixty.',
  'With the Melanio Diadema series V, Oliva is launching a real limitada: it is a slightly different blend compared to the standard range of the Melanio series V and also one of the first round shapes within the otherwise "boxpressed" series.',
  'In September 2020, the "EPC Pledge" was released in two vitolas, a Robusto called "Prequel" and the "Sojourn", a Toro. That year, the range developed into the hottest must-have of the cigar world. The Cigar Aficionado agreed and, just a few months later, awarded it "Cigar of the Year" with an unmatched rating of 98 points. ',
  'The VILLIGER LA MERIDIANA are strong puros from Nicaragua, but thanks to the use of a milder wrapper they offer an amazingly balanced pleasure. The typical chocolaty coffee notes are earthy and deep, while being softly rounded and full-bodied. A beautiful, complex variety of aromas that is powerful but never intrusive and pleasantly surprises lovers of these puros with a wide range of formats.',
];
