/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AnimalDefinition } from '../../..';
import bear from './bear';
import bird from './bird';
import cat from './cat';
import pet_name from './pet_name';
import rabbit from './rabbit';

const animal: AnimalDefinition = {
  bear,
  bird,
  cat,
  pet_name,
  rabbit,
};

export default animal;
