/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'April',
    'August',
    'December',
    'February',
    'January',
    'July',
    'June',
    'March',
    'May',
    'November',
    'October',
    'September',
  ],
  abbr: [
    'Apr',
    'Aug',
    'Dec',
    'Feb',
    'Jan',
    'July',
    'June',
    'Mar',
    'May',
    'Nov',
    'Oct',
    'Sept',
  ],
};
