export default [
  'Set di 250 pezzi per costruire i tuoi cuoricini: abbina colori e numeri per creare la tua composizione di mosaico! Segui lo schema e abbina i colori correttamente per creare cuori carini con il puzzle Plus-Plus in base al numero!',
  'Costruisci una food court per i personaggi di Eevee e Lucario. Questo set si combina con altri set di Adventure Builder per creare un mondo Pokémon ancora più grande, pieno di dettagli autentici. Scopri Pikachu Beach Fun, Bulbasaur Forest o altri set ancora più grandi, ciascuno venduto separatamente. I giocattoli costruibili MEGA Pokémon sono progettati per bambini di età superiore ai 7 anni.',
  'Costruisci un punto di ristoro per i personaggi di Eevee e Lucario. Questo set si combina con altri set di Adventure Builder per creare un mondo Pokémon ancora più grande, pieno di dettagli autentici. Scopri Pikachu Beach Fun, Bulbasaur Forest o altri set ancora più grandi, ciascuno venduto separatamente. I giocattoli costruibili MEGA Pokémon sono progettati per bambini di età superiore ai 7',
  "Una moto: cinque creazioni. Un kit modello divertente ed emozionante da realizzare con questo set Meccano. I bambini possono divertirsi ad assemblare e rimontare moto e auto sportive. Durante l'utilizzo di questo S.T.E.A.M. kit di costruzione, impareranno i principi della scienza, della tecnologia, dell'ingegneria, dell'arte e della matematica.",
  "Questo fantastico modello di auto da corsa LEGO Technic Formula E® Porsche 99X elettrica (42137) con sistema di ritiro è il regalo perfetto per tutti i fan della Formula E® e Porsche dai 9 anni in su. Con questo modello della famosa Porsche, i bambini possono immergersi in un'esperienza costruttiva immersiva, ricreando tutti i dettagli dell'auto reale e rivivendo tutte le emozioni della gara reale, grazie ai 2 motori pull-back e all'app di realtà LEGO Technic . aumentata (AR).",
  "Fai ai giovani fan dai 9 anni in su il regalo perfetto: l'action figure di Iron Man. Alta 24 cm, la figura LEGO Marvel Iron Man (76206) è pronta per regalare ai bambini ore e ore di emozionanti avventure a tema Marvel Supereroi. Ispirata al film Avengers: Age of Ultron, questa riproduzione realistica è completamente articolata e pronta per intraprendere audaci missioni contro i cattivi.",
  "Porta i bambini che amano gli animali marini in un viaggio fantastico sul fondo dell'oceano con il set LEGO DUPLO Ocean Animals (10972). Un playset che offre infinite possibilità per lo sviluppo dei bambini in età prescolare, grazie a un tappetino da gioco tridimensionale che raffigura un fondale marino e 4 dolcissimi animaletti.",
  "Giovani streghe, maghi e babbani dagli 8 anni in su possono vivere fantastiche avventure con questo set LEGO Harry Potter Hogwarts: L'ufficio di Silente (76402) multi-livello, con aree diverse e dettagli autentici della famosa saga cinematografica. Giovani fan dei giochi di Harry Potter troverà magia e avventura in ogni stanza di questo castello giocattolo.",
  'Scopri divertenti giocattoli creativi per bambini nel set costruibile LEGO Creator Creatures of the Forest Fantasy 3in1 (31125). Questo set di animali giocattolo per bambini dai 7 anni in su ti permette di creare tante fantastiche storie nel bosco. Uno dei 3 modelli inclusi è un saggio gufo giocattolo con testa, coda, ali e piume snodabili, che legge un libro di fiabe a un riccio.',
  'Stabile per ospitare fino a 3 pony e ampio spazio esterno recintato per le prime passeggiate. Il piano superiore ospita provviste e attrezzature per la cura dei cavalli.',
  "L'originale Batman in scala 30 centimetri. Con 11 punti di articolazione è possibile spostarlo e posizionarlo a piacimento in pose eroiche. Con colori e decorazioni realistici, ha anche un mantello di stoffa. I bambini possono divertirsi rivivendo le avventure di Gotham City con l'eroe più iconico di sempre.",
  'I dinosauri sono tornati sulla terra! Vivi grandi avventure con questo playset - Luci e suoni - Parti mobili - Disponibile in 2 modelli',
];
