/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'agosto',
    'aprile',
    'dicembre',
    'febbraio',
    'gennaio',
    'giugno',
    'luglio',
    'maggio',
    'marzo',
    'novembre',
    'ottobre',
    'settembre',
  ],
  abbr: [
    'ago',
    'apr',
    'dic',
    'feb',
    'gen',
    'giu',
    'lug',
    'mag',
    'mar',
    'nov',
    'ott',
    'set',
  ],
};
