/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'วันจันทร์',
    'วันพฤหัสบดี',
    'วันพุธ',
    'วันศุกร์',
    'วันอังคาร',
    'วันอาทิตย์',
    'วันเสาร์',
  ],
  abbr: ['จ.', 'พ.', 'พฤ.', 'ศ.', 'ส.', 'อ.', 'อา.'],
};
