/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinition } from '../../..';
import building_number from './building_number';
import city_name from './city_name';
import city_pattern from './city_pattern';
import county from './county';
import postcode from './postcode';
import secondary_address from './secondary_address';
import state from './state';
import state_abbr from './state_abbr';
import street_address from './street_address';
import street_name from './street_name';
import street_pattern from './street_pattern';
import street_suffix from './street_suffix';

const location: LocationDefinition = {
  building_number,
  city_name,
  city_pattern,
  county,
  postcode,
  secondary_address,
  state,
  state_abbr,
  street_address,
  street_name,
  street_pattern,
  street_suffix,
};

export default location;
