/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'вторник',
    'недела',
    'петок',
    'понеделник',
    'сабота',
    'среда',
    'четврток',
  ],
  abbr: ['вто.', 'нед.', 'пет.', 'пон.', 'саб.', 'сре.', 'чет.'],
};
