/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CompanyDefinitions } from '../../..';
import adjective from './adjective';
import buzz_adjective from './buzz_adjective';
import buzz_noun from './buzz_noun';
import buzz_verb from './buzz_verb';
import descriptor from './descriptor';
import name_patterns from './name_patterns';
import noun from './noun';
import suffix from './suffix';

const company: CompanyDefinitions = {
  adjective,
  buzz_adjective,
  buzz_noun,
  buzz_verb,
  descriptor,
  name_patterns,
  noun,
  suffix,
};

export default company;
