/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { NameDefinitions } from '../../..';
import first_name from './first_name';
import last_name from './last_name';
import name_ from './name';
import nobility_title_prefix from './nobility_title_prefix';
import prefix from './prefix';

const name: NameDefinitions = {
  first_name,
  last_name,
  name: name_,
  nobility_title_prefix,
  prefix,
};

export default name;
