/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import color from './color';
import commerce from './commerce';
import date from './date';
import location from './location';
import metadata from './metadata';
import person from './person';

const uz_UZ_latin: LocaleDefinition = {
  color,
  commerce,
  date,
  location,
  metadata,
  person,
};

export default uz_UZ_latin;
