/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinition } from '../../..';
import city_pattern from './city_pattern';
import county from './county';
import default_country from './default_country';
import street_pattern from './street_pattern';

const location: LocationDefinition = {
  city_pattern,
  county,
  default_country,
  street_pattern,
};

export default location;
