/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinition } from '../../..';
import city_name from './city_name';
import city_pattern from './city_pattern';
import street_pattern from './street_pattern';

const location: LocationDefinition = {
  city_name,
  city_pattern,
  street_pattern,
};

export default location;
