/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AddressDefinitions } from '../../..';
import building_number from './building_number';
import city from './city';
import country from './country';
import default_country from './default_country';
import postcode from './postcode';
import street_address from './street_address';
import street_name from './street_name';
import street_root from './street_root';

const address = {
  building_number,
  city,
  country,
  default_country,
  postcode,
  street_address,
  street_name,
  street_root,
} as Partial<AddressDefinitions>;

export default address;
