/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinition } from '../../..';
import city_pattern from './city_pattern';
import city_prefix from './city_prefix';
import city_suffix from './city_suffix';
import country from './country';
import direction from './direction';
import secondary_address from './secondary_address';
import street_address from './street_address';
import street_pattern from './street_pattern';
import street_prefix from './street_prefix';
import street_suffix from './street_suffix';

const location: LocationDefinition = {
  city_pattern,
  city_prefix,
  city_suffix,
  country,
  direction,
  secondary_address,
  street_address,
  street_pattern,
  street_prefix,
  street_suffix,
};

export default location;
