/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { MonumentDefinitions } from '../../..';
import description from './description';
import name_ from './name';

const monument: MonumentDefinitions = {
  description,
  name: name_,
};

export default monument;
