export const ALLOWED_MODULES = new Set([
  'AirlineModule',
  'AnimalModule',
  'BookModule',
  'ColorModule',
  'CommerceModule',
  'CompanyModule',
  'DatabaseModule',
  'DatatypeModule',
  'DateModule',
  'FoodModule',
  'HelpersModule',
  'NumberModule',
  'PersonModule',
  'StringModule',
]);
