/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { FlightsDefinitions } from '../../..';
import airline from './airline';
import class_ from './class_';
import number from './number';
import type_ from './type';

const flights: FlightsDefinitions = {
  airline,
  class_,
  number,
  type: type_,
};

export default flights;
