/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AddressDefinitions } from '../../..';
import default_country from './default_country';
import postcode_by_state from './postcode_by_state';

const address = {
  default_country,
  postcode_by_state,
} as Partial<AddressDefinitions>;

export default address;
