/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinition } from '../../../definitions';
import country_code from './country_code';
import time_zone from './time_zone';

const location: LocationDefinition = {
  country_code,
  time_zone,
};

export default location;
