/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import internet from './internet';
import location from './location';
import metadata from './metadata';
import person from './person';

/**
 * The locale data for the `fr_SN` locale.
 *
 * - Language: French (Senegal)
 * - Endonym: Français (Sénégal)
 */
const fr_SN: LocaleDefinition = {
  internet,
  location,
  metadata,
  person,
};

export default fr_SN;
