/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'april',
    'august',
    'december',
    'februar',
    'januar',
    'juli',
    'juni',
    'maj',
    'marts',
    'november',
    'oktober',
    'september',
  ],
  abbr: [
    'apr.',
    'aug.',
    'dec.',
    'feb.',
    'jan.',
    'jul.',
    'jun.',
    'maj',
    'mar.',
    'nov.',
    'okt.',
    'sep.',
  ],
};
