/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LiquorDefinitions } from '../../..';
import brand from './brand';
import category from './category';
import description from './description';
import name_ from './name';
import size from './size';

const liquor: LiquorDefinitions = {
  brand,
  category,
  description,
  name: name_,
  size,
};

export default liquor;
