/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import person from './person';
import phone_number from './phone_number';

const zh_TW: LocaleDefinition = {
  title: 'Chinese (Taiwan)',
  location,
  person,
  phone_number,
};

export default zh_TW;
