/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import color from './color';
import date from './date';
import location from './location';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';

const zh_TW: LocaleDefinition = {
  color,
  date,
  location,
  metadata,
  person,
  phone_number,
};

export default zh_TW;
