export default [
  "The 'Monflowers' is a Blanche beer with a very refreshing and fresh timbre, inspired by the Belgian tradition and obtained from a mix of spices and Monferrato flowers, Piedmontese malt and wheat. The nose tells delicate notes of wheat, cereals and wheat, supported by hints of honey brought by Italian malt. The sip is light, thin, with a refreshing and very smooth drink",
  'Eporedian Pale Ale is a beer from Canavese with a typical and pleasant bitter and citrusy tone, with a dynamic and very intriguing development on the palate. The nose is marked by intense herbaceous aromas, with sensations of grapefruit and fresh hops. It develops a bitter and beautifully progressive sip, without being invasive, but extremely thirst-quenching and drinkable',
  "'Che Belle Gose' is a delicious Gose beer with a salty taste made by the Birrifcio Civale in collaboration with the Croce di Malto and Montegioco Brewery. It is inspired by the German models of Leipzig which provide for the addition of white and pink salt in the production phases. It is literally a salt beer with a refreshing, fresh and marine profile, enriched with aromas of coriander, citrus fruits, wheat and white flowers",
  'The "Audace" beer of 32 Via dei Birrai is a Belgian strong Ale with a strong character and citrus sensations given by the addition of boiling orange zest. The nose gives warm aromas of dandelion and chamomile, peach in syrup and almond and in the mouth it is full and pleasantly citrine, without bitter accents, very smooth',
  'The Ippa di Baladin is the Italian interpretation of the famous Indian Pale Ale according to Teo Musso style, a pioneer in the world of craft beers. Made with hops grown on Italian soil, it shines in the glass with its amber mantle characterized by a pleasant white foam. The nose is characterized by intense herbaceous, bitter, citrus notes and light sensations of mango. At the sip it is drinkable, light and clean, with long hints of hopsThe Ippa di Baladin is the Italian interpretation of the famous Indian Pale Ale according to Teo Musso style, a pioneer in the world of craft beers. Made with hops grown on Italian soil, it shines in the glass with its amber mantle characterized by a pleasant white foam. The nose is characterized by intense herbaceous, bitter, citrus notes and light sensations of mango. At the sip it is drinkable, light and clean, with long hints of hops',
  '"Lago Nero" is a Stout beer inspired by the Irish model and characterized by strong smoky notes. It reveals a roasted and spicy olfactory profile, with notes of smoked speck, bitter cocoa, coffee beans and a fine hopping. At the sip it shows the classic note of toasted malt with a flowing and pleasantly bitter body',
  '"Full Moon" by Triporteur brewery is a dark beer inspired by typical Quadrupel from Belgium, enhanced by a rest in toasted belgium oak. It opens ont the nose to intense and warm aromas of candied apple, caramel and licorice with toasty and woody undertones. The sip is rich and generous, well balanced between sugar content and fruity nuance, round and really persistent',
  '"Admiral" by 32 - Via dei Birrai brewery is an amber top fermented beer with a dark color and ruby nuances with a compact and persistent beige foam. The nose gives off typical aromas of malt and caramel with returns of yeast and roasting. In the mouth it is full, with a beautiful freshness and a pleasant herbaceous and bitter finish given by the Admiral hop used',
  'The “Strike” Beer by BAV is an Italian IPA produced with refermentation in bottle and with an high IBU value. It is characterized by fragrant and citrusy perfumes, with nuances of exotic fruits, herbs and yeasts. The taste is frewsh, well-structured and slightly fruity, easy drinking despite to the intense and long bittery hop aromas',
  'IPA by Brigà is an Piedmontese interpretation of the most loved (and abused) brew style that exists: the India Pale Ale. It is a top fermented beer, made from pure Pian della Mussa water and raw materials grown in organic agriculture. Amber with a tropical, herbaceous and citrusy stamp, it closes with a bitter tip typical from the style',
  '"Ghisa" by Lambrate brewery is a dark beer in Smoked Stout style that impresses for its natural balance between smoked scents, typical of this category, and flowing drinkability. On the nose it opens to coffee, cappuccino, maron glacé and chestnuts aromas with a dense and smooth sip, lively and delicate rich of smoked, coffee and toffe undertones that perfectly remind olfactory aromas',
  '"Vincent Vega" is the protagonist of the cult film Pulp Fiction to which Retorto has dedicated this amber beer inspired by the triples of abbey. With a particularly creamy and persistent foam cap, it reveals itself in a tawny, caramel-colored coat with citrus scents due to red orange and pink grapefruit. It gives enveloping and full sensations, without being cloying, with a particularly appetizing dry finish',
];
