/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { FinanceDefinitions } from '../../..';
import account_type from './account_type';

const finance: FinanceDefinitions = {
  account_type,
};

export default finance;
