/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import cell_phone from './cell_phone';
import internet from './internet';
import location from './location';
import person from './person';
import phone_number from './phone_number';

const fr_BE: LocaleDefinition = {
  title: 'French (Belgium)',
  cell_phone,
  internet,
  location,
  person,
  phone_number,
};

export default fr_BE;
