/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CompanyDefinition } from '../../..';
import name_pattern from './name_pattern';
import prefix from './prefix';

const company: CompanyDefinition = {
  name_pattern,
  prefix,
};

export default company;
