/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { TireDefinitions } from '../../..';
import brand from './brand';
import name_ from './name';
import season from './season';

const tire: TireDefinitions = {
  brand,
  name: name_,
  season,
};

export default tire;
