/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CompanyDefinitions } from '../../..';
import name_patterns from './name_patterns';
import suffix from './suffix';

const company: CompanyDefinitions = {
  name_patterns,
  suffix,
};

export default company;
