/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import cell_phone from './cell_phone';
import date from './date';
import internet from './internet';
import location from './location';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';

/**
 * The locale data for the `ro_MD` locale.
 *
 * - Language: Romanian (Moldova)
 * - Endonym: Română (Moldova)
 */
const ro_MD: LocaleDefinition = {
  cell_phone,
  date,
  internet,
  location,
  metadata,
  person,
  phone_number,
};

export default ro_MD;
