/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PhoneDefinitions } from '../../..';
import brand from './brand';
import camera from './camera';
import cellularTechnologies from './cellularTechnologies';
import connectivityTechnologies from './connectivityTechnologies';
import memoryStorageCapacity from './memoryStorageCapacity';
import model from './model';
import numberFormats from './numberFormats';
import os from './os';
import productDimensions from './productDimensions';
import screenSize from './screenSize';

const phone: PhoneDefinitions = {
  brand,
  camera,
  cellularTechnologies,
  connectivityTechnologies,
  memoryStorageCapacity,
  model,
  numberFormats,
  os,
  productDimensions,
  screenSize,
};

export default phone;
