/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CommerceDefinitions } from '../../..';
import color from './color';

const commerce: CommerceDefinitions = {
  color,
};

export default commerce;
