/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { WordDefinition } from '../../..';
import adjective from './adjective';
import adverb from './adverb';
import noun from './noun';

const word: WordDefinition = {
  adjective,
  adverb,
  noun,
};

export default word;
