/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PhoneNumberDefinition } from '../../..';
import area_code from './area_code';
import exchange_code from './exchange_code';
import format from './format';

const phone_number: PhoneNumberDefinition = {
  area_code,
  exchange_code,
  format,
};

export default phone_number;
