/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { SystemDefinition } from '../../..';
import directoryPaths from './directoryPaths';
import mimeTypes from './mimeTypes';

const system: SystemDefinition = {
  directoryPaths,
  mimeTypes,
};

export default system;
