/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { SystemDefinition } from '../../..';
import directory_paths from './directory_paths';
import mime_types from './mime_types';

const system: SystemDefinition = {
  directory_paths,
  mime_types,
};

export default system;
