/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { SystemDefinition } from '../../..';
import directory_path from './directory_paths';
import mime_type from './mime_types';

const system: SystemDefinition = {
  directory_path,
  mime_type,
};

export default system;
