/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AnimalDefinitions } from '../../..';
import type_ from './type';

const animal: Partial<AnimalDefinitions> = {
  type: type_,
};

export default animal;
