export default [
  'La portada tiene diez años, la portada ocho, el depósito más de seis años. Los armoniosos y ricos sabores de Davidoff Special 53 - Capa Dominicana van a la perfección con un ron dominicano que tiene notas dulces y especiadas. Las variedades de tabaco sorprenden con notas distintivas de madera, café y cacao. El ron y el cigarro se complementan, la dulzura del ron subraya positivamente el cigarro y el cigarro le da cremosidad al ron.',
  'A pedido de muchos de nuestros clientes que extrañan su Davidoff No.1 o Cohiba Lanceros, nuestro director gerente y experto en cigarros, Mirko Pettene, ha creado un formato Lancero para nuestra Royales Limited Edition 2021. Este Lancero se lia exclusivamente a partir de 8 años. tabaco en calidad premium de cigarros Royales y viene en una edición limitada de solo 300 hermosas cajas negras de 10. Un cigarro elegante para conocedores y bon vivants.',
  "Las palabras 'poder refinado' brillan a través de este cigarro como los tubos de oro que las encierran. Una verdadera potencia respaldada con un sabor extraordinario.",
  'La historia de la marca Horacio comienza en Costa Rica, donde fue desarrollada con gran dedicación por tres amantes de los cigarros en 2008. Hoy, los cigarros premium se producen en Nicaragua, que es conocida por sus mezclas extremadamente delicadas. Las condiciones climáticas allí son ideales para la producción de tabaco de alta calidad.',
  'Hamburgo, julio de 2019. Como agradecimiento por la colaboración excepcional y duradera con los mejores proveedores de Davidoff de Alemania, Davidoff lanza una edición exclusiva estrictamente limitada de Davidoff *****. La edición de cigarros finos está limitada a 500 cajas y solo está disponible en los embajadores de cinco estrellas de David y en las tiendas insignia de Alemania',
  'Conocemos a Rocky desde hace muchos años y simplemente amamos sus puros. En un tiempo récord, Rocky se ha convertido en uno de los mejores mezcladores de puros de la época. Nosotros e innumerables aficionados de todo el mundo creemos que hace mucho tiempo que se ha convertido en un auténtico maestro en su oficio. Una prueba más de ello, por si hiciera falta algo más, es su nueva gama, que nos gustaría presentaros hoy. The Disciple estará disponible en cuatro formatos en el mercado alemán: Robusto, Toro, Bala (Figurado) y Sixty.',
  'Con Melanio Diadema serie V, Oliva está lanzando una verdadera limitada: es una mezcla ligeramente diferente en comparación con la gama estándar de Melanio serie V y también una de las primeras formas redondas dentro de la serie "boxpressed".',
  'En septiembre de 2020, se lanzó el "EPC Pledge" en dos vitolas, un Robusto llamado "Prequel" y el "Sojourn", un Toro. Ese año, la gama se convirtió en el producto imprescindible más popular del mundo de los cigarros. The Cigar Aficionado estuvo de acuerdo y, solo unos meses después, lo otorgó "Cigar of the Year" con una calificación inigualable de 98 puntos. ',
  'Los VILLIGER LA MERIDIANA son puros fuertes de Nicaragua, pero gracias al uso de una capa más suave ofrecen un placer sorprendentemente equilibrado. Las típicas notas de café achocolatadas son terrosas y profundas, mientras que son suavemente redondeadas y con mucho cuerpo. Una hermosa y compleja variedad de aromas, potente pero nunca intrusiva, que sorprende gratamente a los amantes de estos puros con una amplia gama de formatos.',
];
