/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { CigarDefinitions } from '../../..';
import brand from './brand';
import description from './description';
import line from './line';
import shape from './shape';
import strength from './strength';

const cigar: CigarDefinitions = {
  brand,
  description,
  line,
  shape,
  strength,
};

export default cigar;
