export default [
  "La page de garde a dix ans, la page de garde huit ans, le dépôt sur six ans. Les saveurs harmonieuses et riches de Davidoff Special 53 - Capa Dominicana se marient parfaitement avec un rhum dominicain aux notes douces et épicées. Les variétés de tabac surprennent par des notes distinctives de bois, de café et de cacao. Le rhum et le cigare se complètent, la douceur du rhum souligne positivement le cigare et le cigare donne l'onctuosité du rhum.",
  'A la demande de beaucoup de nos clients qui manquent leur Davidoff No.1 ou Cohiba Lanceros, notre directeur général et expert en cigares Mirko Pettene a créé un format Lancero pour notre Royales Limited Edition 2021. Cette Lancero est exclusivement roulée à partir de 8 ans tabac en qualité de cigare Royales premium et est disponible en édition limitée de seulement 300 belles boîtes noires de 10. Un cigare élégant pour les connaisseurs et les bons vivants.',
  "Les mots 'puissance raffinée' brillent à travers ce cigare comme les tubes d'or qui les enveloppent. Une véritable centrale électrique soutenue par une saveur extraordinaire.",
  "L'histoire de la marque Horacio commence au Costa Rica, où elle a été développée avec beaucoup de dévouement par trois amateurs de cigares en 2008. Aujourd'hui, les cigares haut de gamme sont produits au Nicaragua, connu pour ses mélanges extrêmement délicats. Les conditions climatiques y sont idéales pour la production de tabac de haute qualité.",
  "Hambourg, juillet 2019. En guise de remerciement pour la collaboration exceptionnelle et de longue date avec les meilleurs vendeurs Davidoff d'Allemagne, Davidoff lance une édition exclusive Davidoff ***** strictement limitée. L'édition de cigares fins est limitée à 500 caisses et uniquement disponible chez les ambassadeurs cinq étoiles David et les magasins phares en Allemagne.",
  "Nous connaissons Rocky depuis de nombreuses années et adorons tout simplement ses cigares. En un temps record, Rocky est devenu l'un des plus grands mélangeurs de cigares de l'époque. Nous et d'innombrables aficionados du monde entier pensons qu'il est depuis longtemps devenu un véritable maître dans son art. Preuve supplémentaire, s'il en fallait encore, sa nouvelle gamme que nous vous présentons aujourd'hui. Le Disciple sera disponible en quatre formats sur le marché allemand : Robusto, Toro, Bala (Figurado) et Sixty.",
  "Avec la série Melanio Diadema V, Oliva lance une véritable limitada : c'est un mélange légèrement différent par rapport à la gamme standard de la série Melanio V et aussi l'une des premières formes rondes de la série autrement 'boxpressed'.",
  "En septembre 2020, le 'EPC Pledge' est sorti en deux vitoles, un Robusto appelé 'Prequel' et le 'Sojourn', un Toro. Cette année-là, la gamme est devenue l'incontournable incontournable du monde du cigare. Le Cigar Aficionado a accepté et, quelques mois plus tard, lui a décerné le Cigare de l'année avec une note inégalée de 98 points.",
  "Les VILLIGER LA MERIDIANA sont des puros puissants du Nicaragua, mais grâce à l'utilisation d'une cape plus douce, ils offrent un plaisir étonnamment équilibré. Les notes typiques de café chocolaté sont terreuses et profondes, tout en étant légèrement arrondies et corsées. Une belle variété d'arômes complexes, puissants mais jamais envahissants et qui surprend agréablement les amateurs de ces puros aux formats très variés.",
];
