/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinitions } from '../../..';
import state from './state';

const location: LocationDefinitions = {
  state,
};

export default location;
