/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { HackerDefinitions } from '../../..';
import abbreviation from './abbreviation';
import adjective from './adjective';
import noun from './noun';
import verb from './verb';

const hacker: Partial<HackerDefinitions> = {
  abbreviation,
  adjective,
  noun,
  verb,
};

export default hacker;
