/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AirlineDefinitions } from '../../..';
import airports from './airports';

const airline: AirlineDefinitions = {
  airports,
};

export default airline;
