/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AirlineDefinitions } from '../../..';
import airlines from './airlines';
import airport from './airport';

const airline: AirlineDefinitions = {
  airlines,
  airport,
};

export default airline;
