/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';

import name_ from './name';

const en_JP: LocaleDefinition = {
  title: 'English Names (Japan)',
  name: name_,
};

export default en_JP;
