/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { WheelDefinitions } from '../../..';
import brand from './brand';
import material from './material';
import name_ from './name';

const wheel: WheelDefinitions = {
  brand,
  name: name_,
  material,
};

export default wheel;
