/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import app from './app';
import business from './business';
import cell_phone from './cell_phone';
import color from './color';
import commerce from './commerce';
import company from './company';
import finance from './finance';
import hacker from './hacker';
import internet from './internet';
import location from './location';
import lorem from './lorem';
import person from './person';
import phone_number from './phone_number';
import team from './team';

const el: LocaleDefinition = {
  title: 'Greek',
  separator: ' & ',
  app,
  business,
  cell_phone,
  color,
  commerce,
  company,
  finance,
  hacker,
  internet,
  location,
  lorem,
  person,
  phone_number,
  team,
};

export default el;
