/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import app from './app';
import cell_phone from './cell_phone';
import color from './color';
import commerce from './commerce';
import company from './company';
import finance from './finance';
import hacker from './hacker';
import internet from './internet';
import location from './location';
import lorem from './lorem';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';
import team from './team';

/**
 * The locale data for the `el` locale.
 *
 * - Language: Greek
 * - Endonym: Ελληνικά
 */
const el: LocaleDefinition = {
  app,
  cell_phone,
  color,
  commerce,
  company,
  finance,
  hacker,
  internet,
  location,
  lorem,
  metadata,
  person,
  phone_number,
  team,
};

export default el;
