/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  abbr: [
    'الأحد',
    'الأربعاء',
    'الاثنين',
    'الثلاثاء',
    'الجمعة',
    'الخميس',
    'السبت',
  ],
  wide: [
    'الأحد',
    'الأربعاء',
    'الاثنين',
    'الثلاثاء',
    'الجمعة',
    'الخميس',
    'السبت',
  ],
};
