/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import commerce from './commerce';
import company from './company';
import location from './location';
import metadata from './metadata';
import person from './person';
import word from './word';

const da: LocaleDefinition = {
  commerce,
  company,
  location,
  metadata,
  person,
  word,
};

export default da;
