/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { TableDefinitions } from '../../..';
import brand from './brand';
import material from './material';
import name_ from './name';
import room from './room';
import shape from './shape';
import style from './style';

const table: TableDefinitions = {
  brand,
  material,
  name: name_,
  room,
  shape,
  style,
};

export default table;
