/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import address from './address';
import cell_phone from './cell_phone';
import company from './company';
import date from './date';
import internet from './internet';
import lorem from './lorem';
import person from './person';
import phone_number from './phone_number';
import word from './word';

const de: LocaleDefinition = {
  title: 'German',
  address,
  cell_phone,
  company,
  date,
  internet,
  lorem,
  person,
  phone_number,
  word,
};

export default de;
