/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import book from './book';
import cell_phone from './cell_phone';
import company from './company';
import date from './date';
import flights from './flights';
import food from './food';
import internet from './internet';
import location from './location';
import lorem from './lorem';
import movie from './movie';
import person from './person';
import phone_number from './phone_number';
import recipe from './recipe';
import stays from './stays';
import word from './word';

const de: LocaleDefinition = {
  title: 'German',
  book,
  cell_phone,
  company,
  date,
  flights,
  food,
  internet,
  location,
  lorem,
  movie,
  person,
  phone_number,
  recipe,
  stays,
  word,
};

export default de;
