import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { SyntaxKind } from 'ts-morph';
import { getJsDocs, getSince } from '../apidocs/processing/jsdocs';
import { getProject } from '../apidocs/project';
import { toCamelCase, toKebabCase } from '../shared/character-case';
import { formatTypescript } from '../shared/format';
import { FILE_PATH_SRC } from '../shared/paths';
import { ImportHelper } from './import-helper';

//#region Config

const scriptPlaceholder = '<<<module>>>';
const scriptCommand = `pnpm run generate:module-tree ${scriptPlaceholder}`;

const autoGeneratedCommentHeader = `/*
 * The class body is automatically generated.
 * Run '${scriptCommand}' to update the methods from their respective files.
 */`;

function patchModuleImports(moduleName: string, importHelper: ImportHelper) {
  switch (moduleName) {
    case 'finance': {
      importHelper.removeImports('./bitcoin-address', 'BitcoinAddressFamily');
      break;
    }
    case 'helpers': {
      importHelper.addImports('./_eval', 'fakeEval');
      break;
    }
    case 'image': {
      importHelper.addTypeImports('../person', 'SexType');
      importHelper.removeImports('../../faker', 'Faker');
      break;
    }
    case 'person': {
      importHelper.removeImports('./sex-type', 'Sex');
      importHelper.removeImports('../../faker', 'Faker');
      break;
    }
    default: {
      break; // All as expected
    }
  }
}

// #endregion

const project = getProject();

const directories = project
  .getDirectoryOrThrow('src')
  .getDirectoryOrThrow('modules')
  .getDirectories();

const moduleNames = new Set(directories.map((dir) => dir.getBaseName()));

export async function generateModuleTree(onlyModule?: string): Promise<void> {
  //#region Module
  for (const directory of directories) {
    const moduleName = directory.getBaseName();

    if (onlyModule && moduleName !== onlyModule) {
      continue;
    }

    console.log(`Processing module: ${moduleName}`);
    //#region Module
    const moduleFile = directory.getSourceFileOrThrow('module.ts');

    const header = moduleFile
      .getStatements()[0]
      ?.getLeadingCommentRanges()
      .map((c) => c.getText());

    const importHelper = new ImportHelper();
    importHelper.addImports(
      '../../internal/module-base',
      'SimpleModuleBase',
      'ModuleBase'
    );
    importHelper.addTypeImports('../../faker', 'Faker');
    importHelper.addTypeImports(
      '../../utils/types',
      'Casing',
      'LengthStrategyType',
      'NumberOrRange'
    );
    importHelper.addTypeImports('../../internal/types', 'LiteralUnion');
    importHelper.addTypeImports(
      '../../distributors/distributor',
      'Distributor'
    );

    const exports: string[] = moduleFile
      .getExportDeclarations()
      .map((exp) => exp.getText());

    const typesFile = directory.getSourceFile('_types.ts');
    if (typesFile) {
      const typesToImport = [
        typesFile.getEnums(),
        typesFile.getTypeAliases(),
        typesFile.getInterfaces(),
      ]
        .flat()
        .filter((decl) => decl.isExported())
        .map((decl) => decl.getName());

      if (typesToImport.length > 0) {
        importHelper.addTypeImports('./_types', ...typesToImport);
      }
    }

    const content: string[] = [];
    const classes = moduleFile?.getClasses() ?? [];

    //#region Module Classes
    for (const cls of classes) {
      content.push(getJsDocs(cls).getText());
      const methods = cls
        .getMethods()
        .map((method) => [method.getName(), method] as const)
        .filter(([name]) => name !== 'fake');
      const methodNames = new Set(methods.map(([name]) => name));

      for (const [methodName, original] of methods) {
        const oldSinces = [
          ...(original.getOverloads()?.map((o) => o.getJsDocs()[0]) ?? []),
          ...original.getJsDocs(),
        ].map((jsDocs) => getSince(jsDocs));
        original.remove();

        const methodFile = directory.getSourceFileOrThrow(
          `${toKebabCase(methodName)}.ts`
        );

        const typesToImport = [
          methodFile.getEnums(),
          methodFile.getTypeAliases(),
          methodFile.getInterfaces(),
        ]
          .flat()
          .filter((decl) => decl.isExported())
          .map((decl) => decl.getName());

        importHelper.addImports(
          `./${toKebabCase(methodName)}`,
          methodName === 'sample'
            ? `${moduleName}Sample`
            : `${methodName} as ${toCamelCase(moduleName, methodName)}`
        );
        if (typesToImport.length > 0) {
          importHelper.addTypeImports(
            `./${toKebabCase(methodName)}`,
            ...typesToImport
          );
        }

        const functions = methodFile
          .getChildrenOfKind(SyntaxKind.FunctionDeclaration)
          .filter((fn) => fn.isExported())
          .filter(
            (fn) =>
              fn.getName() ===
              // moduleSample() => sample()
              (methodName === 'sample' ? `${moduleName}Sample` : methodName)
          );

        const parts: string[] = [];

        const restoreFakerTreeInvocations = (
          _: string,
          module: string,
          method: string
        ): string =>
          methodNames.has(`${module}${method}`)
            ? `faker.${moduleName}.${module}${method}(`
            : moduleNames.has(module)
              ? `faker.${module}.${toCamelCase(method)}(`
              : `faker.${module}${method}(`;

        for (const [index, child] of functions.entries()) {
          //#region Module Functions
          const jsDocs = child.getJsDocs()[0];

          if (child.hasBody()) {
            const params = child
              .getSignature()
              .getParameters()
              .slice(1)
              .map((param) => param.getName());

            child.setBodyText(
              `return ${toCamelCase(moduleName, methodName)}(this.faker.fakerCore, ${params.join(', ')});`
            );
          }

          if (jsDocs) {
            const description = jsDocs
              .getFullText()
              // Param
              .replace(' * @param fakerCore The FakerCore to use.\n', '')
              .replaceAll(/ +\*\n +\*\n/g, ' *\n')
              // Examples
              .replaceAll(
                new RegExp(`${methodName}\\(fakerCore(?:, ?)?`, 'g'),
                `faker.${moduleName}.${methodName}(`
              )
              // Since
              .replaceAll(
                / +\* @since (.*)\n/g,
                (_, since: string) => ` * @since ${oldSinces[index] ?? since}\n`
              )
              // Experimental
              .replaceAll(' *\n * @experimental\n', '')
              // Default Ref Date
              .replaceAll(
                /(?<= +\* .*?)\bgetDefaultRefDate\(fakerCore(?:, ?)?/g,
                'faker.defaultRefDate('
              )
              // Method References
              .replaceAll(
                /\b([a-z]+)([A-Z][a-zA-Z]+)\(fakerCore(?:, ?)?/g,
                restoreFakerTreeInvocations
              )
              .replaceAll(
                /\b([a-zA-Z]+)\(fakerCore(?:, ?)?/g,
                (_, method: string) =>
                  `faker.${moduleName}.${toCamelCase(method)}(`
              );

            parts.push(description);
          }

          const signature = child
            .getSignature()
            .getDeclaration()
            .getText()
            // Adapt signature
            .replace('export function ', '')
            .replace(/\((\n +)?fakerCore: FakerCore,?/, '(')
            // Adapt nested options defaults
            .replaceAll(
              /(?<= +\* .*?)\bgetDefaultRefDate\(fakerCore(?:, ?)?/g,
              'faker.defaultRefDate('
            )
            .replaceAll(
              /(?<= +\* .*?)\b([a-z]+)([A-Z][a-zA-Z]+)\(fakerCore(?:, ?)?/g,
              restoreFakerTreeInvocations
            )
            // moduleSample() => sample()
            .replaceAll(new RegExp(`^${moduleName}Sample\\(`, 'g'), 'sample(');

          parts.push(signature);
          //#endregion
        }

        cls.addMember(parts.join('\n'));
      }
      //#endregion

      const classBody = cls
        .getText()
        .replace(
          /(Module(?:Base)?) {\n( {2}\/\*\n( +\/?\*[^\n]*\n)+ {3}\*\/\n)?/s,
          '$1 {\n\n' +
            `${autoGeneratedCommentHeader.replace(scriptPlaceholder, moduleName)}\n\n`
        );

      content.push(classBody, '');
    }

    importHelper.removeUnusedImports(content.join('\n'));
    patchModuleImports(moduleName, importHelper);

    content.unshift(
      ...header,
      importHelper.generateImportStatements(),
      '',
      ...exports,
      ''
    );

    writeFileSync(
      resolve(FILE_PATH_SRC, 'modules', moduleName, 'module.ts'),
      await formatTypescript(content.join('\n')),
      'utf8'
    );
    //#endregion
  }

  //#endregion
}
