/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { TvDefinitions } from '../../..';
import brand from './brand';
import category from './category';
import description from './description';
import _name from './name';
import size from './size';

const tv: TvDefinitions = {
  brand,
  category,
  description,
  name: _name,
  size,
};

export default tv;
