/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import company from './company';
import internet from './internet';
import location from './location';
import lorem from './lorem';
import person from './person';
import phone_number from './phone_number';

const ko: LocaleDefinition = {
  title: 'Korean',
  company,
  internet,
  location,
  lorem,
  person,
  phone_number,
};

export default ko;
