/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import color from './color';
import company from './company';
import date from './date';
import internet from './internet';
import location from './location';
import lorem from './lorem';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';
import word from './word';

/**
 * The locale data for the `ko` locale.
 *
 * - Language: Korean
 * - Endonym: 한국어
 */
const ko: LocaleDefinition = {
  color,
  company,
  date,
  internet,
  location,
  lorem,
  metadata,
  person,
  phone_number,
  word,
};

export default ko;
