/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PersonDefinitions } from '../../..';
import female_first_name from './female_first_name';
import female_last_name from './female_last_name';
<<<<<<< HEAD
import female_prefix from './female_prefix';
=======
import first_name from './first_name';
>>>>>>> next
import male_first_name from './male_first_name';
import male_last_name from './male_last_name';
import male_prefix from './male_prefix';
import name_ from './name';
import prefix from './prefix';
import suffix from './suffix';

const person: PersonDefinitions = {
  female_first_name,
  female_last_name,
<<<<<<< HEAD
  female_prefix,
=======
  first_name,
>>>>>>> next
  male_first_name,
  male_last_name,
  male_prefix,
  name: name_,
  prefix,
  suffix,
};

export default person;
