/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { NameDefinitions } from '../../..';
import first_name from './first_name';
import last_name from './last_name';
import name_ from './name';

const name: Partial<NameDefinitions> = {
  first_name,
  last_name,
  name: name_,
};

export default name;
