/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { SystemDefinitions } from '../../..';
import directoryPaths from './directoryPaths';

const system: SystemDefinitions = {
  directoryPaths,
};

export default system;
