/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { WordDefinitions } from '../../..';
import adjective from './adjective';
import adverb from './adverb';

const word: WordDefinitions = {
  adjective,
  adverb,
};

export default word;
