/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { InternetDefinitions } from '../../..';
import domain_suffix from './domain_suffix';

const internet: Partial<InternetDefinitions> = {
  domain_suffix,
};

export default internet;
