/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { ScienceDefinition } from '../../..';
import chemical_element from './chemical_element';
import unit from './unit';

const science: ScienceDefinition = {
  chemical_element,
  unit,
};

export default science;
