/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import type { MedicationDefinitions } from '../../..';
import category from './category';
import description from './description';
import _format from './format';
import howToUse from './howToUse';
import manufacturer from './manufacturer';
import _name from './name';

const medication: MedicationDefinitions = {
  manufacturer,
  description,
  name: _name,
  format: _format,
  category,
  howToUse,
};

export default medication;
