/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import type { LocaleDefinition } from '.';
import af_ZA from './locales/af_ZA.json';
import ar from './locales/ar.json';
import az from './locales/az.json';
import cz from './locales/cz.json';
import de from './locales/de.json';
import de_AT from './locales/de_AT.json';
import de_CH from './locales/de_CH.json';
import el from './locales/el.json';
import en from './locales/en.json';
import en_AU from './locales/en_AU.json';
import en_AU_ocker from './locales/en_AU_ocker.json';
import en_BORK from './locales/en_BORK.json';
import en_CA from './locales/en_CA.json';
import en_GB from './locales/en_GB.json';
import en_GH from './locales/en_GH.json';
import en_IE from './locales/en_IE.json';
import en_IND from './locales/en_IND.json';
import en_NG from './locales/en_NG.json';
import en_US from './locales/en_US.json';
import en_ZA from './locales/en_ZA.json';
import es from './locales/es.json';
import es_MX from './locales/es_MX.json';
import fa from './locales/fa.json';
import fi from './locales/fi.json';
import fr from './locales/fr.json';
import fr_BE from './locales/fr_BE.json';
import fr_CA from './locales/fr_CA.json';
import fr_CH from './locales/fr_CH.json';
import ge from './locales/ge.json';
import he from './locales/he.json';
import hr from './locales/hr.json';
import hu from './locales/hu.json';
import hy from './locales/hy.json';
import id_ID from './locales/id_ID.json';
import it from './locales/it.json';
import ja from './locales/ja.json';
import ko from './locales/ko.json';
import lv from './locales/lv.json';
import mk from './locales/mk.json';
import nb_NO from './locales/nb_NO.json';
import ne from './locales/ne.json';
import nl from './locales/nl.json';
import nl_BE from './locales/nl_BE.json';
import pl from './locales/pl.json';
import pt_BR from './locales/pt_BR.json';
import pt_PT from './locales/pt_PT.json';
import ro from './locales/ro.json';
import ru from './locales/ru.json';
import sk from './locales/sk.json';
import sv from './locales/sv.json';
import tr from './locales/tr.json';
import uk from './locales/uk.json';
import ur from './locales/ur.json';
import vi from './locales/vi.json';
import zh_CN from './locales/zh_CN.json';
import zh_TW from './locales/zh_TW.json';
import zu_ZA from './locales/zu_ZA.json';

export type KnownLocale =
  | 'af_ZA'
  | 'ar'
  | 'az'
  | 'cz'
  | 'de'
  | 'de_AT'
  | 'de_CH'
  | 'el'
  | 'en'
  | 'en_AU'
  | 'en_AU_ocker'
  | 'en_BORK'
  | 'en_CA'
  | 'en_GB'
  | 'en_GH'
  | 'en_IE'
  | 'en_IND'
  | 'en_NG'
  | 'en_US'
  | 'en_ZA'
  | 'es'
  | 'es_MX'
  | 'fa'
  | 'fi'
  | 'fr'
  | 'fr_BE'
  | 'fr_CA'
  | 'fr_CH'
  | 'ge'
  | 'he'
  | 'hr'
  | 'hu'
  | 'hy'
  | 'id_ID'
  | 'it'
  | 'ja'
  | 'ko'
  | 'lv'
  | 'mk'
  | 'nb_NO'
  | 'ne'
  | 'nl'
  | 'nl_BE'
  | 'pl'
  | 'pt_BR'
  | 'pt_PT'
  | 'ro'
  | 'ru'
  | 'sk'
  | 'sv'
  | 'tr'
  | 'uk'
  | 'ur'
  | 'vi'
  | 'zh_CN'
  | 'zh_TW'
  | 'zu_ZA';

export type KnownLocales = Record<KnownLocale, LocaleDefinition>;

const locales: KnownLocales = {
  af_ZA,
  ar,
  az,
  cz,
  de,
  de_AT,
  de_CH,
  el,
  en,
  en_AU,
  en_AU_ocker,
  en_BORK,
  en_CA,
  en_GB,
  en_GH,
  en_IE,
  en_IND,
  en_NG,
  en_US,
  en_ZA,
  es,
  es_MX,
  fa,
  fi,
  fr,
  fr_BE,
  fr_CA,
  fr_CH,
  ge,
  he,
  hr,
  hu,
  hy,
  id_ID,
  it,
  ja,
  ko,
  lv,
  mk,
  nb_NO,
  ne,
  nl,
  nl_BE,
  pl,
  pt_BR,
  pt_PT,
  ro,
  ru,
  sk,
  sv,
  tr,
  uk,
  ur,
  vi,
  zh_CN,
  zh_TW,
  zu_ZA,
};

export default locales;
