/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { ColorDefinitions } from '../../..';
import css_function from './css_function';
import css_space from './css_space';

const color: ColorDefinitions = {
  css_function,
  css_space,
};

export default color;
