/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import animal from './animal';
import cell_phone from './cell_phone';
import color from './color';
import date from './date';
import internet from './internet';
import location from './location';
import person from './person';

const th: LocaleDefinition = {
  title: 'TODO: Insert Title for th',
  animal,
  cell_phone,
  color,
  date,
  internet,
  location,
  person,
};

export default th;
