/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import cell_phone from './cell_phone';
import color from './color';
import commerce from './commerce';
import internet from './internet';
import location from './location';
import person from './person';
import phone_number from './phone_number';

const tr: LocaleDefinition = {
  title: 'Turkish',
  cell_phone,
  color,
  commerce,
  internet,
  location,
  person,
  phone_number,
};

export default tr;
