/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AnimalDefinition } from '../../..';
import bear from './bear';
import cetacean from './cetacean';
import crocodilia from './crocodilia';
import fish from './fish';
import insect from './insect';
import lion from './lion';
import pet_name from './pet_name';
import rabbit from './rabbit';
import rodent from './rodent';
import type_ from './type';

const animal: AnimalDefinition = {
  bear,
  cetacean,
  crocodilia,
  fish,
  insect,
  lion,
  pet_name,
  rabbit,
  rodent,
  type: type_,
};

export default animal;
