/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'Ceturtdiena',
    'Otrdiena',
    'Piektdiena',
    'Pirmdiena',
    'Sestdiena',
    'Svētdiena',
    'Trešdiena',
  ],
  wide_context: [
    'ceturtdien',
    'otrdien',
    'piektdien',
    'pirmdien',
    'sestdien',
    'svētdien',
    'trešdien',
  ],
  abbr: [
    'Ceturtd.',
    'Otrd.',
    'Piektd.',
    'Pirmd.',
    'Sestd.',
    'Svētd.',
    'Trešd.',
  ],
  abbr_context: ['cet.', 'otr.', 'pk.', 'pr.', 'se.', 'sv.', 'tr.'],
};
