/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: ['星期一', '星期三', '星期二', '星期五', '星期六', '星期四', '星期日'],
  abbr: ['週一', '週三', '週二', '週五', '週六', '週四', '週日'],
};
