/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinitions } from '../../..';
import city_name from './city_name';
import city_pattern from './city_pattern';
import city_suffix from './city_suffix';
import postcode from './postcode';
import secondary_address from './secondary_address';
import state from './state';
import state_abbr from './state_abbr';
import street_name from './street_name';
import street_pattern from './street_pattern';
import street_suffix from './street_suffix';

const location: LocationDefinitions = {
  city_name,
  city_pattern,
  city_suffix,
  postcode,
  secondary_address,
  state,
  state_abbr,
  street_name,
  street_pattern,
  street_suffix,
};

export default location;
