/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import internet from './internet';

const global: LocaleDefinition = {
  title: 'Global',
  internet,
};

export default global;
