/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import color from './color';

const global: LocaleDefinition = {
  title: 'Global',
  color,
};

export default global;
