/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { WordDefinitions } from '../../..';
import adjective from './adjective';
import adverb from './adverb';
import conjunction from './conjunction';
import interjection from './interjection';
import noun from './noun';
import verb from './verb';

const word: WordDefinitions = {
  adjective,
  adverb,
  conjunction,
  interjection,
  noun,
  verb,
};

export default word;
