/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import color from './color';
import commerce from './commerce';
import company from './company';
import internet from './internet';
import location from './location';
import person from './person';
import phone_number from './phone_number';
import science from './science';
import word from './word';

const nb_NO: LocaleDefinition = {
  title: 'Norwegian',
  color,
  commerce,
  company,
  internet,
  location,
  person,
  phone_number,
  science,
  word,
};

export default nb_NO;
