/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../../definitions';
import animal from './animal';
import color from './color';
import commerce from './commerce';
import company from './company';
import food from './food';
import internet from './internet';
import location from './location';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';
import science from './science';
import vehicle from './vehicle';
import word from './word';

/**
 * The locale data for the `nb_NO` locale.
 *
 * - Language: Norwegian (Norway)
 * - Endonym: Norsk bokmål (Norge)
 */
const nb_NO: LocaleDefinition = {
  animal,
  color,
  commerce,
  company,
  food,
  internet,
  location,
  metadata,
  person,
  phone_number,
  science,
  vehicle,
  word,
};

export default nb_NO;
