/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PersonDefinitions } from '../../..';
import last_name_patterns from './last_name_patterns';

const person: PersonDefinitions = {
  last_name_patterns,
};

export default person;
