/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinitions } from '../../..';
import city from './city';
import city_name from './city_name';
import country from './country';
import default_country from './default_country';
import secondary_address from './secondary_address';
import state from './state';
import street from './street';
import street_address from './street_address';
import street_prefix from './street_prefix';

const location: LocationDefinitions = {
  city,
  city_name,
  country,
  default_country,
  secondary_address,
  state,
  street,
  street_address,
  street_prefix,
};

export default location;
