/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinition } from '../../..';
import building_number from './building_number';
import city_pattern from './city_pattern';
import city_prefix from './city_prefix';
import city_suffix from './city_suffix';
import postcode from './postcode';
import state from './state';
import state_abbr from './state_abbr';
import street_address from './street_address';
import street_pattern from './street_pattern';
import street_suffix from './street_suffix';

const location: LocationDefinition = {
  building_number,
  city_pattern,
  city_prefix,
  city_suffix,
  postcode,
  state,
  state_abbr,
  street_address,
  street_pattern,
  street_suffix,
};

export default location;
