/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PhoneNumberDefinitions } from '../../..';
import area_code from './area_code';
import formats from './formats';

const phone_number = {
  area_code,
  formats,
} as PhoneNumberDefinitions;

export default phone_number;
