/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { PersonDefinitions } from '../../..';
import last_name_pattern from './last_name_pattern';
import name_ from './name';

const person: PersonDefinitions = {
  last_name_pattern,
  name: name_,
};

export default person;
