/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { AttractionDefinitions } from '../../..';
import age from './age';
import category from './category';
import description from './description';
import height from './height';
import intensity from './intensity';
import name_ from './name';
import recommended from './recommended';

const attraction: AttractionDefinitions = {
  age,
  category,
  description,
  height,
  intensity,
  name: name_,
  recommended,
};

export default attraction;
