export default [
  'Il frontespizio ha dieci anni, il frontespizio otto, il deposito oltre sei anni. I sapori armoniosi e ricchi di Davidoff Special 53 - Capa Dominicana si sposano perfettamente con un rum dominicano dalle note dolci e speziate. Le varietà di tabacco sorprendono con note distintive di legno, caffè e cacao. Rum e sigaro si completano a vicenda, la dolcezza del rum sottolinea positivamente il sigaro e il sigaro dona cremosità al rum.',
  "Su richiesta di molti dei nostri clienti a cui manca il loro Davidoff No.1 o Cohiba Lanceros, il nostro amministratore delegato ed esperto di sigari Mirko Pettene ha creato un formato Lancero per la nostra Royales Limited Edition 2021. Questo Lancero è arrotolato esclusivamente da 8 anni. tabacco nella qualità premium di sigaro Royales ed è disponibile in un'edizione limitata di sole 300 bellissime scatole nere da 10. Un sigaro elegante per intenditori e buongustai.",
  "Le parole 'potere raffinato' brillano attraverso questo sigaro come i tubi d'oro che li racchiudono. Un vero concentrato di potenza supportato da un sapore straordinario.",
  'La storia del marchio Horacio inizia in Costa Rica, dove è stato sviluppato con grande dedizione da tre amanti dei sigari nel 2008. Oggi i sigari premium sono prodotti in Nicaragua, noto per le sue miscele estremamente delicate. Le condizioni climatiche sono ideali per una produzione di tabacco di alta qualità.',
  "Amburgo, luglio 2019. Come ringraziamento per l'eccezionale e di lunga data collaborazione con i migliori fornitori tedeschi di Davidoff, Davidoff lancia un'edizione esclusiva Davidoff ***** rigorosamente limitata. La raffinata edizione di sigari è limitata a 500 casse e solo disponibile presso gli ambasciatori a cinque stelle David e i flagship store in Germania.",
  "Conosciamo Rocky da molti anni e semplicemente amiamo i suoi sigari. A tempo di record, Rocky è diventato uno dei più grandi frullatori di sigari dell'epoca. Noi e innumerevoli appassionati in tutto il mondo crediamo che sia diventato da tempo un vero maestro nel suo mestiere. Un'ulteriore prova di ciò, se ce ne fosse bisogno, è la sua nuova gamma, che vorremmo presentarvi oggi. The Disciple sarà disponibile in quattro formati sul mercato tedesco: Robusto, Toro, Bala (Figurado) e Sixty.",
  "Con il Melanio Diadema serie V, Oliva lancia una vera e propria limitada: è una miscela leggermente diversa rispetto alla gamma standard del Melanio serie V e anche una delle prime forme tonde all'interno della serie altrimenti 'scatolata'.",
  "Nel settembre 2020, 'EPC Pledge' è stato rilasciato in due vitolas, un Robusto chiamato 'Prequel' e il 'Sojourn', un Toro. Quell'anno, la gamma si è trasformata nel must-have più caldo del mondo dei sigari. Il Cigar Aficionado ha acconsentito e, solo pochi mesi dopo, lo ha premiato come 'Cigar of the Year' con un punteggio senza pari di 98 punti.",
  "I VILLIGER LA MERIDIANA sono puros forti del Nicaragua, ma grazie all'uso di un involucro più delicato offrono un piacere sorprendentemente equilibrato. Le tipiche note cioccolatose del caffè sono terrose e profonde, pur essendo morbidamente arrotondate e corpose. Una bella e complessa varietà di aromi che è potente ma mai invadente e sorprende piacevolmente gli amanti di questi puros con un'ampia gamma di formati.",
];
