/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import cell_phone from './cell_phone';
import color from './color';
import commerce from './commerce';
import date from './date';
import internet from './internet';
import location from './location';
import person from './person';
import phone from './phone';

const pt_PT: LocaleDefinition = {
  title: 'Portuguese (Portugal)',
  cell_phone,
  color,
  commerce,
  date,
  internet,
  location,
  person,
  phone,
};

export default pt_PT;
