/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import cell_phone from './cell_phone';
import color from './color';
import commerce from './commerce';
import date from './date';
import internet from './internet';
import location from './location';
import metadata from './metadata';
import person from './person';
import phone_number from './phone_number';

const pt_PT: LocaleDefinition = {
  cell_phone,
  color,
  commerce,
  date,
  internet,
  location,
  metadata,
  person,
  phone_number,
};

export default pt_PT;
