/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { WordDefinition } from '../../..';
import adjective from './adjective';
import noun from './noun';
import verb from './verb';

const word: WordDefinition = {
  adjective,
  noun,
  verb,
};

export default word;
