/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinitions } from '../../..';
import building_number from './building_number';
import city from './city';
import city_name from './city_name';
import city_suffix from './city_suffix';
import common_street_suffix from './common_street_suffix';
import default_country from './default_country';
import postcode from './postcode';
import secondary_address from './secondary_address';
import state from './state';
import street_address from './street_address';
import street_name from './street_name';
import street_pattern from './street_pattern';
import street_prefix from './street_prefix';
import street_suffix from './street_suffix';

const location: LocationDefinitions = {
  building_number,
  city,
  city_name,
  city_suffix,
  common_street_suffix,
  default_country,
  postcode,
  secondary_address,
  state,
  street_address,
  street_name,
  street_pattern,
  street_prefix,
  street_suffix,
};

export default location;
