/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import lorem from './lorem';

const en_BORK: LocaleDefinition = {
  title: 'English (Bork)',
  lorem,
};

export default en_BORK;
