/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import lorem from './lorem';
import metadata from './metadata';
import person from './person';

const en_BORK: LocaleDefinition = {
  lorem,
  metadata,
  person,
};

export default en_BORK;
