/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { FoodDefinitions } from '../../..';
import description from './description';
import flavor from './flavor';
import name_ from './name';
import type_ from './type';

const food: FoodDefinitions = {
  description,
  flavor,
  name: name_,
  type: type_,
};

export default food;
