name: Check mergable by label

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - labeled
      - unlabeled

permissions: {}

jobs:
  fail-by-blocking-label:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is labeled by a blocking label
        if: contains(github.event.pull_request.labels.*.name, 'do NOT merge yet') || endsWith(github.event.pull_request.labels.*.name, 'on hold')
        run: |
          echo "This PR is blocked by label 'do NOT merge yet' or 's: on hold'!"
          exit 1
