name: Integration Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1' # weekly on Mondays at 03:00

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  integration_test:
    name: Integration Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Set node version to 24
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24.19.0
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Integration Test
        run: pnpm run integration-test
