name: Publish Release

on:
  release:
    types: [published]

permissions:
  # we use a personal access token to push the release branch
  id-token: write # required for provenance/signed releases on npm

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0 # we want to push the release branch later
          token: ${{ secrets.GH_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Set node version to 24
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.16.0
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Gather release information
        run: |
          RELEASE_VERSION=$(jq -r '.version' package.json)
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          RELEASE_MAJOR=$(jq -r '.version | split(".")[0]' package.json)
          echo "RELEASE_MAJOR=$RELEASE_MAJOR" >> $GITHUB_ENV

      - name: Prepare README
        run: |
          echo -e "$(grep -P '## 📙 API Documentation' -B 10000 README.md)\n\n- [Getting Started Guide](https://fakerjs.dev/guide/)\n- [API Reference](https://fakerjs.dev/api/)\n\n$(grep -P '## 🚀 Features' -A 10000 README.md)" > README.md
          sed -i "s|/fakerjs.dev/|/v$RELEASE_MAJOR.fakerjs.dev/|g" README.md

      - name: Publish
        run: |
          pnpm publish --access public --tag next --no-git-checks --provenance

      - name: Push to Release Branch
        run: |
          git push origin $GITHUB_REF_NAME:v$RELEASE_MAJOR
