/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { FinanceDefinition } from '../../../..';
import american_express from './american_express';
import diners_club from './diners_club';
import discover from './discover';
import jcb from './jcb';
import mastercard from './mastercard';
import visa from './visa';

const credit_card: FinanceDefinition['credit_card'] = {
  american_express,
  diners_club,
  discover,
  jcb,
  mastercard,
  visa,
};

export default credit_card;
