/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import common_cell_prefix from './common_cell_prefix';
import formats from './formats';

const cell_phone = {
  common_cell_prefix,
  formats,
};

export default cell_phone;
