/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LoremDefinitions } from '../../..';

const lorem: LoremDefinitions = {};

export default lorem;
