/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
export default {
  wide: [
    'bazar',
    'bazar ertəsi',
    'cümə',
    'cümə axşamı',
    'çərşənbə',
    'çərşənbə axşamı',
    'şənbə',
  ],
  wide_context: [
    'воскресенье',
    'вторник',
    'понедельник',
    'пятница',
    'среда',
    'суббота',
    'четверг',
  ],
  abbr: ['B.', 'B.E.', 'C.', 'C.A.', 'Ç.', 'Ç.A.', 'Ş.'],
  abbr_context: ['вс', 'вт', 'пн', 'пт', 'сб', 'ср', 'чт'],
};
